import { describe, expect, it, vi, beforeEach } from "vitest";
import { mount } from "@vue/test-utils";
import RuntimeCorrelations from "@/views/runtime/components/RuntimeCorrelations.vue";
import { runtimeCorrelationsApi } from "@/api/runtimeCorrelations";

const route = { query: {} as Record<string, string> };
const router = { push: vi.fn() };
vi.mock("vue-router", () => ({ useRoute: () => route, useRouter: () => router }));
vi.mock("@/api/runtimeCorrelations", () => ({ runtimeCorrelationsApi: { execution: vi.fn(), trace: vi.fn(), audit: vi.fn(), operatorAction: vi.fn() } }));
const result = { execution: { id: "e1", tenant_id: "t1", workflow_id: "w1", workflow_version_id: "v2", created_by: "u1", retry_of_execution_id: null, resume_of_execution_id: null, status: "completed", current_node_id: null, error_code: null, error_message: null, started_at: null, ended_at: null, created_at: "2026-09-02T00:00:00Z" }, traces: { items: [{ id: "te1", tenant_id: "t1", execution_id: "e1", workflow_id: "w1", workflow_version_id: "v2", event_type: "node.completed", status: "success", trace_id: "trace-1", actor_id: "u1", node_id: "node-a", data: { latency_ms: 42 }, error_code: null, error_message: null, created_at: "2026-09-02T00:01:00Z" }], page: 1, page_size: 20, total: 1 }, audits: { items: [{ id: "audit-1", actor_id: "u1", tenant_id: "t1", workflow_id: "w1", workflow_version_id: "v2", workflow_execution_id: "e1", operator_action_id: null, action: "workflow.execution.cancel", resource_type: "workflow_execution", resource_id: "e1", request_id: "req-1", trace_id: "trace-1", status: "success", error_code: null, metadata: { reason: "operator" }, created_at: "2026-09-02T00:02:00Z" }], page: 1, page_size: 20, total: 1 }, operator_actions: [], focus_audit_id: "audit-1", focus_operator_action_id: null };
const global = { stubs: { "el-form": { template: "<form><slot/></form>" }, "el-select": { props: ["modelValue"], template: "<div><slot/></div>" }, "el-option": { template: "<option/>" }, "el-input": { props: ["modelValue"], template: "<input :value=\"modelValue\" />" }, "el-button": { props: ["loading"], emits: ["click"], template: "<button @click=\"$emit('click')\"><slot/></button>" }, "el-alert": { props: ["title"], template: "<div>{{ title }}</div>" }, "el-empty": { props: ["description"], template: "<div>{{ description }}</div>" }, "el-card": { template: "<div><slot name='header'/><slot/></div>" }, "el-tag": { template: "<span><slot/></span>" }, "el-descriptions": { template: "<div><slot/></div>" }, "el-descriptions-item": { template: "<div><slot/></div>" }, "el-table": { template: "<div><slot/></div>" }, "el-table-column": { template: "<span/>" }, "el-pagination": { template: "<div/>" } } };
beforeEach(() => { vi.clearAllMocks(); route.query = {}; vi.mocked(runtimeCorrelationsApi.execution).mockResolvedValue({ data: result } as never); vi.mocked(runtimeCorrelationsApi.trace).mockResolvedValue({ data: result } as never); vi.mocked(runtimeCorrelationsApi.audit).mockResolvedValue({ data: result } as never); vi.mocked(runtimeCorrelationsApi.operatorAction).mockResolvedValue({ data: result } as never); });

describe("RuntimeCorrelations", () => {
  it("uses execution deep-link context", () => { route.query = { execution_id: "e1", focus_type: "execution", focus_id: "e1" }; const wrapper = mount(RuntimeCorrelations, { global }); expect((wrapper.vm as any).focusType).toBe("execution"); expect((wrapper.vm as any).focusId).toBe("e1"); });
  it("returns Trace focus to the backend Execution and preserves Trace ID", async () => { route.query = { focus_type: "trace", focus_id: "trace-1" }; const wrapper = mount(RuntimeCorrelations, { global }); await (wrapper.vm as any).query(); await (wrapper.vm as any).openWorkflowLifecycle(); expect(router.push).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e1", source: "runtime-correlation", trace_id: "trace-1" } }); });
  it("returns Audit focus to the backend Execution and preserves Audit ID", async () => { route.query = { focus_type: "audit", focus_id: "audit-1" }; const wrapper = mount(RuntimeCorrelations, { global }); await (wrapper.vm as any).query(); await (wrapper.vm as any).openWorkflowLifecycle(); expect(router.push).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e1", source: "runtime-correlation", audit_id: "audit-1" } }); });
  it("focuses the concrete Trace durable fact", async () => { const wrapper = mount(RuntimeCorrelations, { global }); await (wrapper.vm as any).query(); await (wrapper.vm as any).selectTrace(result.traces.items[0]); expect((wrapper.vm as any).focusedTrace.trace_id).toBe("trace-1"); expect((wrapper.vm as any).focusedTrace.node_id).toBe("node-a"); expect((wrapper.vm as any).focusedTrace.data).toEqual({ latency_ms: 42 }); });
  it("focuses the concrete Audit durable fact", async () => { const wrapper = mount(RuntimeCorrelations, { global }); await (wrapper.vm as any).query(); await (wrapper.vm as any).selectAudit(result.audits.items[0]); expect((wrapper.vm as any).focusedAudit.id).toBe("audit-1"); expect((wrapper.vm as any).focusedAudit.trace_id).toBe("trace-1"); expect((wrapper.vm as any).focusedAudit.metadata).toEqual({ reason: "operator" }); });
});
