import { beforeEach, describe, expect, it, vi } from "vitest";
import { mount } from "@vue/test-utils";
import WorkflowLifecycle from "@/views/workflows/WorkflowLifecycle.vue";
import PageHeader from "@/components/ui/PageHeader.vue";
import SurfaceCard from "@/components/ui/SurfaceCard.vue";
import StatePanel from "@/components/ui/StatePanel.vue";
import ConfirmDialog from "@/components/ui/ConfirmDialog.vue";
import { workflowApi } from "@/api/workflows";

const router = { push: vi.fn(), replace: vi.fn() };
const route = { query: {} as Record<string, string> };
vi.mock("vue-router", () => ({ useRouter: () => router, useRoute: () => route }));
vi.mock("@/api/workflows", () => ({ workflowApi: { list: vi.fn(), versions: vi.fn(), triggers: vi.fn(), listExecutions: vi.fn(), executionAvailability: vi.fn(), triggerAvailability: vi.fn(), schedule: vi.fn(), invokeTrigger: vi.fn(), runExecution: vi.fn(), cancelExecution: vi.fn(), retryExecution: vi.fn(), resumeExecution: vi.fn(), updateTrigger: vi.fn(), deleteTrigger: vi.fn() } }));
const global = { stubs: { "el-card": { template: "<div><slot name='header'/><slot/></div>" }, "el-select": { props: ["modelValue"], emits: ["update:modelValue"], template: "<div><slot/></div>" }, "el-option": { template: "<option><slot/></option>" }, "el-button": { props: ["loading", "disabled"], emits: ["click"], template: `<button :disabled="disabled" @click="$emit('click')"><slot/></button>` }, "el-tag": { template: "<span><slot/></span>" }, "el-empty": { props: ["description"], template: "<div>{{ description }}</div>" }, "el-descriptions": { template: "<div><slot/></div>" }, "el-descriptions-item": { props: ["label"], template: "<div>{{ label }}<slot/></div>" }, "el-table": { template: "<div><slot/></div>" }, "el-table-column": { template: "<span/>" }, "el-alert": { props: ["title"], template: "<div>{{ title }}</div>" }, "el-dialog": { props: ["modelValue", "title"], template: "<div v-if=\"modelValue\"><strong>{{ title }}</strong><slot/><slot name='footer'/></div>" }, "el-icon": { template: "<i><slot/></i>" } }, directives: { loading: () => undefined } };
const workflow = { id: "w1", name: "订单审批", description: "", owner_id: "u1", tenant_id: "t1", status: "published", published_version_id: "v2", created_at: "2026-08-30T08:00:00Z", updated_at: "2026-08-30T08:10:00Z" };
const version = { id: "v2", workflow_id: "w1", version: 2, definition: {}, status: "published", created_by: "u1", created_at: "2026-08-30T08:05:00Z" };
const execution = { id: "e1", tenant_id: "t1", workflow_id: "w1", workflow_version_id: "v2", created_by: "u1", status: "completed", input_data: {}, created_at: "2026-08-30T08:00:00Z" };
const failedExecution = { ...execution, id: "e2", status: "failed", current_node_id: "approval", error_code: "TIMEOUT", error_message: "节点执行超时" };
const manualTrigger = { id: "t1", tenant_id: "t1", workflow_id: "w1", name: "人工执行", trigger_type: "manual", status: "enabled", config: {}, created_by: "u1", created_at: "2026-08-30T08:00:00Z", updated_at: "2026-08-30T08:00:00Z" };
function action(action: string, allowed: boolean, extra: Record<string, unknown> = {}) { return { action, allowed, reason_code: allowed ? "AVAILABLE" : "ACTION_NOT_ALLOWED", requires_confirmation: action !== "run" && action !== "invoke", requires_idempotency_key: action === "retry" || action === "invoke", idempotent: true, description: action, ...extra }; }
function executionActionsFor(data: any) { if (data.status === "pending") return [action("run", true), action("cancel", true)]; if (data.status === "running") return [action("run", false), action("cancel", true)]; if (data.status === "failed") return [action("run", false), action("cancel", false), action("retry", true), action("resume", true)]; return [action("run", false), action("cancel", false), action("retry", false), action("resume", false)]; }
function mockDetails(data: any = execution) { const items = Array.isArray(data) ? data : [data]; vi.mocked(workflowApi.versions).mockResolvedValue({ data: [version] } as never); vi.mocked(workflowApi.triggers).mockResolvedValue({ data: [manualTrigger] } as never); vi.mocked(workflowApi.listExecutions).mockResolvedValue({ data: items } as never); vi.mocked(workflowApi.executionAvailability).mockImplementation(async (id: string) => ({ data: { resource_type: "workflow_execution", resource_id: id, status: items.find((item) => item.id === id)?.status || "completed", actions: executionActionsFor(items.find((item) => item.id === id) || execution) } } as never)); vi.mocked(workflowApi.triggerAvailability).mockResolvedValue({ data: { resource_type: "workflow_trigger", resource_id: "t1", status: "enabled", trigger_type: "manual", actions: [action("invoke", true), action("delete", true), action("enable", false), action("disable", true)] } } as never); vi.mocked(workflowApi.schedule).mockResolvedValue({ data: { id: "s1", trigger_id: "t1", lease_active: false } } as never); }
beforeEach(() => { vi.clearAllMocks(); route.query = {}; vi.mocked(workflowApi.list).mockResolvedValue({ data: [workflow] } as never); mockDetails(); vi.mocked(workflowApi.invokeTrigger).mockResolvedValue({ data: { ...execution, id: "e3", status: "pending" } } as never); vi.mocked(workflowApi.runExecution).mockResolvedValue({ data: { ...execution, status: "running" } } as never); vi.mocked(workflowApi.cancelExecution).mockResolvedValue({ data: { ...execution, status: "cancelled" } } as never); vi.mocked(workflowApi.retryExecution).mockResolvedValue({ data: { ...execution, id: "e3", status: "pending", retry_of_execution_id: "e1" } } as never); vi.mocked(workflowApi.resumeExecution).mockResolvedValue({ data: { ...execution, id: "e4", status: "pending", resume_checkpoint_sequence: 3 } } as never); vi.mocked(workflowApi.updateTrigger).mockResolvedValue({ data: manualTrigger } as never); vi.mocked(workflowApi.deleteTrigger).mockResolvedValue({ data: {} } as never); });
const vm = (wrapper: ReturnType<typeof mount>) => wrapper.vm as any;
async function waitForReady(wrapper: ReturnType<typeof mount>) { await vi.waitFor(() => expect(vm(wrapper).pageState).toBe("success")); }

describe("WorkflowLifecycle", () => {
  it("uses shared page header and surface card patterns", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).selected.name).toBe("订单审批"); expect(wrapper.findComponent(PageHeader).exists()).toBe(true); expect(wrapper.findAllComponents(SurfaceCard).length).toBeGreaterThanOrEqual(3); });
  it("uses shared error and permission states", async () => { vi.mocked(workflowApi.list).mockRejectedValueOnce(new Error("failure")); const errorWrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(errorWrapper.findComponent(StatePanel).props("state")).toBe("error")); vi.mocked(workflowApi.list).mockRejectedValueOnce({ response: { status: 403 } }); const permissionWrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(permissionWrapper.findComponent(StatePanel).props("state")).toBe("permission")); });
  it("renders real workflow lifecycle data", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).selected.name).toBe("订单审批"); expect(vm(wrapper).versions).toEqual([version]); expect(vm(wrapper).triggers).toEqual([manualTrigger]); expect(vm(wrapper).executions).toEqual([execution]); });
  it("restores workflow, execution and diagnostic deep-link context", async () => { route.query = { workflow_id: "w1", execution_id: "e2", trace_id: "trace-1", source: "runtime-correlation" }; mockDetails([execution, failedExecution]); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).selectedId).toBe("w1"); expect(vm(wrapper).focusedExecutionId).toBe("e2"); expect(vm(wrapper).diagnosticFocus).toBe("trace"); expect(vm(wrapper).diagnosticFocusId).toBe("trace-1"); expect(wrapper.text()).toContain("反向诊断上下文"); expect(wrapper.text()).toContain("trace-1"); });
  it("restores Audit context and keeps the exact Audit ID", async () => { route.query = { workflow_id: "w1", execution_id: "e1", audit_id: "audit-1", source: "runtime-correlation" }; const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).diagnosticFocus).toBe("audit"); expect(vm(wrapper).diagnosticFocusId).toBe("audit-1"); expect(wrapper.text()).toContain("audit-1"); });
  it("continues Trace context back to Runtime with the exact Execution and Trace IDs", async () => { route.query = { workflow_id: "w1", execution_id: "e2", trace_id: "trace-1", source: "runtime-correlation" }; mockDetails([execution, failedExecution]); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(wrapper.text()).toContain("继续 Trace 诊断"); await vm(wrapper).continueDiagnostic(); expect(router.push).toHaveBeenCalledWith({ path: "/runtime", query: { tab: "correlations", source: "workflow-lifecycle", focus_type: "trace", focus_id: "trace-1", execution_id: "e2", workflow_id: "w1", workflow_version_id: "v2" } }); });
  it("continues Audit context back to Runtime with the exact Execution and Audit IDs", async () => { route.query = { workflow_id: "w1", execution_id: "e1", audit_id: "audit-1", source: "runtime-correlation" }; const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(wrapper.text()).toContain("继续 Audit 诊断"); await vm(wrapper).continueDiagnostic(); expect(router.push).toHaveBeenCalledWith({ path: "/runtime", query: { tab: "correlations", source: "workflow-lifecycle", focus_type: "audit", focus_id: "audit-1", execution_id: "e1", workflow_id: "w1", workflow_version_id: "v2" } }); });
  it("clears diagnostic context without changing the focused Execution", async () => { route.query = { workflow_id: "w1", execution_id: "e1", trace_id: "trace-1", source: "runtime-correlation" }; const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); await vm(wrapper).clearDiagnosticContext(); expect(vm(wrapper).focusedExecutionId).toBe("e1"); expect(vm(wrapper).diagnosticFocus).toBe(null); expect(router.replace).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e1", source: "workflow-lifecycle" } }); });
  it("定位 Execution 后不会把旧 Trace/Audit 上下文带到另一条 Execution", async () => { route.query = { workflow_id: "w1", execution_id: "e1", trace_id: "trace-1", source: "runtime-correlation" }; const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); await vm(wrapper).focusExecution(failedExecution); expect(vm(wrapper).diagnosticFocus).toBe(null); expect(router.replace).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e2", source: "workflow-lifecycle" } }); });
  it("定位 Execution 只更新真实 URL 上下文", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).executions.map((x:any)=>x.id)).toContain("e1"); await vm(wrapper).focusExecution(execution); expect(router.replace).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e1", source: "workflow-lifecycle" } }); });
  it("贯通 Execution 到 Runtime / Trace / Audit 的真实 ID", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).executions.map((x:any)=>x.id)).toContain("e1"); await vm(wrapper).openRuntimeExecution(execution); expect(router.push).toHaveBeenCalledWith({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: "e1", workflow_id: "w1", workflow_version_id: "v2" } }); await vm(wrapper).openRuntimeCorrelations(failedExecution); expect(router.push).toHaveBeenLastCalledWith({ path: "/runtime", query: { tab: "correlations", source: "workflow-lifecycle", focus_type: "execution", focus_id: "e2", execution_id: "e2", workflow_id: "w1", workflow_version_id: "v2" } }); });
  it("无工作流时提供明确中文空状态", async () => { vi.mocked(workflowApi.list).mockResolvedValue({ data: [] } as never); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).props("state")).toBe("empty")); expect(wrapper.text()).toContain("暂无工作流"); });
  it("详情失败后支持重新加载", async () => { vi.mocked(workflowApi.versions).mockRejectedValueOnce(new Error("detail failure")); const wrapper = mount(WorkflowLifecycle, { global }); const detailErrorPanel = () => wrapper.findAllComponents(StatePanel).find((panel) => panel.props("title") === "工作流详情加载失败"); await vi.waitFor(() => expect(detailErrorPanel()?.exists()).toBe(true)); await vm(wrapper).retryDetails(); await vi.waitFor(() => expect(vm(wrapper).detailError).toBe("")); expect(workflowApi.versions).toHaveBeenCalledTimes(2); });
  it("手动触发器确认后调用真实 API 并刷新 Execution", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); await vm(wrapper).requestInvoke(manualTrigger); expect(vm(wrapper).invokeTarget).toEqual(manualTrigger); await vm(wrapper).confirmInvoke(); expect(workflowApi.invokeTrigger).toHaveBeenCalledWith("w1", "t1", {}); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); expect(vm(wrapper).invokeTarget).toBe(null); });
  it("取消手动触发确认不会提交并清理目标", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(vm(wrapper).triggerActionAvailability(manualTrigger, "invoke")).toMatchObject({ allowed: true })); await vm(wrapper).requestInvoke(manualTrigger); expect(vm(wrapper).invokeTarget).toEqual(manualTrigger); await vm(wrapper).cancelInvoke(); expect(workflowApi.invokeTrigger).not.toHaveBeenCalled(); expect(vm(wrapper).invokeDialogVisible).toBe(false); expect(vm(wrapper).invokeTarget).toBe(null); });
  it.each([["pending", ["run", "cancel"], "run", "runExecution"], ["pending", ["run", "cancel"], "cancel", "cancelExecution"], ["running", ["cancel"], "cancel", "cancelExecution"], ["failed", ["retry", "resume"], "retry", "retryExecution"], ["failed", ["retry", "resume"], "resume", "resumeExecution"]] as const)("Execution Availability %s 返回合法操作 %s", async (status, expectedActions, actionName, apiName) => { const current = { ...execution, status }; mockDetails(current); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).executionActions(current)).toEqual(expectedActions); await vm(wrapper).requestExecutionAction(current, actionName); await vm(wrapper).confirmExecutionAction(); expect((workflowApi as any)[apiName]).toHaveBeenCalledWith("e1"); });
  it("Resume 严格尊重 Backend checkpoint eligibility", async () => { mockDetails(failedExecution); vi.mocked(workflowApi.executionAvailability).mockResolvedValue({ data: { resource_type: "workflow_execution", resource_id: "e2", status: "failed", actions: [action("retry", true), action("resume", false, { reason_code: "CHECKPOINT_NOT_ELIGIBLE" })] } } as never); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).executionActions(failedExecution)).toEqual(["retry"]); await vm(wrapper).requestExecutionAction(failedExecution, "resume"); expect(workflowApi.resumeExecution).not.toHaveBeenCalled(); });
  it("403 映射为 Permission，不把权限问题误报为状态冲突", async () => { mockDetails(failedExecution); vi.mocked(workflowApi.retryExecution).mockRejectedValueOnce({ response: { status: 403 } }); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); await vm(wrapper).requestExecutionAction(failedExecution, "retry"); await vm(wrapper).confirmExecutionAction(); expect(workflowApi.retryExecution).toHaveBeenCalledWith("e2"); });
  it("409 区分幂等冲突并保留 Backend Result Resource 语义", async () => { mockDetails(failedExecution); vi.mocked(workflowApi.retryExecution).mockRejectedValueOnce({ response: { status: 409, data: { detail: "相同 Idempotency-Key 的 Operator Action 已在处理中或此前失败" } } }); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); await vm(wrapper).requestExecutionAction(failedExecution, "retry"); await vm(wrapper).confirmExecutionAction(); expect(workflowApi.retryExecution).toHaveBeenCalledWith("e2"); });
  it("Retry 成功后展示 Result Resource 与 retry lineage，并刷新 Backend Execution", async () => { mockDetails(failedExecution); const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); await vm(wrapper).requestExecutionAction(failedExecution, "retry"); await vm(wrapper).confirmExecutionAction(); expect(workflowApi.retryExecution).toHaveBeenCalledWith("e2"); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); expect(vm(wrapper).executionTarget).toBe(null); });
  it("completed Execution 无生命周期变更操作但保留诊断入口", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await waitForReady(wrapper); expect(vm(wrapper).executionActions(execution)).toEqual([]); expect(wrapper.text()).toContain("Runtime 诊断"); expect(wrapper.text()).toContain("Trace/Audit"); });
});
