import { beforeEach, describe, expect, it, vi } from "vitest";
import { mount } from "@vue/test-utils";
import WorkflowLifecycle from "@/views/workflows/WorkflowLifecycle.vue";
import PageHeader from "@/components/ui/PageHeader.vue";
import SurfaceCard from "@/components/ui/SurfaceCard.vue";
import StatePanel from "@/components/ui/StatePanel.vue";
import ConfirmDialog from "@/components/ui/ConfirmDialog.vue";
import { workflowApi } from "@/api/workflows";

const router = { push: vi.fn(), replace: vi.fn() };
const route = { query: {} as Record<string, string> };
vi.mock("vue-router", () => ({ useRouter: () => router, useRoute: () => route }));
vi.mock("@/api/workflows", () => ({ workflowApi: { list: vi.fn(), versions: vi.fn(), triggers: vi.fn(), listExecutions: vi.fn(), schedule: vi.fn(), invokeTrigger: vi.fn(), runExecution: vi.fn(), cancelExecution: vi.fn(), retryExecution: vi.fn(), resumeExecution: vi.fn() } }));
const global = { stubs: {
  "el-card": { template: "<div><slot name='header'/><slot/></div>" }, "el-select": { props: ["modelValue"], emits: ["update:modelValue"], template: "<div><slot/></div>" }, "el-option": { template: "<option><slot/></option>" }, "el-button": { props: ["loading", "disabled"], emits: ["click"], template: `<button :disabled="disabled" @click="$emit('click')"><slot/></button>` }, "el-tag": { template: "<span><slot/></span>" }, "el-empty": { props: ["description"], template: "<div>{{ description }}</div>" }, "el-descriptions": { template: "<div><slot/></div>" }, "el-descriptions-item": { props: ["label"], template: "<div>{{ label }}<slot/></div>" }, "el-table": { template: "<div><slot/></div>" }, "el-table-column": { template: "<span/>" }, "el-alert": { props: ["title"], template: "<div>{{ title }}</div>" }, "el-dialog": { props: ["modelValue", "title"], template: "<div v-if=\"modelValue\"><strong>{{ title }}</strong><slot/><slot name='footer'/></div>" }, "el-icon": { template: "<i><slot/></i>" },
}, directives: { loading: () => undefined } };
const workflow = { id: "w1", name: "订单审批", description: "", owner_id: "u1", tenant_id: "t1", status: "published", published_version_id: "v2", created_at: "2026-08-30T08:00:00Z", updated_at: "2026-08-30T08:10:00Z" };
const version = { id: "v2", workflow_id: "w1", version: 2, definition: {}, status: "published", created_by: "u1", created_at: "2026-08-30T08:05:00Z" };
const execution = { id: "e1", tenant_id: "t1", workflow_id: "w1", workflow_version_id: "v2", created_by: "u1", status: "completed", input_data: {}, created_at: "2026-08-30T08:00:00Z" };
const failedExecution = { ...execution, id: "e2", status: "failed", current_node_id: "approval", error_code: "TIMEOUT", error_message: "节点执行超时" };
const manualTrigger = { id: "t1", tenant_id: "t1", workflow_id: "w1", name: "人工执行", trigger_type: "manual", status: "enabled", config: {}, created_by: "u1", created_at: "2026-08-30T08:00:00Z", updated_at: "2026-08-30T08:00:00Z" };
function mockDetails(data: any = execution) { vi.mocked(workflowApi.versions).mockResolvedValue({ data: [version] } as never); vi.mocked(workflowApi.triggers).mockResolvedValue({ data: [manualTrigger] } as never); vi.mocked(workflowApi.listExecutions).mockResolvedValue({ data: Array.isArray(data) ? data : [data] } as never); }
beforeEach(() => { vi.clearAllMocks(); route.query = {}; vi.mocked(workflowApi.list).mockResolvedValue({ data: [workflow] } as never); mockDetails(); vi.mocked(workflowApi.invokeTrigger).mockResolvedValue({ data: { ...execution, id: "e3", status: "pending" } } as never); vi.mocked(workflowApi.runExecution).mockResolvedValue({ data: { ...execution, status: "running" } } as never); vi.mocked(workflowApi.cancelExecution).mockResolvedValue({ data: { ...execution, status: "cancelled" } } as never); vi.mocked(workflowApi.retryExecution).mockResolvedValue({ data: { ...execution, id: "e3", status: "pending" } } as never); vi.mocked(workflowApi.resumeExecution).mockResolvedValue({ data: { ...execution, id: "e4", status: "pending" } } as never); });

const vm = (wrapper: ReturnType<typeof mount>) => wrapper.vm as any;

describe("WorkflowLifecycle", () => {
  it("uses shared page header and surface card patterns", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(wrapper.findComponent(PageHeader).exists()).toBe(true); expect(wrapper.findAllComponents(SurfaceCard).length).toBeGreaterThanOrEqual(3); });
  it("uses shared error and permission states", async () => { vi.mocked(workflowApi.list).mockRejectedValueOnce(new Error("failure")); const errorWrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(errorWrapper.findComponent(StatePanel).props("state")).toBe("error")); vi.mocked(workflowApi.list).mockRejectedValueOnce({ response: { status: 403 } }); const permissionWrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(permissionWrapper.findComponent(StatePanel).props("state")).toBe("permission")); });
  it("renders real workflow lifecycle data", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(wrapper.text()).toContain("当前生效版本"); expect(wrapper.text()).toContain("触发与调度"); expect(wrapper.text()).toContain("已完成"); });
  it("restores workflow and execution deep-link context", async () => { route.query = { workflow_id: "w1", execution_id: "e2", source: "runtime" }; mockDetails([execution, failedExecution]); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("当前 Execution 定位")); expect(vm(wrapper).selectedId).toBe("w1"); expect(vm(wrapper).focusedExecutionId).toBe("e2"); expect(vm(wrapper).focusedExecution.error_code).toBe("TIMEOUT"); expect(vm(wrapper).focusedExecution.error_message).toBe("节点执行超时"); });
  it("定位 Execution 只更新真实 URL 上下文", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("e1")); await vm(wrapper).focusExecution(execution); expect(router.replace).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e1", source: "workflow-lifecycle" } }); });
  it("贯通 Execution 到 Runtime / Trace / Audit 的真实 ID", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("Runtime 诊断")); await vm(wrapper).openRuntimeExecution(execution); expect(router.push).toHaveBeenCalledWith({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: "e1", workflow_id: "w1", workflow_version_id: "v2" } }); await vm(wrapper).openRuntimeCorrelations(failedExecution); expect(router.push).toHaveBeenLastCalledWith({ path: "/runtime", query: { tab: "correlations", source: "workflow-lifecycle", focus_type: "execution", focus_id: "e2", execution_id: "e2", workflow_id: "w1", workflow_version_id: "v2" } }); });
  it("无工作流时提供明确中文空状态", async () => { vi.mocked(workflowApi.list).mockResolvedValue({ data: [] } as never); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).props("state")).toBe("empty")); expect(wrapper.text()).toContain("暂无工作流"); });
  it("详情失败后支持重新加载", async () => { vi.mocked(workflowApi.versions).mockRejectedValueOnce(new Error("detail failure")); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).props("title")).toBe("工作流详情加载失败")); await vm(wrapper).retryDetails(); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).exists()).toBe(false)); expect(workflowApi.versions).toHaveBeenCalledTimes(2); });
  it("手动触发器确认后调用真实 API 并刷新 Execution", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("触发与调度")); await vm(wrapper).requestInvoke(manualTrigger); expect(wrapper.findComponent(ConfirmDialog).exists()).toBe(true); await vm(wrapper).confirmInvoke(); expect(workflowApi.invokeTrigger).toHaveBeenCalledWith("w1", "t1", {}); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); });
  it.each([
    ["pending", ["run", "cancel"], "run", "runExecution"], ["pending", ["run", "cancel"], "cancel", "cancelExecution"], ["running", ["cancel"], "cancel", "cancelExecution"], ["failed", ["retry", "resume"], "retry", "retryExecution"], ["failed", ["retry", "resume"], "resume", "resumeExecution"],
  ] as const)("Execution 状态 %s 暴露合法操作 %s", async (status, expectedActions, action, apiName) => { const current = { ...execution, status }; mockDetails(current); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("e1")); expect(vm(wrapper).executionActions(current)).toEqual(expectedActions); await vm(wrapper).requestExecutionAction(current, action); await vm(wrapper).confirmExecutionAction(); expect((workflowApi as any)[apiName]).toHaveBeenCalledWith("e1"); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); });
  it("completed Execution 无生命周期变更操作但保留诊断入口", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("Runtime 诊断")); expect(vm(wrapper).executionActions(execution)).toEqual([]); expect(wrapper.text()).toContain("Trace / Audit"); });
});
