import { beforeEach, describe, expect, it, vi } from "vitest";
import { mount } from "@vue/test-utils";
import WorkflowLifecycle from "@/views/workflows/WorkflowLifecycle.vue";
import { workflowApi } from "@/api/workflows";

const router = { push: vi.fn(), replace: vi.fn() };
const route = { query: {} as Record<string, string> };
vi.mock("vue-router", () => ({ useRouter: () => router, useRoute: () => route }));
vi.mock("@/api/workflows", () => ({ workflowApi: { list: vi.fn(), versions: vi.fn(), triggers: vi.fn(), listExecutions: vi.fn(), executionAvailability: vi.fn(), triggerAvailability: vi.fn(), schedule: vi.fn(), invokeTrigger: vi.fn(), enableTrigger: vi.fn(), disableTrigger: vi.fn(), deleteTrigger: vi.fn(), runExecution: vi.fn(), cancelExecution: vi.fn(), retryExecution: vi.fn(), resumeExecution: vi.fn(), updateTrigger: vi.fn() } }));
const global = { stubs: { PageHeader: { template: "<div><slot name='actions'/></div>" }, SurfaceCard: { template: "<section><slot/><slot name='header'/></section>" }, StatePanel: { props: ["state", "title"], template: "<div>{{ title }}</div>" }, ConfirmDialog: { props: ["modelValue", "title"], template: "<div v-if='modelValue'>{{ title }}<slot/></div>" }, "el-select": { template: "<div><slot/></div>" }, "el-option": { template: "<option/>" }, "el-button": { props: ["disabled"], template: "<button :disabled='disabled'><slot/></button>" }, "el-tag": { template: "<span><slot/></span>" }, "el-table": { template: "<div><slot/></div>" }, "el-table-column": { template: "<span/>" }, "el-alert": { template: "<div><slot/></div>" }, "el-descriptions": { template: "<div><slot/></div>" }, "el-descriptions-item": { template: "<div><slot/></div>" }, "el-dialog": { template: "<div><slot/><slot name='footer'/></div>" }, "el-form": { template: "<form><slot/></form>" }, "el-form-item": { template: "<label><slot/></label>" }, "el-input": { template: "<input/>" }, "el-input-number": { template: "<input/>" } }, directives: { loading: () => undefined } };
const workflow = { id: "w1", name: "订单审批", description: "", owner_id: "u1", tenant_id: "t1", status: "published", published_version_id: "v1", created_at: "2026-09-04T08:00:00Z", updated_at: "2026-09-04T08:00:00Z" };
const version = { id: "v1", workflow_id: "w1", version: 1, definition: {}, status: "published", created_by: "u1", created_at: "2026-09-04T08:00:00Z" };
const enabledTrigger = { id: "t1", tenant_id: "t1", workflow_id: "w1", name: "人工执行", trigger_type: "manual", status: "enabled", config: {}, created_by: "u1", created_at: "2026-09-04T08:00:00Z", updated_at: "2026-09-04T08:00:00Z" };
const disabledTrigger = { ...enabledTrigger, id: "t2", name: "Webhook", trigger_type: "webhook", status: "disabled" };
const execution = { id: "e1", tenant_id: "t1", workflow_id: "w1", workflow_version_id: "v1", created_by: "u1", status: "completed", input_data: {}, created_at: "2026-09-04T08:00:00Z" };
const availability = (action: string, allowed: boolean, reason_code = allowed ? "AVAILABLE" : "ACTION_NOT_ALLOWED") => ({ resource_type: "workflow_trigger", action, allowed, reason_code, requires_confirmation: action !== "invoke", requires_idempotency_key: action === "invoke", idempotent: true, description: action });
function setup(triggers = [enabledTrigger]) { vi.mocked(workflowApi.list).mockResolvedValue({ data: [workflow] } as never); vi.mocked(workflowApi.versions).mockResolvedValue({ data: [version] } as never); vi.mocked(workflowApi.triggers).mockResolvedValue({ data: triggers } as never); vi.mocked(workflowApi.listExecutions).mockResolvedValue({ data: [execution] } as never); vi.mocked(workflowApi.executionAvailability).mockResolvedValue({ data: { resource_type: "workflow_execution", resource_id: "e1", status: "completed", actions: [] } } as never); vi.mocked(workflowApi.triggerAvailability).mockImplementation(async (id: string) => ({ data: { resource_type: "workflow_trigger", resource_id: id, status: triggers.find((item) => item.id === id)?.status || "enabled", trigger_type: triggers.find((item) => item.id === id)?.trigger_type || "manual", actions: id === "t1" ? [availability("invoke", true), availability("enable", false, "TRIGGER_ALREADY_ENABLED"), availability("disable", true), availability("delete", true)] : [availability("invoke", false, "TRIGGER_TYPE_NOT_INVOKABLE"), availability("enable", true), availability("disable", false, "TRIGGER_ALREADY_DISABLED"), availability("delete", true)] } } as never)); vi.mocked(workflowApi.schedule).mockResolvedValue({ data: { id: "s1", trigger_id: "t1", workflow_id: "w1", enabled: true, lease_active: false } } as never); vi.mocked(workflowApi.enableTrigger).mockResolvedValue({ data: { ...disabledTrigger, status: "enabled" } } as never); vi.mocked(workflowApi.disableTrigger).mockResolvedValue({ data: { ...enabledTrigger, status: "disabled" } } as never); vi.mocked(workflowApi.deleteTrigger).mockResolvedValue({ data: enabledTrigger } as never); }
beforeEach(() => { vi.clearAllMocks(); route.query = {}; setup(); });
const vm = (wrapper: ReturnType<typeof mount>) => wrapper.vm as any;
describe("WorkflowLifecycle Trigger Operator Availability phase 3", () => {
  it("only exposes trigger actions allowed by backend availability", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(vm(wrapper).triggerActionAllowed(enabledTrigger, "invoke")).toBe(true); expect(vm(wrapper).triggerActionAllowed(enabledTrigger, "disable")).toBe(true); expect(vm(wrapper).triggerActionAllowed(enabledTrigger, "enable")).toBe(false); expect(vm(wrapper).triggerActionReason(enabledTrigger, "enable")).toBe("TRIGGER_ALREADY_ENABLED"); });
  it("requires backend availability before opening enable/disable confirmation", async () => { setup([disabledTrigger]); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); await vm(wrapper).requestTriggerStatusAction(disabledTrigger, "enable"); expect(vm(wrapper).triggerActionTarget).toEqual(disabledTrigger); expect(vm(wrapper).triggerAction).toBe("enable"); await vm(wrapper).confirmTriggerStatusAction(); expect(workflowApi.enableTrigger).toHaveBeenCalledWith("w1", "t2"); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); });
  it("blocks delete when backend denies it and refreshes after successful delete", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); await vm(wrapper).requestDeleteTrigger(enabledTrigger); expect(vm(wrapper).deleteTriggerTarget).toEqual(enabledTrigger); await vm(wrapper).confirmDeleteTrigger(); expect(workflowApi.deleteTrigger).toHaveBeenCalledWith("w1", "t1"); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); });
  it("maps 403 and 409 without hiding the lifecycle page", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(vm(wrapper).operatorErrorMessage({ response: { status: 403 } }, "触发器", "disable")).toContain("没有操作"); expect(vm(wrapper).operatorErrorMessage({ response: { status: 409, data: { detail: "Idempotency-Key already has a result" } } }, "触发器", "invoke")).toContain("幂等冲突"); expect(vm(wrapper).operatorErrorMessage({ response: { status: 409, data: { detail: "state conflict" } } }, "触发器", "disable")).toContain("状态已变化"); });
  it("keeps trigger availability as the source of truth after refresh", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(workflowApi.triggerAvailability).toHaveBeenCalledWith("t1"); expect(vm(wrapper).triggerActionAvailability(enabledTrigger, "delete").allowed).toBe(true); });
});
