import { describe, expect, it, vi, beforeEach } from "vitest";
import { mount } from "@vue/test-utils";
import WorkflowLifecycle from "@/views/workflows/WorkflowLifecycle.vue";
import PageHeader from "@/components/ui/PageHeader.vue";
import SurfaceCard from "@/components/ui/SurfaceCard.vue";
import StatePanel from "@/components/ui/StatePanel.vue";
import ConfirmDialog from "@/components/ui/ConfirmDialog.vue";
import { workflowApi } from "@/api/workflows";

const router = { push: vi.fn(), replace: vi.fn() }; const route = { query: {} as Record<string, string> };
vi.mock("vue-router", () => ({ useRouter: () => router, useRoute: () => route }));
vi.mock("@/api/workflows", () => ({ workflowApi: { list: vi.fn(), versions: vi.fn(), triggers: vi.fn(), listExecutions: vi.fn(), schedule: vi.fn(), invokeTrigger: vi.fn(), runExecution: vi.fn(), cancelExecution: vi.fn(), retryExecution: vi.fn(), resumeExecution: vi.fn() } }));
const global = { stubs: {
  "el-card": { template: "<div><slot name='header'/><slot/></div>" }, "el-select": { props: ["modelValue"], emits: ["update:modelValue"], template: "<div><slot/></div>" }, "el-option": { template: "<option><slot/></option>" }, "el-button": { props: ["loading", "disabled"], emits: ["click"], template: `<button :disabled="disabled" @click="$emit('click')"><slot/></button>` }, "el-tag": { template: "<span><slot/></span>" }, "el-empty": { props: ["description"], template: "<div>{{ description }}</div>" }, "el-descriptions": { template: "<div><slot/></div>" }, "el-descriptions-item": { props: ["label"], template: "<div>{{ label }}<slot/></div>" }, "el-table": { template: "<div><slot/></div>" }, "el-table-column": { template: "<span/>" }, "el-alert": { props: ["title"], template: "<div>{{ title }}</div>" }, "el-dialog": { props: ["modelValue", "title"], template: "<div v-if=\"modelValue\"><strong>{{ title }}</strong><slot/><slot name='footer'/></div>" },
}, directives: { loading: () => undefined } };
const workflow = { id: "w1", name: "订单审批", description: "", owner_id: "u1", tenant_id: "t1", status: "published", published_version_id: "v2", created_at: "2026-08-30T08:00:00Z", updated_at: "2026-08-30T08:10:00Z" };
const version = { id: "v2", workflow_id: "w1", version: 2, definition: {}, status: "published", created_by: "u1", created_at: "2026-08-30T08:05:00Z" };
const execution = { id: "e1", tenant_id: "t1", workflow_id: "w1", workflow_version_id: "v2", created_by: "u1", status: "completed", input_data: {}, created_at: "2026-08-30T08:00:00Z" };
const secondExecution = { ...execution, id: "e2", status: "failed", current_node_id: "approval", error_code: "TIMEOUT", error_message: "节点执行超时" };
const manualTrigger = { id: "t1", tenant_id: "t1", workflow_id: "w1", name: "人工执行", trigger_type: "manual", status: "enabled", config: {}, created_by: "u1", created_at: "2026-08-30T08:00:00Z", updated_at: "2026-08-30T08:00:00Z" };
function mockDetails(data = execution) { vi.mocked(workflowApi.versions).mockResolvedValue({ data: [version] } as never); vi.mocked(workflowApi.triggers).mockResolvedValue({ data: [manualTrigger] } as never); vi.mocked(workflowApi.listExecutions).mockResolvedValue({ data: Array.isArray(data) ? data : [data] } as never); }
beforeEach(() => { vi.clearAllMocks(); route.query = {}; vi.mocked(workflowApi.list).mockResolvedValue({ data: [workflow] } as never); mockDetails(); vi.mocked(workflowApi.invokeTrigger).mockResolvedValue({ data: { ...execution, id: "e2", status: "pending" } } as never); vi.mocked(workflowApi.runExecution).mockResolvedValue({ data: { ...execution, status: "running" } } as never); vi.mocked(workflowApi.cancelExecution).mockResolvedValue({ data: { ...execution, status: "cancelled" } } as never); vi.mocked(workflowApi.retryExecution).mockResolvedValue({ data: { ...execution, id: "e2", status: "pending", retry_of_execution_id: "e1" } } as never); vi.mocked(workflowApi.resumeExecution).mockResolvedValue({ data: { ...execution, id: "e3", status: "pending", resume_of_execution_id: "e1" } } as never); });

describe("WorkflowLifecycle", () => {
  it("uses shared page header and surface card patterns", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(wrapper.findComponent(PageHeader).exists()).toBe(true); expect(wrapper.findAllComponents(SurfaceCard).length).toBeGreaterThanOrEqual(3); });
  it("uses the shared state panel for an ordinary list failure", async () => { vi.mocked(workflowApi.list).mockRejectedValueOnce(new Error("backend failure")); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).props("state")).toBe("error")); expect(wrapper.findComponent(StatePanel).props("title")).toBe("工作流加载失败"); });
  it("uses the shared permission state for a forbidden list request", async () => { vi.mocked(workflowApi.list).mockRejectedValueOnce({ response: { status: 403 } }); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).props("state")).toBe("permission")); expect(wrapper.findComponent(StatePanel).props("title")).toBe("无权查看工作流"); });
  it("以真实 workflow/version/trigger/execution 数据构建生命周期工作台", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect(wrapper.text()).toContain("当前生效版本"); expect(wrapper.text()).toContain("触发与调度"); expect(wrapper.text()).toContain("已完成"); });
  it("从 Workflow 深链进入时按真实 workflow_id 恢复工作流上下文", async () => { route.query = { workflow_id: "w1", source: "runtime" }; const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("订单审批")); expect((wrapper.vm as { selectedId: string }).selectedId).toBe("w1"); expect(workflowApi.versions).toHaveBeenCalledWith("w1"); });
  it("从 Execution 深链进入时定位真实运行记录", async () => { route.query = { workflow_id: "w1", execution_id: "e2", source: "runtime" }; mockDetails([execution, secondExecution]); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("当前 Execution 定位")); expect((wrapper.vm as { focusedExecutionId: string }).focusedExecutionId).toBe("e2"); expect(wrapper.text()).toContain("TIMEOUT"); });
  it("定位 Execution 时只更新 WorkflowLifecycle 的真实 execution_id 上下文", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("e1")); await (wrapper.vm as any).focusExecution(execution); expect(router.replace).toHaveBeenCalledWith({ path: "/workflows/lifecycle", query: { workflow_id: "w1", execution_id: "e1", source: "workflow-lifecycle" } }); });
  it("从 Execution 进入 Runtime 时贯通 execution/workflow/version ID", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("Runtime 诊断")); await (wrapper.vm as any).openRuntimeExecution(execution); expect(router.push).toHaveBeenCalledWith({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: "e1", workflow_id: "w1", workflow_version_id: "v2" } }); });
  it("从 Execution 进入 Trace/Audit 时以 execution_id 作为关联根", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("Trace / Audit")); await (wrapper.vm as any).openRuntimeCorrelations(secondExecution); expect(router.push).toHaveBeenCalledWith({ path: "/runtime", query: { tab: "correlations", source: "workflow-lifecycle", focus_type: "execution", focus_id: "e2", execution_id: "e2", workflow_id: "w1", workflow_version_id: "v2" } }); });
  it("无工作流时提供明确中文空状态", async () => { vi.mocked(workflowApi.list).mockResolvedValue({ data: [] } as never); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("暂无工作流")); expect(wrapper.findComponent(StatePanel).props("state")).toBe("empty"); });
  it("详情请求失败时显示共享错误状态并支持重新加载", async () => { vi.mocked(workflowApi.versions).mockRejectedValueOnce(new Error("detail failure")); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).props("title")).toBe("工作流详情加载失败")); await (wrapper.vm as any).retryDetails(); await vi.waitFor(() => expect(wrapper.findComponent(StatePanel).exists()).toBe(false)); expect(workflowApi.versions).toHaveBeenCalledTimes(2); });
  it("手动触发器可确认并提交一次真实 Execution，然后刷新生命周期数据", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("立即运行")); const action = wrapper.findAll("button").find((button) => button.text() === "立即运行"); await action!.trigger("click"); expect(wrapper.findComponent(ConfirmDialog).exists()).toBe(true); await (wrapper.vm as any).confirmInvoke(); expect(workflowApi.invokeTrigger).toHaveBeenCalledWith("w1", "t1", {}); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2)); });
  it.each([
    ["pending", ["运行", "取消"], "run", "runExecution"], ["pending", ["运行", "取消"], "cancel", "cancelExecution"], ["running", ["取消"], "cancel", "cancelExecution"], ["failed", ["重试", "恢复"], "retry", "retryExecution"], ["failed", ["重试", "恢复"], "resume", "resumeExecution"],
  ] as const)("Execution 状态 %s 只暴露合法操作 %s", async (status, expectedActions, action, apiName) => {
    const current = { ...execution, status }; mockDetails(current); const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("e1")); const buttons = wrapper.findAll("button").map((button) => button.text()); for (const label of expectedActions) expect(buttons).toContain(label); for (const label of ["运行", "取消", "重试", "恢复"]) if (!(expectedActions as readonly string[]).includes(label)) expect(buttons).not.toContain(label);
    await (wrapper.vm as any).requestExecutionAction(current, action); await (wrapper.vm as any).confirmExecutionAction(); expect((workflowApi as any)[apiName]).toHaveBeenCalledWith("e1"); await vi.waitFor(() => expect(workflowApi.listExecutions).toHaveBeenCalledTimes(2));
  });
  it("completed Execution 不显示生命周期变更操作但保留 Runtime 诊断", async () => { const wrapper = mount(WorkflowLifecycle, { global }); await vi.waitFor(() => expect(wrapper.text()).toContain("Runtime 诊断")); const buttons = wrapper.findAll("button").map((button) => button.text()); for (const label of ["运行", "取消", "重试", "恢复"]) expect(buttons).not.toContain(label); expect(buttons).toContain("Runtime 诊断"); });
});
