<template>
  <div class="page"><div class="header"><div><h1>智能体工作台</h1><p>管理智能体、版本、发布生命周期，并使用真实运行过程调试。</p></div><el-button type="primary" @click="dialogVisible = true">创建智能体</el-button></div>
    <StatePanel v-if="agentState === 'loading'" state="loading" title="正在加载智能体" description="正在同步智能体及其发布状态。" />
    <StatePanel v-else-if="agentState === 'permission'" state="permission" title="无权查看智能体" description="当前账号没有智能体查询权限，请联系管理员。" />
    <StatePanel v-else-if="agentState === 'error'" state="error" title="智能体加载失败" :description="error" action-label="重试" @action="load" />
    <StatePanel v-else-if="agentState === 'empty'" state="empty" title="暂无智能体" description="创建第一个智能体后，即可管理版本、发布生命周期并进行对话调试。" action-label="创建智能体" @action="dialogVisible = true" />
    <el-alert v-if="error && agentState !== 'error' && agentState !== 'permission'" :title="error" type="error" show-icon closable @close="error = ''" />
    <el-table v-if="agentState === 'success'" :data="agents" border class="table"><el-table-column prop="name" label="名称" min-width="180" /><el-table-column label="当前生效版本" width="180"><template #default="{ row }">{{ row.version || "未发布" }}<span v-if="row.version" class="published-badge">已发布</span></template></el-table-column><el-table-column prop="model_id" label="模型" width="160" /><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" min-width="500"><template #default="{ row }"><el-button v-if="row.status === 'published'" link type="primary" @click="openPublishedVersion(row as Agent)">查看生效版本</el-button><el-button link type="primary" @click="openVersions(row as Agent)">版本</el-button><el-button link type="primary" @click="openChat(row as Agent)" :disabled="row.status !== 'published'">对话调试</el-button><el-button v-if="row.status !== 'published' && row.status !== 'archived'" link type="success" @click="publishLatest(row as Agent)">发布最新版本</el-button><el-button v-if="row.status === 'published'" link type="danger" @click="archive(row as Agent)">归档</el-button></template></el-table-column></el-table>
    <el-dialog v-model="dialogVisible" title="创建智能体" width="560px"><el-form label-width="110px"><el-form-item label="名称" required><el-input v-model="form.name" /></el-form-item><el-form-item label="描述"><el-input v-model="form.description" /></el-form-item><el-form-item label="系统提示词" required><el-input v-model="form.system_prompt" type="textarea" :rows="5" /></el-form-item><el-form-item label="模型" required><el-input v-model="form.model_id" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog>
    <el-dialog v-model="versionsVisible" :title="`智能体版本 · ${selected?.name || ''}`" width="760px"><StatePanel v-if="versionState === 'loading'" state="loading" title="正在加载版本" /><StatePanel v-else-if="versionState === 'permission'" state="permission" title="无权查看版本" description="当前账号没有版本查询权限。" /><StatePanel v-else-if="versionState === 'error'" state="error" title="版本加载失败" description="暂时无法获取版本列表，请重试。" action-label="重试" @action="selected && openVersions(selected)" /><el-alert v-if="selected?.status === 'archived'" title="智能体已归档，不能创建或发布新版本。" type="warning" show-icon /><el-table v-if="versionState === 'success' && versions.length" :data="versions" border><el-table-column prop="version" label="版本" width="130"><template #default="{ row }">{{ row.version }}<span v-if="row.is_published" class="published-badge">已发布</span></template></el-table-column><el-table-column prop="model_id" label="模型" width="160" /><el-table-column prop="created_at" label="创建时间" /><el-table-column label="操作" width="110"><template #default="{ row }"><el-button v-if="!row.is_published && selected?.status !== 'archived'" link type="success" :loading="publishingVersionId === row.id" @click="publishVersion(row as AgentVersion)">发布</el-button></template></el-table-column></el-table><StatePanel v-else-if="versionState === 'success'" state="empty" title="暂无版本" description="请先创建一个版本，再发布到运行环境。" /><el-divider /><el-form label-width="100px"><el-form-item label="系统提示词"><el-input v-model="versionForm.system_prompt" type="textarea" :rows="3" :disabled="selected?.status === 'archived'" /></el-form-item><el-form-item label="模型"><el-input v-model="versionForm.model_id" :disabled="selected?.status === 'archived'" /></el-form-item></el-form><template #footer><el-button @click="versionsVisible = false">关闭</el-button><el-button type="primary" :loading="savingVersion" :disabled="selected?.status === 'archived'" @click="createVersion">创建版本</el-button></template></el-dialog>
    <el-dialog v-model="publishedVisible" :title="`当前生效版本 · ${selected?.name || ''}`" width="720px"><StatePanel v-if="publishedState === 'loading'" state="loading" title="正在加载生效版本" /><StatePanel v-else-if="publishedState === 'permission'" state="permission" title="无权查看生效版本" description="当前账号没有生效版本查询权限。" /><StatePanel v-else-if="publishedState === 'error'" state="error" title="生效版本加载失败" description="暂时无法获取当前生效版本，请重试。" action-label="重试" @action="selected && openPublishedVersion(selected)" /><el-descriptions v-else-if="publishedState === 'success' && publishedVersion" :column="1" border><el-descriptions-item label="版本">{{ publishedVersion.version }}</el-descriptions-item><el-descriptions-item label="模型">{{ publishedVersion.model_id }}</el-descriptions-item><el-descriptions-item label="系统提示词"><div class="prompt">{{ publishedVersion.system_prompt }}</div></el-descriptions-item><el-descriptions-item label="知识库数量">{{ publishedVersion.knowledge_config?.knowledge_base_ids?.length || 0 }}</el-descriptions-item><el-descriptions-item label="检索数量">{{ publishedVersion.knowledge_config?.top_k ?? "未配置" }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ publishedVersion.created_at }}</el-descriptions-item><el-descriptions-item label="版本标识">{{ publishedVersion.id }}</el-descriptions-item></el-descriptions><StatePanel v-else-if="publishedState === 'empty'" state="empty" title="暂无当前生效版本" description="该智能体尚未发布可用版本。" /><template #footer><el-button @click="publishedVisible = false">关闭</el-button></template></el-dialog>
    <el-dialog v-model="chatVisible" :title="`调试：${selected?.name || ''}`" width="720px" @close="closeChat"><StatePanel v-if="chatContextState === 'loading'" state="loading" title="正在加载当前生效配置" /><StatePanel v-else-if="chatContextState === 'permission'" state="permission" title="无权加载调试配置" description="当前账号没有查看该智能体生效配置的权限。" /><StatePanel v-else-if="chatContextState === 'error'" state="error" title="调试配置加载失败" :description="chatContextError" action-label="重试" @action="selected && loadChatContext(selected.id)" /><div v-else-if="publishedVersion" class="chat-context"><span>系统提示词</span><div class="prompt">{{ publishedVersion.system_prompt }}</div></div><el-scrollbar v-if="chatContextState === 'success'" height="360px" class="messages"><div v-for="(message, index) in messages" :key="index" :class="['message', message.role]"><b>{{ message.role === 'user' ? '你' : '智能体' }}</b><div>{{ message.content }}</div></div><el-empty v-if="!messages.length" description="输入消息开始调试" /></el-scrollbar><el-alert v-if="chatError" :title="chatError" type="error" :closable="false" show-icon class="chat-alert" /><el-input v-if="chatContextState === 'success'" v-model="input" type="textarea" :rows="4" placeholder="输入消息..." :disabled="chatState === 'streaming'" @keyup.ctrl.enter="execute" /><div v-if="chatContextState === 'success'" class="chat-status"><el-tag :type="chatStatusType">{{ chatStatusLabel }}</el-tag><span v-if="requestId">请求标识：{{ shortId(requestId) }}</span><span v-if="traceId">链路追踪标识：{{ shortId(traceId) }}</span><span v-if="sessionId">会话标识：{{ shortId(sessionId) }}</span><span v-if="executionId">执行标识：{{ shortId(executionId) }}</span></div><template #footer><el-button v-if="chatState === 'streaming'" type="warning" @click="cancelChat">停止生成</el-button><el-button @click="closeChat">关闭</el-button><el-button v-if="chatContextState === 'success'" type="primary" :loading="chatState === 'streaming'" :disabled="!input.trim() || chatState === 'streaming'" @click="execute">发送</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import StatePanel from "@/components/ui/StatePanel.vue";
import { archiveAgent, createAgent, createVersion as createAgentVersion, getPublishedVersion, listAgents, listVersions, publishAgent, type Agent, type AgentVersion } from "@/api/agents";
import { streamChat, type ChatEvent } from "@/api/chat";
type ViewState = "loading" | "empty" | "error" | "permission" | "success"; type ChatState = "idle" | "streaming" | "completed" | "failed" | "cancelled";
const agents = ref<Agent[]>([]), versions = ref<AgentVersion[]>([]); const loadingAgents = ref(true), saving = ref(false), savingVersion = ref(false), chatLoading = ref(false), chatContextLoading = ref(false), publishingVersionId = ref("");
const dialogVisible = ref(false), versionsVisible = ref(false), publishedVisible = ref(false), chatVisible = ref(false); const error = ref(""), successMessage = ref(""), agentPermissionDenied = ref(false), chatError = ref(""), chatContextError = ref(""), selected = ref<Agent | null>(null), publishedVersion = ref<AgentVersion | null>(null), input = ref(""), executionId = ref("");
const requestId = ref(""), traceId = ref(""), sessionId = ref<string | undefined>(), messages = ref<Array<{ role: string; content: string }>>([]); const chatState = ref<ChatState>("idle");
const agentState = computed<ViewState>(() => loadingAgents.value ? "loading" : agentPermissionDenied.value ? "permission" : error.value && !agents.value.length ? "error" : !agents.value.length ? "empty" : "success"); const versionState = ref<ViewState>("empty"), publishedState = ref<ViewState>("empty"), chatContextState = ref<ViewState>("empty"); let activeController: AbortController | null = null; let activeRun = 0;
const form = ref({ name: "企业智能助手", description: "", system_prompt: "你是一个企业级 AI 助手，请准确、简洁地回答用户问题。", model_id: "mock-model" }); const versionForm = ref({ system_prompt: "", model_id: "mock-model" }); const chatStatusLabel = computed(() => ({ idle: "就绪", streaming: "生成中", completed: "已完成", failed: "失败", cancelled: "已取消" }[chatState.value])); const chatStatusType = computed(() => ({ idle: "info", streaming: "primary", completed: "success", failed: "danger", cancelled: "warning" }[chatState.value] as "info" | "primary" | "success" | "danger" | "warning"));
function statusLabel(status: string) { return ({ draft: "草稿", published: "已发布", archived: "已归档", active: "已启用", inactive: "已停用" } as Record<string, string>)[status] || `未知状态（${status}）`; } function statusType(status: string) { return status === "published" || status === "active" ? "success" : status === "archived" ? "info" : status === "inactive" ? "warning" : "info"; } function shortId(value?: string | null) { if (!value) return "-"; return value.length <= 18 ? value : `${value.slice(0, 8)}...${value.slice(-6)}`; }
function isPermissionError(value: unknown) { if (typeof value === "string") return /403|forbidden/i.test(value); if (!value || typeof value !== "object") return false; const candidate = value as { response?: { status?: unknown; data?: { status?: unknown; code?: unknown } }; status?: unknown; code?: unknown; message?: unknown }; const responseStatus = candidate.response?.status ?? candidate.response?.data?.status ?? candidate.status; const responseCode = candidate.response?.data?.code; return responseStatus === 403 || responseStatus === "403" || candidate.code === "FORBIDDEN" || candidate.code === "403" || responseCode === "FORBIDDEN" || responseCode === "403" || (typeof candidate.message === "string" && /403|forbidden/i.test(candidate.message)); } function userError(value: unknown, fallback: string) { return isPermissionError(value) ? "无权执行该操作，请联系管理员。" : fallback; }
async function load(){loadingAgents.value=true;error.value="";agentPermissionDenied.value=false;try{agents.value=await listAgents()}catch(e){agentPermissionDenied.value=isPermissionError(e);error.value=userError(e,"智能体列表加载失败，请刷新后重试。")}finally{loadingAgents.value=false}}
async function create(){saving.value=true;try{await createAgent(form.value);dialogVisible.value=false;await load();successMessage.value="智能体创建成功";ElMessage.success("智能体创建成功，请发布后再进行对话调试")}catch(e){ElMessage.error(userError(e,"智能体创建失败，请检查填写内容后重试"))}finally{saving.value=false}}
async function openVersions(agent:Agent){selected.value=agent;versionsVisible.value=true;versionState.value="loading";versionForm.value={system_prompt:"",model_id:agent.model_id||"mock-model"};try{versions.value=await listVersions(agent.id);versionState.value="success"}catch(e){versionState.value=isPermissionError(e)?"permission":"error"}}
async function openPublishedVersion(agent:Agent){selected.value=agent;publishedVersion.value=null;publishedVisible.value=true;publishedState.value="loading";try{publishedVersion.value=await getPublishedVersion(agent.id);publishedState.value=publishedVersion.value?"success":"empty"}catch(e){publishedState.value=isPermissionError(e)?"permission":"error"}}
async function loadChatContext(agentId:string){chatContextLoading.value=true;chatContextError.value="";chatContextState.value="loading";try{publishedVersion.value=await getPublishedVersion(agentId);chatContextState.value=publishedVersion.value?"success":"empty"}catch(e){publishedVersion.value=null;const permissionDenied=isPermissionError(e);chatContextState.value=permissionDenied?"permission":"error";chatContextError.value=permissionDenied?"无权加载调试配置":userError(e,"当前生效配置加载失败，请稍后重试")}finally{chatContextLoading.value=false}}
async function openChat(agent:Agent){selected.value=agent;chatVisible.value=true;chatContextState.value="loading";messages.value=[];input.value="";chatError.value="";requestId.value="";traceId.value="";sessionId.value=undefined;executionId.value="";chatState.value="idle";await loadChatContext(agent.id)}
async function publishLatest(agent:Agent){await publishVersion((await listVersions(agent.id))[0])} async function publishVersion(version:AgentVersion){publishingVersionId.value=version.id;try{await publishAgent(version.agent_id,version.id);await load();if(selected.value)await openVersions(selected.value);ElMessage.success("版本发布成功")}catch(e){ElMessage.error(userError(e,"版本发布失败，请稍后重试"))}finally{publishingVersionId.value=""}}
async function createVersion(){if(!selected.value||selected.value.status==="archived")return;savingVersion.value=true;try{await createAgentVersion(selected.value.id,versionForm.value);await openVersions(selected.value);ElMessage.success("版本创建成功")}catch(e){ElMessage.error(userError(e,"版本创建失败，请检查配置后重试"))}finally{savingVersion.value=false}}
async function archive(agent:Agent){try{await ElMessageBox.confirm("归档后将停止新版本发布与对话调试，是否继续？","确认归档",{type:"warning"});await archiveAgent(agent.id);await load();ElMessage.success("智能体已归档")}catch(e){if(e!=="cancel"&&e!=="close")ElMessage.error(userError(e,"归档失败，请稍后重试"))}}
function closeChat(){activeController?.abort();activeController=null;chatVisible.value=false;chatContextState.value="empty";chatState.value="idle";messages.value=[];input.value=""}
async function execute(){if(!selected.value||chatContextState.value!=="success"||!input.value.trim()||chatState.value==="streaming")return;const text=input.value.trim();input.value="";chatState.value="streaming";chatError.value="";const currentRun=++activeRun;activeController=new AbortController();messages.value.push({role:"user",content:text});messages.value.push({role:"assistant",content:""});try{await streamChat({agent_id:selected.value.id,input:text,session_id:sessionId.value},(event:ChatEvent)=>{if(currentRun!==activeRun)return;if(event.type==="delta"){messages.value[messages.value.length-1].content+=event.content}else if(event.type==="start"){requestId.value=event.request_id;traceId.value=event.trace_id;sessionId.value=event.session_id}else if(event.type==="done"){executionId.value=event.execution_id}else if(event.type==="error"){chatError.value=event.message||"对话执行失败，请稍后重试"}},activeController.signal);if(currentRun===activeRun)chatState.value=chatError.value?"failed":"completed"}catch(e){if((e as Error)?.name!=="AbortError")chatError.value=userError(e,"对话执行失败，请稍后重试");if(currentRun===activeRun)chatState.value=(e as Error)?.name==="AbortError"?"cancelled":"failed"}finally{if(currentRun===activeRun)activeController=null}}
function cancelChat(){activeController?.abort();activeController=null;chatState.value="cancelled"}
onMounted(load);onBeforeUnmount(()=>activeController?.abort());
</script>
<style scoped>
.page{padding:24px}.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.header h1{margin:0 0 6px}.header p{margin:0;color:#64748b}.table{width:100%}.published-badge{margin-left:8px;font-size:12px;color:#16a34a}.prompt{white-space:pre-wrap;background:#f8fafc;padding:12px;border-radius:6px}.chat-context{margin-bottom:16px}.chat-context>span{display:block;margin-bottom:6px;font-weight:600}.messages{margin-bottom:12px}.message{padding:8px 0}.message b{display:block;margin-bottom:4px}.message.user{text-align:right}.chat-status{display:flex;gap:12px;align-items:center;margin:8px 0;font-size:12px;color:#64748b}.chat-alert{margin:8px 0}@media(max-width:768px){.page{padding:16px}.header{gap:12px;flex-direction:column}.table{overflow:auto}}
</style>
