<template>
  <div class="page">
    <div class="header"><div><h1>智能体工作台</h1><p>管理智能体、版本、发布生命周期，并使用真实运行过程调试。</p></div><el-button type="primary" @click="dialogVisible = true">创建智能体</el-button></div>
    <el-alert v-if="error" :title="error" type="error" show-icon closable @close="error = ''" />
    <el-table v-loading="loadingAgents" :data="agents" border class="table">
      <el-table-column prop="name" label="名称" min-width="180" />
      <el-table-column label="当前生效版本" width="180"><template #default="{ row }">{{ row.version || "未发布" }}<span v-if="row.version" class="published-badge">已发布</span></template></el-table-column>
      <el-table-column prop="model_id" label="模型" width="160" /><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column>
      <el-table-column label="操作" min-width="430"><template #default="{ row }"><el-button link type="primary" @click="openVersions(row as Agent)">版本</el-button><el-button link type="primary" @click="openChat(row as Agent)" :disabled="row.status !== 'published'">对话调试</el-button><el-button v-if="row.status !== 'published' && row.status !== 'archived'" link type="success" @click="publishLatest(row as Agent)">发布最新版本</el-button><el-button v-if="row.status === 'published'" link type="danger" @click="archive(row as Agent)">归档</el-button></template></el-table-column>
    </el-table>
    <el-empty v-if="!loadingAgents && !agents.length" description="暂无智能体，请先创建一个。" />
    <el-dialog v-model="dialogVisible" title="创建智能体" width="560px"><el-form label-width="110px"><el-form-item label="名称" required><el-input v-model="form.name" /></el-form-item><el-form-item label="描述"><el-input v-model="form.description" /></el-form-item><el-form-item label="系统提示词" required><el-input v-model="form.system_prompt" type="textarea" :rows="5" /></el-form-item><el-form-item label="模型" required><el-input v-model="form.model_id" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog>
    <el-dialog v-model="versionsVisible" :title="`智能体版本 · ${selected?.name || ''}`" width="760px"><el-alert v-if="selected?.status === 'archived'" title="智能体已归档，不能创建或发布新版本。" type="warning" show-icon /><el-table :data="versions" border><el-table-column prop="version" label="版本" width="130"><template #default="{ row }">{{ row.version }}<span v-if="row.is_published" class="published-badge">已发布</span></template></el-table-column><el-table-column prop="model_id" label="模型" width="160" /><el-table-column prop="created_at" label="创建时间" /><el-table-column label="操作" width="110"><template #default="{ row }"><el-button v-if="!row.is_published && selected?.status !== 'archived'" link type="success" :loading="publishingVersionId === row.id" @click="publishVersion(row as AgentVersion)">发布</el-button></template></el-table-column></el-table><el-divider /><el-form label-width="100px"><el-form-item label="系统提示词"><el-input v-model="versionForm.system_prompt" type="textarea" :rows="3" :disabled="selected?.status === 'archived'" /></el-form-item><el-form-item label="模型"><el-input v-model="versionForm.model_id" :disabled="selected?.status === 'archived'" /></el-form-item></el-form><template #footer><el-button @click="versionsVisible = false">关闭</el-button><el-button type="primary" :loading="savingVersion" :disabled="selected?.status === 'archived'" @click="createVersion">创建版本</el-button></template></el-dialog>
    <el-dialog v-model="chatVisible" :title="`调试：${selected?.name || ''}`" width="720px" @close="closeChat">
      <el-scrollbar height="360px" class="messages"><div v-for="(message, index) in messages" :key="index" :class="['message', message.role]"><b>{{ message.role === 'user' ? '你' : '智能体' }}</b><div>{{ message.content }}</div></div><el-empty v-if="!messages.length" description="输入消息开始调试" /></el-scrollbar>
      <el-alert v-if="chatError" :title="chatError" type="error" :closable="false" show-icon class="chat-alert" />
      <el-input v-model="input" type="textarea" :rows="4" placeholder="输入消息..." :disabled="chatState === 'streaming'" @keyup.ctrl.enter="execute" />
      <div class="chat-status"><el-tag :type="chatStatusType">{{ chatStatusLabel }}</el-tag><span v-if="requestId">请求标识：{{ shortId(requestId) }}</span><span v-if="traceId">链路追踪标识：{{ shortId(traceId) }}</span><span v-if="sessionId">会话标识：{{ shortId(sessionId) }}</span><span v-if="executionId">执行标识：{{ shortId(executionId) }}</span></div>
      <template #footer><el-button v-if="chatState === 'streaming'" type="warning" @click="cancelChat">停止生成</el-button><el-button @click="closeChat">关闭</el-button><el-button type="primary" :loading="chatState === 'streaming'" :disabled="!input.trim() || chatState === 'streaming'" @click="execute">发送</el-button></template>
    </el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { archiveAgent, createAgent, createVersion as createAgentVersion, listAgents, listVersions, publishAgent, type Agent, type AgentVersion } from "@/api/agents";
import { streamChat, type ChatEvent } from "@/api/chat";

type ChatState = "idle" | "streaming" | "completed" | "failed" | "cancelled";
const agents = ref<Agent[]>([]), versions = ref<AgentVersion[]>([]);
const loadingAgents = ref(false), saving = ref(false), savingVersion = ref(false), chatLoading = ref(false), publishingVersionId = ref("");
const dialogVisible = ref(false), versionsVisible = ref(false), chatVisible = ref(false);
const error = ref(""), chatError = ref(""), selected = ref<Agent | null>(null), input = ref(""), executionId = ref("");
const requestId = ref(""), traceId = ref(""), sessionId = ref<string | undefined>(), messages = ref<Array<{ role: string; content: string }>>([]);
const chatState = ref<ChatState>("idle");
let activeController: AbortController | null = null;
let activeRun = 0;
const form = ref({ name: "企业智能助手", description: "", system_prompt: "你是一个企业级 AI 助手，请准确、简洁地回答用户问题。", model_id: "mock-model" });
const versionForm = ref({ system_prompt: "", model_id: "mock-model" });
const chatStatusLabel = computed(() => ({ idle: "就绪", streaming: "生成中", completed: "已完成", failed: "失败", cancelled: "已取消" }[chatState.value]));
const chatStatusType = computed(() => ({ idle: "info", streaming: "primary", completed: "success", failed: "danger", cancelled: "warning" }[chatState.value] as "info" | "primary" | "success" | "danger" | "warning"));
function statusLabel(status: string) { return ({ draft: "草稿", published: "已发布", archived: "已归档", active: "已启用", inactive: "已停用" } as Record<string, string>)[status] || `未知状态（${status}）`; }
function statusType(status: string) { return status === "published" || status === "active" ? "success" : status === "archived" ? "info" : status === "inactive" ? "warning" : "info"; }
function shortId(value?: string | null) { if (!value) return "-"; return value.length <= 18 ? value : `${value.slice(0, 8)}...${value.slice(-6)}`; }
function userError(_value: unknown, fallback: string) { return fallback; }
async function load(){loadingAgents.value=true;error.value="";try{agents.value=await listAgents()}catch(e){error.value=userError(e,"智能体列表加载失败，请刷新后重试。")}finally{loadingAgents.value=false}}
async function create(){saving.value=true;try{await createAgent(form.value);dialogVisible.value=false;await load();ElMessage.success("智能体创建成功，请发布后再进行对话调试")}catch(e){ElMessage.error(userError(e,"智能体创建失败，请检查填写内容后重试"))}finally{saving.value=false}}
async function openVersions(agent:Agent){selected.value=agent;versionsVisible.value=true;versionForm.value={system_prompt:"",model_id:agent.model_id||"mock-model"};try{versions.value=await listVersions(agent.id)}catch(e){ElMessage.error(userError(e,"版本加载失败，请刷新后重试"))}}
async function createVersion(){if(!selected.value||!versionForm.value.system_prompt.trim()||selected.value.status==="archived")return;savingVersion.value=true;try{await createAgentVersion(selected.value.id,versionForm.value);versions.value=await listVersions(selected.value.id);await load();selected.value=agents.value.find(a=>a.id===selected.value?.id)||selected.value;ElMessage.success("版本创建成功，请发布目标版本后生效")}catch(e){ElMessage.error(userError(e,"版本创建失败，请检查填写内容后重试"))}finally{savingVersion.value=false}}
async function publishVersion(version:AgentVersion){if(!selected.value||selected.value.status==="archived")return;publishingVersionId.value=version.id;try{await publishAgent(selected.value.id,version.id);versions.value=await listVersions(selected.value.id);await load();selected.value=agents.value.find(a=>a.id===selected.value?.id)||selected.value;ElMessage.success(`已发布 ${version.version}`)}catch(e){ElMessage.error(userError(e,"智能体发布失败，请稍后重试"))}finally{publishingVersionId.value=""}}
async function publishLatest(agent:Agent){try{const items=await listVersions(agent.id);if(!items.length)throw new Error("没有可发布版本");await publishAgent(agent.id,items[0].id);await load();ElMessage.success(`已发布 ${items[0].version}`)}catch(e){ElMessage.error(userError(e,"智能体发布失败，请稍后重试"))}}
async function archive(agent:Agent){try{await ElMessageBox.confirm(`确定归档智能体「${agent.name}」吗？归档后不能创建新版本或继续进行对话调试。`,`归档确认`,{type:"warning"});await archiveAgent(agent.id);await load();ElMessage.success("智能体已归档")}catch(e){if(e!=="cancel"&&e!=="close")ElMessage.error(userError(e,"智能体归档失败，请稍后重试"))}}
function openChat(agent:Agent){cancelChat();selected.value=agent;input.value="";sessionId.value=undefined;executionId.value="";requestId.value="";traceId.value="";chatError.value="";messages.value=[];chatState.value="idle";chatVisible.value=true}
function cancelChat(){activeRun++;activeController?.abort();activeController=null;if(chatState.value==="streaming"){chatState.value="cancelled";chatLoading.value=false}}
function closeChat(){cancelChat();chatVisible.value=false}
function handleEvent(event: ChatEvent, run: number){if(run!==activeRun)return;if(event.type==="start"){requestId.value=event.request_id;traceId.value=event.trace_id;sessionId.value=event.session_id;return}if(event.type==="delta"){messages.value[messages.value.length-1].content+=event.content;return}if(event.type==="done"){executionId.value=event.execution_id;chatState.value="completed";return}if(event.type==="error"){chatError.value=userError(new Error(event.message),"对话执行失败，请稍后重试");chatState.value="failed";messages.value[messages.value.length-1].content=chatError.value}}
async function execute(){if(!selected.value||!input.value.trim()||chatState.value==="streaming")return;const text=input.value.trim();input.value="";chatError.value="";messages.value.push({role:"user",content:text},{role:"assistant",content:""});chatState.value="streaming";chatLoading.value=true;const controller=new AbortController();activeController=controller;const run=++activeRun;try{await streamChat({agent_id:selected.value.id,input:text,session_id:sessionId.value,memory_limit:20},event=>handleEvent(event,run),controller.signal);if(run===activeRun&&chatState.value==="streaming")chatState.value="completed"}catch(e){if(run!==activeRun)return;if(controller.signal.aborted){chatState.value="cancelled"}else{chatState.value="failed";chatError.value=userError(e,"对话执行失败，请稍后重试");messages.value[messages.value.length-1].content=chatError.value;ElMessage.error("对话执行失败，请稍后重试")}}finally{if(run===activeRun){chatLoading.value=false;if(activeController===controller)activeController=null}}}
onMounted(load);onBeforeUnmount(cancelChat);
</script>
<style scoped>.page{padding:32px}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.header p{color:#667085}.table{margin-top:18px}.published-badge{margin-left:6px;font-size:11px;color:#16a34a}.messages{margin-bottom:16px;padding:8px;background:#f8fafc;border-radius:8px}.message{margin:10px 0;padding:10px 14px;border-radius:8px;white-space:pre-wrap}.message.user{margin-left:18%;background:#e8f3ff}.message.assistant{margin-right:18%;background:#fff}.chat-alert{margin-bottom:10px}.chat-status{display:flex;gap:12px;align-items:center;margin-top:10px;color:#667085;font-size:12px;flex-wrap:wrap}</style>