<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { ElMessage, ElMessageBox } from "element-plus";
import { workflowApi, type ScheduledTriggerConfig, type SchedulerStatus, type WebhookTriggerConfig, type Workflow, type WorkflowExecution, type WorkflowTrigger, type WorkflowTriggerType } from "@/api/workflows";

const router = useRouter();
const workflows = ref<Workflow[]>([]);
const triggers = ref<WorkflowTrigger[]>([]);
const selectedWorkflowId = ref("");
const loading = ref(false);
const actionLoading = ref(false);
const execution = ref<WorkflowExecution>();
const schedulerStatus = ref<SchedulerStatus>();
const schedulerLoading = ref(false);
const selectedSchedulerTriggerId = ref("");
const webhookSecret = ref("");
const editingTriggerId = ref("");
const form = ref({ name: "", triggerType: "manual" as WorkflowTriggerType, configText: "{}" });
const inputText = ref("{}");

const defaultSchedule = (): ScheduledTriggerConfig => ({ timezone: "UTC", interval_seconds: 60 });
const defaultWebhook = (): Record<string, unknown> => ({ auth_mode: "secret", event_id_field: "event_id" });
function isScheduled(trigger: WorkflowTrigger) { return trigger.trigger_type === "scheduled"; }
function isWebhook(trigger: WorkflowTrigger) { return trigger.trigger_type === "webhook"; }
function scheduleConfig(trigger: WorkflowTrigger): ScheduledTriggerConfig { const config = trigger.config as Partial<ScheduledTriggerConfig>; return { timezone: typeof config.timezone === "string" ? config.timezone : "UTC", interval_seconds: typeof config.interval_seconds === "number" ? config.interval_seconds : 60, misfire_policy: config.misfire_policy, catch_up_limit: config.catch_up_limit }; }
function webhookConfig(trigger: WorkflowTrigger): WebhookTriggerConfig { const config = trigger.config as Partial<WebhookTriggerConfig>; return { auth_mode: "secret", event_id_field: typeof config.event_id_field === "string" ? config.event_id_field : "event_id", secret_configured: config.secret_configured === true }; }
function validateSchedule(config: Record<string, unknown>) { if (typeof config.timezone !== "string" || !config.timezone.trim()) throw new Error("Schedule timezone 必须是非空字符串"); if (!Number.isInteger(config.interval_seconds) || Number(config.interval_seconds) < 1) throw new Error("Schedule interval_seconds 必须是大于 0 的整数"); }
function validateWebhook(config: Record<string, unknown>, requireSecret = true) { if (requireSecret && (webhookSecret.value.length < 16 || webhookSecret.value.length > 256)) throw new Error("Webhook secret 长度必须为 16-256 个字符"); if (typeof config.event_id_field !== "string" || !config.event_id_field.trim()) throw new Error("Webhook event_id_field 必须是非空字符串"); }
function webhookEndpoint(trigger: WorkflowTrigger) { return `/api/v1/webhooks/${trigger.id}`; }
function generateSecret() { webhookSecret.value = `${crypto.randomUUID()}${crypto.randomUUID().replaceAll("-", "")}`.slice(0, 64); }
function workflowIsPublished() { return workflows.value.find((item) => item.id === selectedWorkflowId.value)?.status === "published"; }
function openRuntime(executionId: string, source: "scheduler" | "webhook" | "workflow-trigger") { return router.push({ path: "/runtime", query: { execution_id: executionId, workflow_id: selectedWorkflowId.value, source } }); }
function openWorkflowRuntime(source: "scheduler" | "webhook") { return router.push({ path: "/runtime", query: { workflow_id: selectedWorkflowId.value, source } }); }
async function loadWorkflows() { loading.value = true; try { workflows.value = (await workflowApi.list()).data; if (!selectedWorkflowId.value && workflows.value.length) selectedWorkflowId.value = workflows.value[0].id; await loadTriggers(); } catch { ElMessage.error("Workflow 查询失败"); } finally { loading.value = false; } }
async function loadTriggers() { if (!selectedWorkflowId.value) { triggers.value = []; schedulerStatus.value = undefined; selectedSchedulerTriggerId.value = ""; return; } try { triggers.value = (await workflowApi.triggers(selectedWorkflowId.value)).data; const selected = triggers.value.find((item) => item.id === selectedSchedulerTriggerId.value); if (!selected || !isScheduled(selected)) { schedulerStatus.value = undefined; selectedSchedulerTriggerId.value = ""; } } catch { ElMessage.error("Trigger 查询失败"); } }
async function loadSchedule(trigger: WorkflowTrigger) { if (!selectedWorkflowId.value || !isScheduled(trigger)) return; selectedSchedulerTriggerId.value = trigger.id; schedulerLoading.value = true; schedulerStatus.value = undefined; const maxAttempts = 4; try { for (let attempt = 1; attempt <= maxAttempts; attempt += 1) { try { schedulerStatus.value = (await workflowApi.schedule(selectedWorkflowId.value, trigger.id)).data; return; } catch (error) { const message = error instanceof Error ? error.message : ""; const retryable = message.includes("Scheduler 状态尚未初始化") || message.includes("Request failed with status code 404"); if (!retryable || attempt === maxAttempts) throw error; await new Promise((resolve) => window.setTimeout(resolve, 500)); } } } catch { schedulerStatus.value = undefined; ElMessage.error("Scheduler 状态查询失败"); } finally { schedulerLoading.value = false; } }
function resetForm() { editingTriggerId.value = ""; form.value = { name: "", triggerType: "manual", configText: "{}" }; webhookSecret.value = ""; }
function selectTriggerType(type: WorkflowTriggerType) { form.value.triggerType = type; webhookSecret.value = ""; if (type === "scheduled") form.value.configText = JSON.stringify(defaultSchedule(), null, 2); else if (type === "webhook") form.value.configText = JSON.stringify(defaultWebhook(), null, 2); else form.value.configText = "{}"; }
function editTrigger(trigger: WorkflowTrigger) { editingTriggerId.value = trigger.id; form.value = { name: trigger.name, triggerType: trigger.trigger_type, configText: JSON.stringify(trigger.config, null, 2) }; webhookSecret.value = ""; window.scrollTo({ top: 0, behavior: "smooth" }); }
async function saveTrigger() { if (!selectedWorkflowId.value) return ElMessage.warning("请选择 Workflow"); if (!form.value.name.trim()) return ElMessage.warning("请输入 Trigger 名称"); try { const config = JSON.parse(form.value.configText) as Record<string, unknown>; if (form.value.triggerType === "scheduled") validateSchedule(config); if (form.value.triggerType === "webhook") { const current = editingTriggerId.value ? triggers.value.find((item) => item.id === editingTriggerId.value) : undefined; validateWebhook(config, !current?.config || !(current.config as WebhookTriggerConfig).secret_configured || !!webhookSecret.value); if (webhookSecret.value) config.secret = webhookSecret.value; } actionLoading.value = true; if (editingTriggerId.value) { await workflowApi.updateTrigger(selectedWorkflowId.value, editingTriggerId.value, { name: form.value.name, config }); ElMessage.success("Trigger 已更新"); } else { await workflowApi.createTrigger(selectedWorkflowId.value, { name: form.value.name, trigger_type: form.value.triggerType, config }); ElMessage.success("Trigger 创建成功"); } resetForm(); await loadTriggers(); } catch (error) { ElMessage.error(error instanceof SyntaxError ? "Trigger Config 不是合法 JSON" : error instanceof Error ? error.message : "Trigger 保存失败"); } finally { actionLoading.value = false; } }
async function toggleTrigger(trigger: WorkflowTrigger) { if (!selectedWorkflowId.value) return; const nextStatus = trigger.status === "enabled" ? "disabled" : "enabled"; if (nextStatus === "enabled" && workflowIsPublished() === false) return ElMessage.warning("Workflow 尚未发布，不能启用 Trigger"); try { await ElMessageBox.confirm(`确认${nextStatus === "enabled" ? "启用" : "禁用"} Trigger「${trigger.name}」？`, `${nextStatus === "enabled" ? "启用" : "禁用"} Trigger`, { type: nextStatus === "enabled" ? "warning" : "info" }); actionLoading.value = true; await workflowApi.updateTrigger(selectedWorkflowId.value, trigger.id, { status: nextStatus }); await loadTriggers(); if (trigger.id === selectedSchedulerTriggerId.value && nextStatus === "disabled") schedulerStatus.value = undefined; ElMessage.success(`Trigger 已${nextStatus === "enabled" ? "启用" : "禁用"}`); } catch (error) { if (error !== "cancel") ElMessage.error("Trigger 状态更新失败"); } finally { actionLoading.value = false; } }
async function deleteTrigger(trigger: WorkflowTrigger) { if (!selectedWorkflowId.value) return; try { await ElMessageBox.confirm(`删除 Trigger「${trigger.name}」将同时解除其调度/入口配置，确认继续？`, "危险操作确认", { type: "warning", confirmButtonText: "确认删除", cancelButtonText: "取消" }); actionLoading.value = true; await workflowApi.deleteTrigger(selectedWorkflowId.value, trigger.id); if (trigger.id === selectedSchedulerTriggerId.value) { selectedSchedulerTriggerId.value = ""; schedulerStatus.value = undefined; } if (editingTriggerId.value === trigger.id) resetForm(); await loadTriggers(); ElMessage.success("Trigger 已删除"); } catch (error) { if (error !== "cancel") ElMessage.error("Trigger 删除失败"); } finally { actionLoading.value = false; } }
async function invokeTrigger(trigger: WorkflowTrigger) { if (!selectedWorkflowId.value) return; try { const inputData = JSON.parse(inputText.value) as Record<string, unknown>; const idempotencyKey = `frontend-trigger-${crypto.randomUUID()}`; actionLoading.value = true; execution.value = (await workflowApi.invokeTrigger(selectedWorkflowId.value, trigger.id, inputData, idempotencyKey)).data; ElMessage.success("Trigger 已调用并进入 Workflow Execution"); await openRuntime(execution.value.id, "workflow-trigger"); } catch (error) { ElMessage.error(error instanceof SyntaxError ? "Trigger Input 不是合法 JSON" : "Trigger 调用失败"); } finally { actionLoading.value = false; } }
async function openLastSchedulerExecution() { const executionId = schedulerStatus.value?.last_execution_id; if (!executionId) return ElMessage.info("暂无最近 Execution"); await openRuntime(executionId, "scheduler"); }
async function openWebhookRuntime(trigger: WorkflowTrigger) { if (!isWebhook(trigger)) return; await router.push({ path: "/runtime", query: { workflow_id: selectedWorkflowId.value, trigger_id: trigger.id, source: "webhook" } }); }
onMounted(loadWorkflows);
</script>

<template>
  <div class="trigger-page">
    <el-card v-loading="loading">
      <template #header><div class="header"><span>Workflow Trigger Governance</span><el-button size="small" @click="loadWorkflows">刷新</el-button></div></template>
      <el-alert title="Trigger 只能作用于当前 Tenant 可访问的 Workflow；Tenant 不由前端提交。启用 Trigger 前必须先发布 Workflow。Webhook Secret 只以哈希形式持久化。" type="info" :closable="false" />
      <el-form label-position="top" class="selector"><el-form-item label="Workflow"><el-select v-model="selectedWorkflowId" placeholder="选择 Workflow" @change="loadTriggers"><el-option v-for="workflow in workflows" :key="workflow.id" :label="`${workflow.name} (${workflow.status})`" :value="workflow.id" /></el-select></el-form-item></el-form>
      <el-divider />
      <el-form label-position="top" inline @submit.prevent="saveTrigger"><el-form-item label="Trigger 名称"><el-input v-model="form.name" placeholder="例如：订单事件入口" /></el-form-item><el-form-item label="类型"><el-select data-testid="workflow-trigger-type-select" :model-value="form.triggerType" :disabled="!!editingTriggerId" @update:model-value="selectTriggerType"><el-option label="manual" value="manual" /><el-option label="scheduled" value="scheduled" /><el-option label="webhook" value="webhook" /></el-select></el-form-item><el-form-item v-if="form.triggerType === 'webhook'" label="Webhook Secret"><div class="secret-editor"><el-input v-model="webhookSecret" type="password" show-password placeholder="编辑时留空表示保持现有 Secret" /><el-button size="small" @click="generateSecret">生成 Secret</el-button></div></el-form-item><el-form-item label="Config JSON"><el-input v-model="form.configText" type="textarea" :rows="3" style="width: 320px" /></el-form-item><el-form-item label=" "><el-button type="primary" :loading="actionLoading" native-type="submit">{{ editingTriggerId ? "保存修改" : "创建 Trigger" }}</el-button><el-button v-if="editingTriggerId" @click="resetForm">取消编辑</el-button></el-form-item></el-form>
      <el-table :data="triggers" empty-text="暂无 Trigger"><el-table-column prop="name" label="名称" min-width="180" /><el-table-column prop="trigger_type" label="类型" width="110" /><el-table-column label="Schedule / Webhook" min-width="300"><template #default="scope"><span v-if="isScheduled(scope.row as WorkflowTrigger)">{{ scheduleConfig(scope.row as WorkflowTrigger).timezone }} / 每 {{ scheduleConfig(scope.row as WorkflowTrigger).interval_seconds }} 秒</span><span v-else-if="isWebhook(scope.row as WorkflowTrigger)">POST {{ webhookEndpoint(scope.row as WorkflowTrigger) }} / event_id: {{ webhookConfig(scope.row as WorkflowTrigger).event_id_field }}</span><span v-else>-</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="scope.row.status === 'enabled' ? 'success' : 'info'">{{ scope.row.status }}</el-tag></template></el-table-column><el-table-column label="Secret" width="120"><template #default="scope"><el-tag v-if="isWebhook(scope.row as WorkflowTrigger)" type="success">{{ webhookConfig(scope.row as WorkflowTrigger).secret_configured ? '已配置' : '未配置' }}</el-tag><span v-else>-</span></template></el-table-column><el-table-column prop="updated_at" label="更新时间" min-width="180" /><el-table-column label="操作" width="560"><template #default="scope"><el-button size="small" @click="editTrigger(scope.row as WorkflowTrigger)">编辑</el-button><el-button v-if="scope.row.trigger_type === 'scheduled'" size="small" :loading="schedulerLoading && selectedSchedulerTriggerId === scope.row.id" @click="loadSchedule(scope.row as WorkflowTrigger)">调度状态</el-button><el-button v-if="scope.row.trigger_type === 'scheduled' && selectedSchedulerTriggerId === scope.row.id && schedulerStatus?.last_execution_id" size="small" @click="openLastSchedulerExecution">最近 Execution</el-button><el-button v-if="scope.row.trigger_type === 'webhook'" size="small" @click="openWebhookRuntime(scope.row as WorkflowTrigger)">查看 Webhook 运行</el-button><el-button v-if="scope.row.trigger_type === 'manual'" size="small" :disabled="scope.row.status === 'disabled'" @click="invokeTrigger(scope.row as WorkflowTrigger)">Invoke</el-button><el-button size="small" :loading="actionLoading" @click="toggleTrigger(scope.row as WorkflowTrigger)">{{ scope.row.status === 'enabled' ? '禁用' : '启用' }}</el-button><el-button size="small" type="danger" :loading="actionLoading" @click="deleteTrigger(scope.row as WorkflowTrigger)">删除</el-button></template></el-table-column></el-table>
      <el-card v-if="selectedSchedulerTriggerId" v-loading="schedulerLoading" class="scheduler-card"><template #header><div class="header"><span>Scheduler 持久化状态</span><el-button size="small" :disabled="schedulerLoading" @click="loadSchedule(triggers.find((item) => item.id === selectedSchedulerTriggerId) as WorkflowTrigger)">刷新</el-button></div></template><template v-if="schedulerStatus"><el-descriptions :column="3" border><el-descriptions-item label="状态"><el-tag :type="schedulerStatus.status === 'enabled' ? 'success' : 'info'">{{ schedulerStatus.status }}</el-tag></el-descriptions-item><el-descriptions-item label="时区"><span data-testid="scheduler-timezone">{{ schedulerStatus.timezone }}</span></el-descriptions-item><el-descriptions-item label="Misfire"><span data-testid="scheduler-misfire-policy">{{ schedulerStatus.misfire_policy }}</span></el-descriptions-item><el-descriptions-item label="Catch-up Limit"><span data-testid="scheduler-catch-up-limit">{{ schedulerStatus.catch_up_limit }}</span></el-descriptions-item><el-descriptions-item label="下次运行">{{ schedulerStatus.next_run_at || '-' }}</el-descriptions-item><el-descriptions-item label="上次运行">{{ schedulerStatus.last_run_at || '-' }}</el-descriptions-item><el-descriptions-item label="Lease"><el-tag :type="schedulerStatus.lease_active ? 'warning' : 'info'">{{ schedulerStatus.lease_active ? '占用中' : '未占用' }}</el-tag></el-descriptions-item><el-descriptions-item label="Lease 到期">{{ schedulerStatus.lease_expires_at || '-' }}</el-descriptions-item><el-descriptions-item label="最近 Execution"><span data-testid="scheduler-last-execution">{{ schedulerStatus.last_execution_id || '-' }}</span><el-button v-if="schedulerStatus.last_execution_id" link type="primary" size="small" @click="openLastSchedulerExecution">查看运行</el-button></el-descriptions-item></el-descriptions></template><el-empty v-else description="Scheduler 持久化状态正在初始化，请稍候刷新。" /></el-card>
      <el-divider /><el-form label-position="top"><el-form-item label="Manual Invoke Input JSON"><el-input v-model="inputText" type="textarea" :rows="4" /></el-form-item></el-form>
      <el-descriptions v-if="execution" title="最近一次 Manual Trigger Execution" :column="2" border><el-descriptions-item label="Execution ID">{{ execution.id }}</el-descriptions-item><el-descriptions-item label="Status"><el-tag>{{ execution.status }}</el-tag></el-descriptions-item><el-descriptions-item label="Workflow Version">{{ execution.workflow_version_id }}</el-descriptions-item><el-descriptions-item v-if="execution.error_code" label="Error">{{ execution.error_code }}: {{ execution.error_message || '-' }}</el-descriptions-item></el-descriptions>
    </el-card>
  </div>
</template>
<style scoped>.trigger-page { padding: 24px; }.header { display: flex; justify-content: space-between; align-items: center; }.selector { margin-top: 16px; max-width: 520px; }.el-form--inline { align-items: end; }.secret-editor { display: flex; gap: 8px; align-items: center; }.scheduler-card { margin-top: 16px; }</style>
