<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import { createOrganization, listOrganizations, type Organization } from "@/api/organizations";
const organizations = ref<Organization[]>([]); const loading = ref(false); const error = ref(""); const dialogVisible = ref(false); const saving = ref(false); const name = ref("");
function userError(error: unknown, fallback: string) { if (error instanceof Error) { const message = error.message.trim(); if (message && !/^\s*(?:HTTP\s*)?[45]\d\d\b/i.test(message)) return message; } return fallback; }
async function load() { loading.value = true; error.value = ""; try { organizations.value = (await listOrganizations()).items; } catch (e) { console.error("组织列表加载失败", e); error.value = userError(e, "组织列表加载失败，请稍后重试"); } finally { loading.value = false; } }
async function create() { if (!name.value.trim()) return; saving.value = true; try { await createOrganization({ name: name.value.trim() }); name.value = ""; dialogVisible.value = false; await load(); ElMessage.success("组织创建成功"); } catch (e) { console.error("组织创建失败", e); ElMessage.error(userError(e, "组织创建失败，请稍后重试")); } finally { saving.value = false; } }
function statusLabel(status: Organization["status"]) { return status === "active" ? "已启用" : status === "inactive" ? "已停用" : `未知状态（${status}）`; }
onMounted(load);
</script>
<template><div class="page"><div class="header"><div><h1>组织</h1><p>管理企业组织及成员访问权限。</p></div><el-button type="primary" @click="dialogVisible = true">创建组织</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon /><el-table v-loading="loading" :data="organizations" border class="table"><el-table-column prop="name" label="名称" min-width="220" /><el-table-column prop="tenant_id" label="租户 ID" min-width="280" /><el-table-column label="状态" width="120"><template #default="{ row }"><el-tag :type="row.status === 'active' ? 'success' : 'warning'">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="130"><template #default="{ row }"><router-link :to="`/organizations/${row.id}`">管理成员</router-link></template></el-table-column></el-table><el-empty v-if="!loading && !organizations.length" description="暂无组织。" /><el-dialog v-model="dialogVisible" title="创建组织" width="480px"><el-form label-width="90px"><el-form-item label="名称" required><el-input v-model="name" maxlength="120" show-word-limit @keyup.enter="create" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!name.trim()" @click="create">创建</el-button></template></el-dialog></div></template>
<style scoped>.page{padding:32px}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.header p{color:#667085}.table{margin-top:18px}a{color:#409eff;text-decoration:none}</style>
