<template>
  <div class="operations-console">
    <div class="toolbar"><PageToolbar title="运维窗口" description="选择观察窗口并重新同步 Runtime 后端事实。"><template #actions><el-select v-model="windowHours" style="width:120px" @change="loadAll"><el-option label="最近 1 小时" :value="1" /><el-option label="最近 24 小时" :value="24" /><el-option label="最近 7 天" :value="168" /></el-select><el-button :icon="Refresh" :loading="loading" @click="loadAll">刷新</el-button></template></PageToolbar></div>
    <StatePanel v-if="loading && !globalPosture && !overview" state="loading" title="正在加载 Runtime 运维数据" description="正在同步全局态势、告警、Provider、Audit 和死信。" /><StatePanel v-else-if="error" state="error" title="Runtime 运维数据加载失败" description="无法同步核心运维数据；已有数据不会被当作最新事实。" action-label="重试" @action="loadAll" />
    <template v-else><el-tabs v-model="activeTab" class="operations-tabs">
      <el-tab-pane label="全局运行态势" name="global"><StatePanel v-if="globalState==='loading'" state="loading" title="正在加载全局运行态势" description="" /><StatePanel v-else-if="globalState==='error'" state="error" title="全局运行态势加载失败" description="请重试以获得最新后端事实。" action-label="重试" @action="loadGlobal" /><StatePanel v-else-if="!globalPosture" state="empty" title="暂无全局运行态势" description="当前窗口没有可展示的 Runtime 态势。" /><template v-else><div class="metric-grid"><MetricCard label="执行总量" :value="globalPosture.executions.total" :description="`${globalPosture.executions.active_count} 个执行中`" /><MetricCard label="工作流" :value="globalPosture.workflows.total" :description="`${globalPosture.workflows.status_counts.active || 0} 个活跃`" /><MetricCard label="调度积压" :value="globalPosture.scheduler.durable_frontier_backlog" :description="`${globalPosture.scheduler.enabled_scheduled_triggers} 个定时触发器已启用`" /><MetricCard label="Worker 租约" :value="globalPosture.worker.leased_frontiers" :description="`${globalPosture.worker.active_worker_owners} 个活跃 Worker`" /></div><div class="slo-grid"><SurfaceCard title="Worker 状态"><div v-for="item in [['运行中 Frontier',globalPosture.worker.running_frontiers],['待处理 Frontier',globalPosture.worker.pending_frontiers],['过期租约',globalPosture.worker.expired_leases]]" :key="item[0]" class="status-row"><span>{{item[0]}}</span><strong>{{item[1]}}</strong></div><small class="muted">{{globalPosture.worker.liveness_reason_code}}</small></SurfaceCard><SurfaceCard title="Scheduler 状态"><div v-for="item in [['已启用定时触发器',globalPosture.scheduler.enabled_scheduled_triggers],['持久化 Frontier 积压',globalPosture.scheduler.durable_frontier_backlog]]" :key="item[0]" class="status-row"><span>{{item[0]}}</span><strong>{{item[1]}}</strong></div><small class="muted">{{globalPosture.scheduler.liveness_reason_code}}</small></SurfaceCard><SurfaceCard title="执行状态"><div v-for="item in executionStatuses" :key="item.key" class="status-row"><span>{{item.label}}</span><strong>{{statusCount(globalPosture.executions.status_counts,item.key)}}</strong></div></SurfaceCard></div><SurfaceCard title="最近执行" :description="`${globalPosture.window_hours} 小时窗口；Execution ID 为后端 durable ID`"><el-table :data="globalPosture.executions.items" empty-text="当前窗口没有执行记录"><el-table-column prop="workflow_name" label="工作流" min-width="180" /><el-table-column prop="id" label="Execution ID" min-width="250" show-overflow-tooltip><template #default="{row}"><el-button link type="primary" @click="openExecution(row.id)">{{row.id}}</el-button></template></el-table-column><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="current_node_id" label="当前节点" min-width="150" show-overflow-tooltip /><el-table-column prop="worker_owner" label="Worker" min-width="150" show-overflow-tooltip /><el-table-column prop="created_at" label="创建时间" min-width="180" /></el-table></SurfaceCard></template></el-tab-pane>
      <el-tab-pane label="总览" name="overview"><StatePanel v-if="overviewState==='loading'" state="loading" title="正在加载运行总览" description="" /><StatePanel v-else-if="overviewState==='error'" state="error" title="运行总览加载失败" description="请重试以获得最新 SLO 与 Delivery 数据。" action-label="重试" @action="loadOverview" /><StatePanel v-else-if="!overview" state="empty" title="暂无运行总览" description="当前窗口没有可展示的数据。" /><template v-else><div class="metric-grid"><MetricCard label="事件总量" :value="overview.events.total" :description="`${statusCount(overview.events.status_counts,'delivered')} 已送达`" /><MetricCard label="Delivery 总量" :value="overview.deliveries.total" :description="`${statusCount(overview.deliveries.status_counts,'pending')} 待处理`" /><MetricCard label="死信" :value="overview.deliveries.dead_letter_count" :description="`${overview.deliveries.retry_count} 次重试`" /><MetricCard label="投递成功率" :value="`${overview.slo.delivery_success_percent.toFixed(2)}%`" :description="`目标 ${overview.slo.target_percent.toFixed(2)}%`" /></div><div class="slo-grid"><SurfaceCard title="SLO"><div class="status-row"><span>投递成功率</span><strong>{{overview.slo.delivery_success_percent.toFixed(4)}}%</strong></div><div class="status-row"><span>错误预算剩余</span><strong>{{overview.slo.error_budget_percent.toFixed(4)}}%</strong></div><div class="status-row"><span>P95 投递延迟</span><strong>{{overview.slo.p95_delivery_latency_ms==null?'-':`${overview.slo.p95_delivery_latency_ms} ms`}}</strong></div><el-progress :percentage="Math.min(100,overview.slo.delivery_success_percent)" :status="sloHealthy?'success':'exception'" :stroke-width="8" /></SurfaceCard><SurfaceCard title="事件状态"><div v-for="item in eventStatuses" :key="item.key" class="status-row"><span>{{item.label}}</span><strong>{{statusCount(overview.events.status_counts,item.key)}}</strong></div></SurfaceCard><SurfaceCard title="Delivery 状态"><div v-for="item in deliveryStatuses" :key="item.key" class="status-row"><span>{{item.label}}</span><strong>{{statusCount(overview.deliveries.status_counts,item.key)}}</strong></div></SurfaceCard></div></template></el-tab-pane>
      <el-tab-pane label="告警" name="alerts"><div class="tab-toolbar"><div><strong>Alert 生命周期</strong><span>查看 firing / recovery，并可显式触发当前租户规则评估。</span></div><el-button type="primary" :loading="actionLoading" @click="evaluateAlerts">立即评估</el-button></div><StatePanel v-if="alertsState==='loading'" state="loading" title="正在加载告警" description="" /><StatePanel v-else-if="alertsState==='error'" state="error" title="告警加载失败" description="告警数据已清空，避免展示 stale facts。" action-label="重试" @action="loadAlerts" /><StatePanel v-else-if="!alerts.length&&!alertRules.length" state="empty" title="暂无告警与规则" description="当前窗口没有告警实例或规则。" /><template v-else><el-table :data="alerts" empty-text="暂无告警实例"><el-table-column prop="name" label="告警" min-width="180" /><el-table-column prop="severity" label="级别" width="100" /><el-table-column prop="status" label="状态" width="120" /><el-table-column prop="fired_at" label="触发时间" min-width="180" /><el-table-column prop="recovered_at" label="恢复时间" min-width="180" /></el-table><el-divider>告警规则</el-divider><el-table :data="alertRules" empty-text="暂无告警规则"><el-table-column prop="name" label="名称" min-width="180" /><el-table-column prop="metric_name" label="指标" min-width="180" /><el-table-column prop="operator" label="条件" width="90" /><el-table-column prop="threshold" label="阈值" width="100" /><el-table-column prop="severity" label="级别" width="100" /><el-table-column label="启用" width="100"><template #default="{row}"><el-switch :model-value="row.enabled" :loading="row.id===togglingRuleId" @change="toggleRule(row as RuntimeAlertRule, $event === true)" /></template></el-table-column></el-table></template></el-tab-pane>
      <el-tab-pane label="Provider" name="providers"><div class="tab-toolbar"><div><strong>通知 Provider</strong><span>页面不会读取或展示 Secret。</span></div></div><StatePanel v-if="providersState==='loading'" state="loading" title="正在加载 Provider" description="" /><StatePanel v-else-if="providersState==='error'" state="error" title="Provider 加载失败" description="Provider 数据已清空，避免展示 stale facts。" action-label="重试" @action="loadProviders" /><StatePanel v-else-if="!providers.length" state="empty" title="暂无 Provider" description="当前租户没有可展示的 Provider。" /><el-table v-else :data="providers"><el-table-column prop="name" label="名称" min-width="180" /><el-table-column prop="provider_type" label="类型" width="140" /><el-table-column prop="status" label="健康状态" width="120" /><el-table-column prop="last_checked_at" label="最近探测" min-width="180" /><el-table-column label="操作" width="210"><template #default="{row}"><el-switch :model-value="row.enabled" :loading="row.id===togglingProviderId" @change="toggleProvider(row as RuntimeProvider, $event === true)" /><el-button link type="primary" :loading="row.id===probingProviderId" @click="probeProvider(row as RuntimeProvider)">健康探测</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="Metrics" name="metrics"><div class="tab-toolbar"><div><strong>Runtime 时间序列</strong><span>指标查询遵循后端 canonical metric / dimension Contract。</span></div><el-button :loading="metricLoading" @click="snapshotMetrics">采样快照</el-button></div><StatePanel v-if="metricsState==='loading'" state="loading" title="正在加载指标" description="" /><StatePanel v-else-if="metricsState==='error'" state="error" title="指标查询失败" description="请检查指标名称与维度条件后重试。" action-label="重试" @action="loadMetrics" /><template v-else><el-form inline @submit.prevent="loadMetrics"><el-input v-model="metricName" placeholder="指标名称，例如 runtime.notification.delivery" clearable style="width:280px" /><el-input-number v-model="metricWindow" :min="1" :max="10080" controls-position="right" /><el-input v-model="dimensionKey" placeholder="维度键（可选）" clearable style="width:150px" /><el-input v-model="dimensionValue" placeholder="维度值（可选）" clearable style="width:180px" /><el-button type="primary" :loading="metricLoading" @click="loadMetrics">查询</el-button></el-form><el-table :data="metricSeries" empty-text="暂无指标样本"><el-table-column prop="timestamp" label="时间" min-width="180" /><el-table-column prop="metric_name" label="指标" min-width="220" /><el-table-column prop="value" label="值" width="120" /><el-table-column prop="dimension_key" label="维度键" width="140" /><el-table-column prop="dimension_value" label="维度值" min-width="180" /></el-table></template></el-tab-pane>
      <el-tab-pane label="Audit" name="audit"><div class="tab-toolbar"><div><strong>Runtime 运维审计</strong><span>查询严格限制在当前租户。</span></div><el-button :loading="auditLoading" @click="loadAudit">刷新</el-button></div><el-form inline class="audit-filters" @submit.prevent="queryAudit"><el-input v-model="auditActor" placeholder="操作主体（可选）" clearable style="width:180px" /><el-input v-model="auditAction" placeholder="动作（可选）" clearable style="width:220px" /><el-input v-model="auditResourceType" placeholder="资源类型（可选）" clearable style="width:160px" /><el-input v-model="auditResourceId" placeholder="资源标识（可选）" clearable style="width:220px" /><el-select v-model="auditOutcome" placeholder="结果" clearable style="width:130px"><el-option label="成功" value="success" /><el-option label="拒绝" value="rejected" /><el-option label="失败" value="failed" /></el-select><el-input v-model="auditSince" type="datetime-local" aria-label="开始时间" style="width:190px" /><el-input v-model="auditUntil" type="datetime-local" aria-label="结束时间" style="width:190px" /><el-button type="primary" :loading="auditLoading" native-type="submit">查询</el-button><el-button :disabled="auditLoading" @click="resetAuditFilters">重置</el-button></el-form><StatePanel v-if="auditState==='loading'" state="loading" title="正在查询运维审计" description="" /><StatePanel v-else-if="auditState==='error'" state="error" title="审计查询失败" description="审计结果已清空，避免继续展示旧查询结果。" action-label="重试" @action="loadAudit" /><StatePanel v-else-if="!audits.length" state="empty" title="暂无符合条件的运维审计" description="当前筛选条件没有审计事实。" /><template v-else><el-table :data="audits"><el-table-column prop="action" label="操作" min-width="220" /><el-table-column prop="resource_type" label="资源类型" width="150" /><el-table-column prop="resource_id" label="资源标识" min-width="220" show-overflow-tooltip /><el-table-column prop="outcome" label="结果" width="110" /><el-table-column prop="actor" label="操作主体" min-width="180" show-overflow-tooltip /><el-table-column label="Execution" min-width="230"><template #default="{row}"><el-button v-if="executionIdOf(row as RuntimeAudit)" link type="primary" @click="openExecution(executionIdOf(row as RuntimeAudit)!)">{{executionIdOf(row as RuntimeAudit)}}</el-button><span v-else>-</span></template></el-table-column><el-table-column prop="created_at" label="时间" min-width="180" /></el-table><el-pagination v-if="auditTotal" v-model:current-page="auditPage" v-model:page-size="auditPageSize" :total="auditTotal" :page-sizes="[10,20,50,100]" layout="total,sizes,prev,pager,next" @change="loadAudit" /></template></el-tab-pane>
      <el-tab-pane label="死信" name="dead-letters"><div class="tab-toolbar"><div><strong>死信管理</strong><span>重新投递只重新进入后端队列，不由浏览器直接请求目标地址。</span></div><el-button link type="primary" :loading="deadLetterLoading" @click="loadDeadLetters">刷新</el-button></div><StatePanel v-if="deadLetterState==='loading'" state="loading" title="正在加载死信" description="" /><StatePanel v-else-if="deadLetterState==='error'" state="error" title="死信查询失败" description="死信数据已清空，避免展示 stale facts。" action-label="重试" @action="loadDeadLetters" /><StatePanel v-else-if="!deadLetters.length" state="empty" title="当前没有死信" description="当前租户没有可重新投递的 Delivery。" /><template v-else><el-table :data="deadLetters"><el-table-column prop="id" label="Delivery" min-width="270" show-overflow-tooltip /><el-table-column prop="integration_event_id" label="事件" min-width="270" show-overflow-tooltip /><el-table-column prop="attempt_count" label="尝试次数" width="100" /><el-table-column prop="response_status_code" label="HTTP" width="90" /><el-table-column label="错误" min-width="190" show-overflow-tooltip><template #default="{row}">{{row.last_error_code||row.last_error_message||'-'}}</template></el-table-column><el-table-column prop="updated_at" label="更新时间" min-width="180" /><el-table-column label="操作" width="110" fixed="right"><template #default="{row}"><el-button link type="primary" :loading="replayingId===row.id" @click="replay(row.id)">重新投递</el-button></template></el-table-column></el-table><el-pagination v-if="deadLetterTotal" v-model:current-page="deadLetterPage" v-model:page-size="deadLetterPageSize" :total="deadLetterTotal" :page-sizes="[10,20,50]" layout="total,sizes,prev,pager,next" @change="loadDeadLetters" /></template></el-tab-pane>
    </el-tabs></template>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { Refresh } from "@element-plus/icons-vue";
import { useRouter } from "vue-router";
import PageToolbar from "@/components/ui/PageToolbar.vue";
import StatePanel from "@/components/ui/StatePanel.vue";
import SurfaceCard from "@/components/ui/SurfaceCard.vue";
import MetricCard from "@/components/ui/MetricCard.vue";
import { runtimeOperationsApi, type RuntimeAlert, type RuntimeAlertRule, type RuntimeAudit, type RuntimeDeadLetter, type RuntimeGlobalPosture, type RuntimeMetricSample, type RuntimeOperationsOverview, type RuntimeProvider } from "@/api/runtimeOperations";
const router=useRouter(); const activeTab=ref("global"),windowHours=ref(24),globalPosture=ref<RuntimeGlobalPosture>(),overview=ref<RuntimeOperationsOverview>(),alerts=ref<RuntimeAlert[]>([]),providers=ref<RuntimeProvider[]>([]),alertRules=ref<RuntimeAlertRule[]>([]),audits=ref<RuntimeAudit[]>([]),metricSeries=ref<RuntimeMetricSample[]>([]),deadLetters=ref<RuntimeDeadLetter[]>([]); const loading=ref(false),error=ref(false),loadingAlerts=ref(false),loadingProviders=ref(false),auditLoading=ref(false),metricLoading=ref(false),deadLetterLoading=ref(false),actionLoading=ref(false); const globalState=ref<"loading"|"success"|"error">("loading"),overviewState=ref<"loading"|"success"|"error">("loading"),alertsState=ref<"loading"|"success"|"error">("loading"),providersState=ref<"loading"|"success"|"error">("loading"),metricsState=ref<"loading"|"success"|"error">("loading"),auditState=ref<"loading"|"success"|"error">("loading"),deadLetterState=ref<"loading"|"success"|"error">("loading");
const deadLetterPage=ref(1),deadLetterPageSize=ref(20),deadLetterTotal=ref(0),auditPage=ref(1),auditPageSize=ref(20),auditTotal=ref(0),auditActor=ref(""),auditAction=ref(""),auditResourceType=ref(""),auditResourceId=ref(""),auditOutcome=ref(""),auditSince=ref(""),auditUntil=ref(""),replayingId=ref(""),togglingProviderId=ref(""),probingProviderId=ref(""),togglingRuleId=ref(""),metricName=ref("runtime.notification.delivery"),metricWindow=ref(60),dimensionKey=ref(""),dimensionValue=ref("");
const executionStatuses=[{key:"pending",label:"待处理"},{key:"running",label:"运行中"},{key:"completed",label:"已完成"},{key:"failed",label:"失败"},{key:"cancelled",label:"已取消"}],eventStatuses=[{key:"pending",label:"待处理"},{key:"processing",label:"处理中"},{key:"delivered",label:"已送达"},{key:"failed",label:"处理失败"},{key:"dead_letter",label:"死信"}],deliveryStatuses=[{key:"pending",label:"待处理"},{key:"running",label:"执行中"},{key:"delivered",label:"已送达"},{key:"failed",label:"失败"},{key:"dead_letter",label:"死信"}]; const sloHealthy=computed(()=>!!overview.value&&overview.value.slo.delivery_success_percent>=overview.value.slo.target_percent);
function statusCount(v:Record<string,number>,k:string){return v[k]||0} function executionIdOf(a:RuntimeAudit){const id=a.details?.workflow_execution_id;return typeof id==="string"&&id.length?id:null} function openExecution(id:string){void router.push({path:"/runtime",query:{execution_id:id,source:"runtime-operations-audit"}})}
async function loadGlobal(){globalState.value="loading";globalPosture.value=undefined;try{globalPosture.value=(await runtimeOperationsApi.global({window_hours:windowHours.value,limit:50})).data;globalState.value="success"}catch{globalState.value="error";throw new Error("global")}
}
async function loadOverview(){overviewState.value="loading";overview.value=undefined;try{overview.value=(await runtimeOperationsApi.overview(windowHours.value)).data;overviewState.value="success"}catch{overviewState.value="error";throw new Error("overview")}
}
async function loadAlerts(){loadingAlerts.value=true;alertsState.value="loading";alerts.value=[];alertRules.value=[];try{alerts.value=(await runtimeOperationsApi.alerts(windowHours.value)).data.items;alertRules.value=(await runtimeOperationsApi.alertRules()).data.items;alertsState.value="success"}catch{alertsState.value="error";throw new Error("alerts")}finally{loadingAlerts.value=false}}
async function loadProviders(){loadingProviders.value=true;providersState.value="loading";providers.value=[];try{providers.value=(await runtimeOperationsApi.providers()).data.items;providersState.value="success"}catch{providersState.value="error";throw new Error("providers")}finally{loadingProviders.value=false}}
function auditQueryParams(){return{page:auditPage.value,page_size:auditPageSize.value,actor:auditActor.value.trim()||undefined,action:auditAction.value.trim()||undefined,resource_type:auditResourceType.value.trim()||undefined,resource_id:auditResourceId.value.trim()||undefined,outcome:auditOutcome.value||undefined,since:auditSince.value||undefined,until:auditUntil.value||undefined}}
async function loadAudit(){auditLoading.value=true;auditState.value="loading";audits.value=[];try{const r=await runtimeOperationsApi.auditQuery(auditQueryParams());audits.value=r.data.items;auditTotal.value=r.data.total;auditState.value="success"}catch{auditTotal.value=0;auditState.value="error"}finally{auditLoading.value=false}} async function queryAudit(){auditPage.value=1;await loadAudit()} async function resetAuditFilters(){auditActor.value="";auditAction.value="";auditResourceType.value="";auditResourceId.value="";auditOutcome.value="";auditSince.value="";auditUntil.value="";auditPage.value=1;await loadAudit()}
async function loadMetrics(){metricLoading.value=true;metricsState.value="loading";metricSeries.value=[];try{metricSeries.value=(await runtimeOperationsApi.metricSeries(metricName.value.trim(),metricWindow.value,dimensionKey.value||undefined,dimensionValue.value||undefined)).data.items;metricsState.value="success"}catch{metricsState.value="error"}finally{metricLoading.value=false}}
async function loadDeadLetters(){deadLetterLoading.value=true;deadLetterState.value="loading";deadLetters.value=[];try{const r=await runtimeOperationsApi.deadLetters(deadLetterPage.value,deadLetterPageSize.value);deadLetters.value=r.data.items;deadLetterTotal.value=r.data.total;deadLetterState.value="success"}catch{deadLetterTotal.value=0;deadLetterState.value="error"}finally{deadLetterLoading.value=false}}
async function loadAll(){loading.value=true;error.value=false;try{await Promise.all([loadGlobal(),loadOverview(),loadAlerts(),loadProviders(),loadAudit(),loadDeadLetters()])}catch{error.value=true}finally{loading.value=false}}
async function evaluateAlerts(){if(actionLoading.value)return;actionLoading.value=true;try{const r=await runtimeOperationsApi.evaluateAlertRules();ElMessage.success(`规则评估完成，本次状态发生变化 ${r.data.count} 条`);await loadAlerts()}catch{ElMessage.error("告警评估失败，请稍后重试")}finally{actionLoading.value=false}}
async function toggleProvider(row:RuntimeProvider,requested:boolean){if(togglingProviderId.value)return;togglingProviderId.value=row.id;try{await runtimeOperationsApi.setProviderEnabled(row.id,requested);await loadProviders();ElMessage.success(requested?"Provider 已启用":"Provider 已停用")}catch{await loadProviders();ElMessage.error("Provider 状态更新失败，请稍后重试")}finally{togglingProviderId.value=""}}
async function probeProvider(row:RuntimeProvider){if(probingProviderId.value)return;probingProviderId.value=row.id;try{const r=await runtimeOperationsApi.probeProviderHealth(row.id);await loadProviders();ElMessage.success(r.data.error?`Provider ${row.name} 探测失败，请检查 Provider 配置。`:`Provider ${row.name} 探测完成：${r.data.status}${r.data.latency_ms==null?"":`，${r.data.latency_ms} ms`}`)}catch{ElMessage.error("Provider 健康探测失败，请稍后重试")}finally{probingProviderId.value=""}}
async function toggleRule(row:RuntimeAlertRule,requested:boolean){if(togglingRuleId.value)return;togglingRuleId.value=row.id;try{await runtimeOperationsApi.setAlertRuleEnabled(row.id,requested);await loadAlerts();ElMessage.success(requested?"告警规则已启用":"告警规则已停用")}catch{await loadAlerts();ElMessage.error("告警规则状态更新失败，请稍后重试")}finally{togglingRuleId.value=""}}
async function snapshotMetrics(){if(metricLoading.value)return;metricLoading.value=true;try{const r=await runtimeOperationsApi.createMetricsSnapshot();ElMessage.success(`已写入 ${r.data.samples_written} 条指标样本`);await loadMetrics()}catch{ElMessage.error("指标采样失败，请稍后重试")}finally{metricLoading.value=false}}
async function replay(id:string){if(replayingId.value)return;try{await ElMessageBox.confirm("重新投递会将 Delivery 重新进入后端队列，不会由浏览器直接请求目标地址。","确认重新投递",{type:"warning"});replayingId.value=id;const r=await runtimeOperationsApi.replayDeadLetters([id]);if(r.data.rejected.length)throw new Error(r.data.rejected[0].reason);ElMessage.success("Delivery 已重新进入投递队列");await loadDeadLetters()}catch(e){if(e!=="cancel"&&e!=="close")ElMessage.error("重新投递失败，请稍后重试")}finally{replayingId.value=""}}
onMounted(loadAll)
</script>
<style scoped>.operations-console{padding:0}.toolbar{margin-bottom:16px}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.slo-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:14px}.status-row{display:flex;justify-content:space-between;align-items:center;margin:10px 0}.status-row span,.muted{color:var(--ui-text-tertiary);font-size:12px}.tab-toolbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.tab-toolbar strong,.tab-toolbar span{display:block}.tab-toolbar span{margin-top:4px;color:var(--ui-text-tertiary);font-size:12px}.audit-filters{margin-bottom:14px}@media(max-width:900px){.metric-grid,.slo-grid{grid-template-columns:1fr}.tab-toolbar{align-items:flex-start;flex-direction:column;gap:10px}.audit-filters :deep(.el-form-item){margin-right:0;width:100%}.audit-filters :deep(.el-input),.audit-filters :deep(.el-select){width:100%!important}}</style>