import { test, expect, type APIRequestContext } from "@playwright/test";

function normalizeApiOrigin(value: string): string { return value.replace(/\/+$/, "").replace(/\/api\/v1$/, ""); }
const apiOrigin = normalizeApiOrigin(process.env.API_BASE_URL || "http://127.0.0.1:8000/api/v1");
const apiPath = (path: string): string => `/api/v1${path.startsWith("/") ? path : `/${path}`}`;

async function assertTriggerStatus(api: APIRequestContext, workflowId: string, triggerId: string, headers: Record<string, string>, status: string) {
  await expect.poll(async () => { const response = await api.get(apiPath(`/workflows/${workflowId}/triggers`), { headers }); expect(response.ok()).toBeTruthy(); const body = await response.json(); const items = Array.isArray(body) ? body : body.items; return items?.find((item: { id: string }) => item.id === triggerId)?.status; }, { timeout: 15_000, intervals: [500, 1000, 2000] }).toBe(status);
}
async function confirmMessageBox(page: import("@playwright/test").Page) { const dialog = page.locator(".el-message-box:visible"); await expect(dialog).toBeVisible(); await dialog.locator(".el-message-box__btns .el-button--primary").click(); }

test("Webhook browser runtime converges duplicate events and enforces lifecycle security", async ({ page, playwright }) => {
  test.setTimeout(60_000); const nonce = crypto.randomUUID().replaceAll("-", "").slice(0, 12); const username = `frontend_webhook_runtime_${nonce}`; const password = `FrontendE2E!${nonce}`; const triggerName = `Browser Webhook Runtime ${nonce}`; const secret = `WebhookSecret!${nonce}1234`; const eventId = `event-${nonce}`; const api: APIRequestContext = await playwright.request.newContext({ baseURL: apiOrigin });
  try {
    const register = await api.post(apiPath("/auth/register"), { data: { username, password } }); expect([200, 201]).toContain(register.status()); const login = await api.post(apiPath("/auth/login"), { data: { username, password } }); expect(login.ok()).toBeTruthy(); const loginBody = await login.json(); const token = loginBody.access_token as string; const headers = { Authorization: `Bearer ${token}` };
    const workflowResponse = await api.post(apiPath("/workflows"), { headers, data: { name: `Browser Webhook Runtime ${nonce}`, description: "Phase 1.8-E browser runtime fixture" } }); expect(workflowResponse.status()).toBe(201); const workflow = await workflowResponse.json(); const versionResponse = await api.post(apiPath(`/workflows/${workflow.id}/versions`), { headers, data: { definition: { nodes: [{ id: "input", type: "input", config: {} }, { id: "output", type: "output", config: {} }], edges: [{ source: "input", target: "output" }] } } }); expect(versionResponse.status()).toBe(201); const version = await versionResponse.json(); const publishResponse = await api.post(apiPath(`/workflows/${workflow.id}/versions/${version.id}/publish`), { headers }); expect(publishResponse.status()).toBe(200);
    await page.goto("/login"); await page.getByLabel("用户名").fill(username); await page.getByLabel("密码").fill(password); await page.getByRole("button", { name: "登录" }).click(); await expect(page).toHaveURL(/\/dashboard$/); await page.goto("/workflows/triggers"); await expect(page.getByText("Workflow Trigger Governance")).toBeVisible();
    const workflowFormItem = page.locator(".el-form-item").filter({ hasText: "Workflow" }).first(); await workflowFormItem.locator(".el-select").click(); const workflowOption = page.locator(".el-select-dropdown:visible .el-select-dropdown__item").filter({ hasText: `${workflow.name} (published)` }).first(); await expect(workflowOption).toBeVisible(); await workflowOption.click(); await page.getByLabel("Trigger 名称").fill(triggerName); await page.locator(".el-form-item").filter({ hasText: "类型" }).first().locator(".el-select").click(); await page.keyboard.press("End"); await page.keyboard.press("Enter"); await expect(page.getByLabel("Webhook Secret")).toBeVisible(); await page.getByLabel("Webhook Secret").fill(secret); await page.getByRole("button", { name: "创建 Trigger" }).click();
    const triggerRow = page.locator(".el-table__body-wrapper tbody tr").filter({ hasText: triggerName }); await expect(triggerRow).toBeVisible(); await expect(triggerRow).toContainText("webhook"); await expect(triggerRow).toContainText("已配置"); const persisted = await api.get(apiPath(`/workflows/${workflow.id}/triggers`), { headers }); expect(persisted.ok()).toBeTruthy(); const persistedItems = await persisted.json(); const persistedTrigger = persistedItems.find((item: { name: string }) => item.name === triggerName); expect(persistedTrigger).toMatchObject({ trigger_type: "webhook", status: "enabled" }); expect(persistedTrigger.config.secret_hash).toBeUndefined();
    const webhookPath = apiPath(`/webhooks/${persistedTrigger.id}`); const payload = { event_id: eventId, source: "browser-e2e", value: nonce }; const first = await api.post(webhookPath, { headers: { "X-Webhook-Secret": secret, "Idempotency-Key": eventId }, data: payload }); expect(first.status()).toBe(202); const firstBody = await first.json(); expect(firstBody).toMatchObject({ status: "accepted", idempotency_key: `webhook:${persistedTrigger.id}:${eventId}` }); expect(firstBody.execution_id).toBeTruthy(); const duplicate = await api.post(webhookPath, { headers: { "X-Webhook-Secret": secret, "Idempotency-Key": eventId }, data: payload }); expect(duplicate.status()).toBe(200); expect(await duplicate.json()).toMatchObject({ status: "duplicate", execution_id: firstBody.execution_id, idempotency_key: firstBody.idempotency_key }); const invalidSecret = await api.post(webhookPath, { headers: { "X-Webhook-Secret": `${secret}-invalid`, "Idempotency-Key": `invalid-${eventId}` }, data: payload }); expect(invalidSecret.status()).toBe(401);
    await expect.poll(async () => { const executions = await api.get(apiPath(`/workflows/${workflow.id}/executions`), { headers }); expect(executions.ok()).toBeTruthy(); const items = await executions.json(); const execution = items.find((item: { id: string }) => item.id === firstBody.execution_id); return execution ? { status: execution.status, id: execution.id } : null; }, { timeout: 20_000, intervals: [500, 1000, 2000] }).toMatchObject({ id: firstBody.execution_id, status: expect.any(String) });
    await page.goto(`/runtime?tab=executions&source=webhook&execution_id=${encodeURIComponent(firstBody.execution_id)}&workflow_id=${encodeURIComponent(workflow.id)}`); await expect(page).toHaveURL(new RegExp(`[?&]execution_id=${firstBody.execution_id}`)); await expect(page.getByText("运行记录详情")).toBeVisible(); await expect(page.getByText(firstBody.execution_id, { exact: true })).toBeVisible();
    await triggerRow.getByRole("button", { name: "禁用" }).click(); await confirmMessageBox(page); await assertTriggerStatus(api, workflow.id, persistedTrigger.id, headers, "disabled"); const disabled = await api.post(webhookPath, { headers: { "X-Webhook-Secret": secret, "Idempotency-Key": `disabled-${eventId}` }, data: { ...payload, event_id: `disabled-${eventId}` } }); expect(disabled.status()).toBe(409);
    await triggerRow.getByRole("button", { name: "删除" }).click(); await confirmMessageBox(page); await expect(page.getByText("Trigger 已删除")).toBeVisible(); const deleted = await api.post(webhookPath, { headers: { "X-Webhook-Secret": secret, "Idempotency-Key": `deleted-${eventId}` }, data: { ...payload, event_id: `deleted-${eventId}` } }); expect(deleted.status()).toBe(404);
  } finally { await api.dispose(); }
});
