$ErrorActionPreference = "Stop"
$backendRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backendRoot

function Get-ServiceProcessSnapshot {
    Get-CimInstance Win32_Process |
        Where-Object {
            $_.CommandLine -and (
                $_.CommandLine -match "uvicorn|app\.main|scheduler|worker|postgres|redis-server|redis-server\.exe"
            )
        } |
        Select-Object ProcessId, Name, CommandLine
}

function Invoke-Test {
    param(
        [string]$Description,
        [string[]]$Arguments
    )

    Write-Host $Description
    & uv run pytest @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Test gate failed: $Description"
    }
}

$beforeServices = @(Get-ServiceProcessSnapshot)

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Phase 2.10-II Runtime Audit / Trace Correlation Backend Gate"
Write-Host "============================================================"
Write-Host "[0/6] Local precondition checks"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
Write-Host "Test data policy: all test fixtures and identities are generated by the tests; no manual IDs, tokens, or business data are required."
Write-Host "Warning policy: warnings are treated as test errors."
Write-Host "Service startup is a boundary check only; missing services are never auto-started."

Write-Host "[1/6] Runtime correlation unit regression"
Invoke-Test "Runtime correlation unit regression" @(
    "-q",
    "tests/unit/test_runtime_audit_trace_correlation.py",
    "--tb=long",
    "-W", "error"
)

Write-Host "[2/6] Runtime correlation API Contract hardening"
Invoke-Test "Runtime correlation API Contract hardening" @(
    "-q",
    "tests/api_contract/test_runtime_correlations_contract.py",
    "--tb=long",
    "-W", "error"
)

Write-Host "[3/6] PostgreSQL readiness and Real Acceptance"
$postgresCheck = @"
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))

asyncio.run(main())
"@
$postgresCheck | uv run python -
if ($LASTEXITCODE -ne 0) {
    Write-Host "[NOT EXECUTED] PostgreSQL is not reachable through the configured backend database URL."
    Write-Host "Required manual startup command (run only when the developer wants local PostgreSQL):"
    Write-Host "  docker compose up -d postgres"
    Write-Host "This gate intentionally does not execute that command."
    exit 2
}

Invoke-Test "Runtime correlation Real PostgreSQL Acceptance" @(
    "-q",
    "tests/api_real/test_runtime_audit_trace_correlation_acceptance.py",
    "-m", "real_api",
    "--tb=long",
    "-W", "error"
)

Write-Host "[4/6] Runtime correlation targeted regression"
Invoke-Test "Runtime correlation targeted regression" @(
    "-q",
    "tests/unit/test_runtime_audit_trace_correlation.py",
    "tests/api_contract/test_runtime_correlations_contract.py",
    "tests/api_contract/test_api_runtime_endpoints.py",
    "--tb=long",
    "-W", "error"
)

Write-Host "[5/6] Backend default regression with warning enforcement"
Invoke-Test "Backend default regression" @(
    "-q",
    "--tb=long",
    "-W", "error"
)

Write-Host "[6/6] Service startup boundary"
$afterServices = @(Get-ServiceProcessSnapshot)
$beforeIds = @($beforeServices | ForEach-Object { $_.ProcessId })
$created = @($afterServices | Where-Object { $beforeIds -notcontains $_.ProcessId })

if ($created.Count -gt 0) {
    $created | Format-Table -AutoSize | Out-String | Write-Host
    throw "Service startup boundary violated: a protected service process appeared during the gate."
}

Write-Host "[PASS] No protected service process appeared during the gate."
Write-Host "[PASS] No API/Scheduler/Worker/PostgreSQL/Redis process was intentionally created, started, restarted, or stopped by this gate."
Write-Host "[PASS] Runtime Audit / Trace Correlation Backend Gate completed with warnings treated as errors."
