$ErrorActionPreference = "Stop"
$backendRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backendRoot

function Get-ServiceProcessSnapshot {
    Get-CimInstance Win32_Process |
        Where-Object {
            $_.CommandLine -and (
                $_.CommandLine -match "uvicorn|app\.main|scheduler|worker|postgres|redis-server|redis-server\.exe"
            )
        } |
        Select-Object ProcessId, Name, CommandLine
}

function Invoke-Test {
    param(
        [string]$Description,
        [string[]]$Arguments
    )

    Write-Host $Description
    & uv run pytest @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Test gate failed: $Description"
    }
}

$beforeServices = @(Get-ServiceProcessSnapshot)

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Phase 2.10-II Operator Audit Governance Backend Gate"
Write-Host "============================================================"
Write-Host "[0/5] Local precondition checks"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
Write-Host "Test data policy: all test fixtures and identities are generated by the tests; no manual IDs, tokens, or business data are required."
Write-Host "Warning policy: warnings are treated as test errors."
Write-Host "Migration policy: no schema migration is required by this slice; the Real PostgreSQL test uses the existing AuditLog contract."

Write-Host "[1/5] Operator audit API Contract"
Invoke-Test "Operator audit API Contract" @(
    "-q",
    "tests/api_contract/test_runtime_operator_audit_contract.py",
    "--tb=long",
    "-W", "error"
)

Write-Host "[2/5] PostgreSQL readiness"
$postgresCheck = @"
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))

asyncio.run(main())
"@
$postgresCheck | uv run python -
if ($LASTEXITCODE -ne 0) {
    Write-Host "[NOT EXECUTED] PostgreSQL is not reachable through the configured backend database URL."
    Write-Host "Required manual startup command (run only when the developer wants local PostgreSQL):"
    Write-Host "  docker compose up -d postgres"
    Write-Host "This gate intentionally does not execute that command."
    exit 2
}

Write-Host "[3/5] Operator audit Real PostgreSQL Acceptance"
Invoke-Test "Operator audit Real PostgreSQL Acceptance" @(
    "-q",
    "tests/api_real/test_runtime_operator_audit_acceptance.py",
    "-m", "real_api",
    "--tb=long",
    "-W", "error"
)

Write-Host "[4/5] Operator audit targeted regression"
Invoke-Test "Operator audit targeted regression" @(
    "-q",
    "tests/api_contract/test_runtime_operator_audit_contract.py",
    "tests/api_contract/test_runtime_operations_audit_query_contract.py",
    "tests/api_real/test_runtime_operator_audit_acceptance.py",
    "--tb=long",
    "-W", "error"
)

Write-Host "[5/5] Service startup boundary"
$afterServices = @(Get-ServiceProcessSnapshot)
$beforeIds = @($beforeServices | ForEach-Object { $_.ProcessId })
$created = @($afterServices | Where-Object { $beforeIds -notcontains $_.ProcessId })

if ($created.Count -gt 0) {
    $created | Format-Table -AutoSize | Out-String | Write-Host
    throw "Service startup boundary violated: a protected service process appeared during the gate."
}

Write-Host "[PASS] No protected service process appeared during the gate."
Write-Host "[PASS] Operator Action audit query uses AuditLog as the canonical fact source."
Write-Host "[PASS] Tenant isolation, exact filters, pagination and time-window validation are covered."
Write-Host "[PASS] Operator Audit Governance Backend Gate completed with warnings treated as errors."
