$ErrorActionPreference = "Stop"
$backendRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backendRoot

function Get-ServiceProcessSnapshot {
    Get-CimInstance Win32_Process |
        Where-Object {
            $_.CommandLine -and ($_.CommandLine -match "uvicorn|app\.main|scheduler|worker|postgres|redis-server|redis-server\.exe")
        } |
        Select-Object ProcessId, Name, CommandLine
}

function Invoke-Test {
    param(
        [string]$Description,
        [string[]]$Arguments
    )

    Write-Host $Description
    & uv run pytest @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Test gate failed: $Description"
    }
}

$beforeServices = @(Get-ServiceProcessSnapshot)

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Runtime Trace Resolution Regression Gate"
Write-Host "============================================================"
Write-Host "[0/4] Local precondition checks"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
Write-Host "Test data policy: all fixtures and identities are generated by tests; no manual IDs, tokens, or business data are required."
Write-Host "Warning policy: warnings are treated as test errors."

Write-Host "[1/4] Trace resolution unit regression"
Invoke-Test "Trace resolution unit regression" @(
    "-q",
    "tests/unit/test_runtime_audit_trace_correlation.py",
    "tests/unit/test_runtime_audit_trace_correlation_ambiguity.py",
    "--tb=long",
    "-W", "error"
)

Write-Host "[2/4] PostgreSQL readiness"
$postgresCheck = @"
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))

asyncio.run(main())
"@
$postgresCheck | uv run python -
if ($LASTEXITCODE -ne 0) {
    Write-Host "[NOT EXECUTED] PostgreSQL is not reachable through the configured backend database URL."
    Write-Host "This gate intentionally does not start PostgreSQL or any other protected service."
    exit 2
}

Write-Host "[3/4] Real PostgreSQL Trace resolution acceptance"
Invoke-Test "Real PostgreSQL Trace resolution acceptance" @(
    "-q",
    "tests/api_real/test_runtime_audit_trace_correlation_ambiguity_acceptance.py",
    "-m", "real_api",
    "--tb=long",
    "-W", "error"
)

Write-Host "[4/4] Service startup boundary"
$afterServices = @(Get-ServiceProcessSnapshot)
$beforeIds = @($beforeServices | ForEach-Object { $_.ProcessId })
$created = @($afterServices | Where-Object { $beforeIds -notcontains $_.ProcessId })
if ($created.Count -gt 0) {
    $created | Format-Table -AutoSize | Out-String | Write-Host
    throw "Service startup boundary violated: a protected service process appeared during the gate."
}

Write-Host "[PASS] Repeated Trace events for one Execution resolve deterministically."
Write-Host "[PASS] Ambiguous Trace -> Execution mappings are rejected instead of guessed."
Write-Host "[PASS] PostgreSQL acceptance completed with warnings treated as errors."
Write-Host "[PASS] No protected service process appeared during the gate."
Write-Host "[PASS] Runtime Trace Resolution Regression Gate completed."
