$ErrorActionPreference = "Stop"

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Phase 2.10-II Operator Audit Access Governance Gate"
Write-Host "============================================================"
Write-Host "[0/4] Local precondition checks"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
Write-Host "Test data policy: all identities and tokens are generated by tests; no manual IDs or credentials are required."
Write-Host "Warning policy: warnings are treated as test errors."

Write-Host "[1/4] Operator Audit access governance unit/API contract"
uv run pytest -q -W error tests/api_contract/test_runtime_operator_audit_contract.py
if ($LASTEXITCODE -ne 0) { throw "Operator Audit access governance contract tests failed." }

Write-Host "[2/4] Backend targeted regression"
uv run pytest -q -W error tests/unit tests/api_contract -k "operator_audit or operator_action"
if ($LASTEXITCODE -ne 0) { throw "Operator governance targeted regression failed." }

Write-Host "[3/4] Backend default regression"
uv run pytest -q -W error
if ($LASTEXITCODE -ne 0) { throw "Backend default regression failed." }

Write-Host "[4/4] Service startup boundary"
Write-Host "[PASS] No API/Scheduler/Worker/PostgreSQL/Redis process was created, started, restarted, or stopped by this gate."
Write-Host "[PASS] Operator Audit access governance Gate completed with warnings treated as errors."
