$ErrorActionPreference = "Stop"
$backendRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backendRoot

function Invoke-Test {
    param(
        [string]$Description,
        [string[]]$Arguments
    )

    Write-Host $Description
    & uv run pytest @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Test gate failed: $Description"
    }
}

function Get-ServiceProcessSnapshot {
    Get-CimInstance Win32_Process |
        Where-Object {
            $_.CommandLine -and (
                $_.CommandLine -match "uvicorn|app\.main|scheduler|worker|postgres|redis-server|redis-server\.exe"
            )
        } |
        Select-Object ProcessId, Name, CommandLine
}

$beforeServices = @(Get-ServiceProcessSnapshot)
$previousDatabaseIntegration = $env:RUN_DATABASE_INTEGRATION

try {
    Write-Host "============================================================"
    Write-Host "Enterprise AI Agent Platform - Phase 2.10-II Operator Audit Governance Gate"
    Write-Host "============================================================"
    Write-Host "[0/6] Local precondition checks"
    Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
    Write-Host "Test data policy: all test fixtures are generated by tests; no manual IDs, credentials, or business data are required."
    Write-Host "Warning policy: warnings are treated as test errors."
    Write-Host "Migration policy: PostgreSQL is upgraded to Alembic head only when already reachable; no service is started."

    Write-Host "[1/6] Operator Governance unit/API regression"
    Invoke-Test "Operator Governance regression" @(
        "-q",
        "tests/api_contract/test_runtime_operator_audit_contract.py",
        "tests/api_contract/test_runtime_operations_audit_query_contract.py",
        "tests/unit",
        "-k", "operator_audit or operator_action",
        "-W", "error"
    )

    Write-Host "[2/6] PostgreSQL readiness"
    $postgresCheck = @"
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))

asyncio.run(main())
"@
    $postgresCheck | uv run python -
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[NOT EXECUTED] PostgreSQL is not reachable through the configured backend database URL."
        Write-Host "Required manual startup command: docker compose up -d postgres"
        Write-Host "This gate intentionally does not execute that command."
        exit 2
    }

    Write-Host "[3/6] Database migration/head verification"
    & uv run alembic upgrade head
    if ($LASTEXITCODE -ne 0) { throw "Alembic upgrade head failed." }
    $heads = & uv run alembic heads
    if ($LASTEXITCODE -ne 0) { throw "Alembic heads verification failed." }
    $headLines = @($heads | Where-Object { $_ -match "^[0-9a-z_]+ \(" })
    if ($headLines.Count -ne 1) {
        $heads | Write-Host
        throw "Alembic migration graph must expose exactly one head."
    }

    Write-Host "[4/6] Operator Governance PostgreSQL Acceptance"
    $env:RUN_DATABASE_INTEGRATION = "1"
    Invoke-Test "Operator Governance PostgreSQL Acceptance" @(
        "-q",
        "tests/api_real/test_operator_action_result_correlation_acceptance.py",
        "tests/api_real/test_operator_action_schema_acceptance.py",
        "tests/api_real/test_operator_audit_query_index_acceptance.py",
        "tests/integration/test_operator_action_idempotency.py",
        "tests/integration/test_operator_execution_retry_resume_concurrency.py",
        "-m", "integration",
        "--tb=long",
        "-W", "error"
    )

    Write-Host "[5/6] Canonical Operator Audit query-plan performance"
    Invoke-Test "Operator Audit query-plan performance acceptance" @(
        "-q",
        "tests/api_real/test_operator_audit_query_performance_acceptance.py",
        "-m", "integration",
        "--tb=long",
        "-W", "error"
    )

    Write-Host "[6/6] Service startup boundary"
    $afterServices = @(Get-ServiceProcessSnapshot)
    $beforeIds = @($beforeServices | ForEach-Object { $_.ProcessId })
    $created = @($afterServices | Where-Object { $beforeIds -notcontains $_.ProcessId })
    if ($created.Count -gt 0) {
        $created | Format-Table -AutoSize | Out-String | Write-Host
        throw "Service startup boundary violated: a protected service process appeared during the gate."
    }

    Write-Host "[PASS] Operator Action → AuditLog → Result Resource schema is migration-complete."
    Write-Host "[PASS] Canonical Operator Audit indexes are present with tenant-first column order."
    Write-Host "[PASS] Alembic exposes exactly one migration head."
    Write-Host "[PASS] PostgreSQL Acceptance completed with warnings treated as errors."
    Write-Host "[PASS] Retry / Resume cross-session concurrency is included in the gate."
    Write-Host "[PASS] Canonical Operator Audit query plans use tenant-first indexes."
    Write-Host "[PASS] No protected service process appeared during the gate."
    Write-Host "[PASS] Operator Governance Gate completed."
}
finally {
    if ($null -eq $previousDatabaseIntegration) {
        Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
    } else {
        $env:RUN_DATABASE_INTEGRATION = $previousDatabaseIntegration
    }
}
