$ErrorActionPreference = "Stop"
$backendRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backendRoot

function Get-ServiceProcessSnapshot {
    Get-CimInstance Win32_Process |
        Where-Object {
            $_.CommandLine -and ($_.CommandLine -match "uvicorn|app\.main|scheduler|worker|postgres|redis-server|redis-server\.exe")
        } |
        Select-Object ProcessId, Name, CommandLine
}

function Invoke-Test {
    param(
        [string]$Description,
        [string[]]$Arguments
    )

    Write-Host $Description
    & uv run pytest @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Release gate failed: $Description"
    }
}

$beforeServices = @(Get-ServiceProcessSnapshot)
$previousDatabaseIntegration = $env:RUN_DATABASE_INTEGRATION

try {
    Write-Host "============================================================"
    Write-Host "Enterprise AI Agent Platform - Backend Release Gate"
    Write-Host "============================================================"
    Write-Host "[0/7] Local precondition checks"
    Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
    Write-Host "Test data policy: all test fixtures, identities, and Idempotency-Key values are generated by tests."
    Write-Host "Warning policy: warnings are treated as test errors."
    Write-Host "Migration policy: PostgreSQL is upgraded to Alembic head only when already reachable; no service is started."

    Write-Host "[1/7] Backend default regression"
    Invoke-Test "Backend default regression" @(
        "-q",
        "-W", "error",
        "-s"
    )

    Write-Host "[2/7] PostgreSQL readiness"
    $postgresCheck = @"
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))

asyncio.run(main())
"@
    $postgresCheck | uv run python -
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[NOT EXECUTED] PostgreSQL is not reachable through the configured backend database URL."
        Write-Host "This gate intentionally does not start PostgreSQL or any other protected service."
        exit 2
    }

    Write-Host "[3/7] Alembic migration/head verification"
    & uv run alembic upgrade head
    if ($LASTEXITCODE -ne 0) {
        throw "Release gate failed: Alembic upgrade head failed."
    }

    $headsOutput = @(& uv run alembic heads 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw "Release gate failed: Alembic heads command failed."
    }
    $headLines = @(
        $headsOutput |
            ForEach-Object { $_.ToString().Trim() } |
            Where-Object { $_ -match "\(head\)\s*$" }
    )
    $headLines | ForEach-Object { Write-Host $_ }
    if ($headLines.Count -ne 1) {
        throw "Release gate failed: expected exactly one Alembic migration head."
    }

    Write-Host "[4/7] Operator Governance acceptance"
    $env:RUN_DATABASE_INTEGRATION = "1"
    Invoke-Test "Operator Action Idempotency PostgreSQL Acceptance" @(
        "-q",
        "tests/integration/test_operator_action_idempotency.py",
        "-m", "real_api",
        "--tb=long",
        "-W", "error"
    )
    Invoke-Test "Retry / Resume cross-session concurrency Acceptance" @(
        "-q",
        "tests/integration/test_operator_execution_retry_resume_concurrency.py",
        "-m", "real_api",
        "--tb=long",
        "-W", "error"
    )

    Write-Host "[5/7] Operator Action Result Lineage acceptance"
    Invoke-Test "Result lineage acceptance" @(
        "-q",
        "tests/api_real/test_operator_action_result_lineage_acceptance.py",
        "-m", "real_api",
        "--tb=long",
        "-W", "error"
    )
    Invoke-Test "Result lineage rollback acceptance" @(
        "-q",
        "tests/api_real/test_operator_action_transaction_rollback_acceptance.py",
        "-m", "real_api",
        "--tb=long",
        "-W", "error"
    )
    Invoke-Test "Resume lineage acceptance" @(
        "-q",
        "tests/api_real/test_operator_action_resume_lineage_acceptance.py",
        "-m", "real_api",
        "--tb=long",
        "-W", "error"
    )

    Write-Host "[6/7] Service startup boundary"
    $afterServices = @(Get-ServiceProcessSnapshot)
    $beforeIds = @($beforeServices | ForEach-Object { $_.ProcessId })
    $created = @($afterServices | Where-Object { $beforeIds -notcontains $_.ProcessId })
    if ($created.Count -gt 0) {
        $created | Format-Table -AutoSize | Out-String | Write-Host
        throw "Service startup boundary violated: a protected service process appeared during the gate."
    }

    Write-Host "[PASS] Backend default regression completed with warnings treated as errors."
    Write-Host "[PASS] PostgreSQL readiness verified without starting protected services."
    Write-Host "[PASS] Alembic migration upgraded to head and exposes exactly one migration head."
    Write-Host "[PASS] Operator Action idempotency and cross-session concurrency acceptance completed."
    Write-Host "[PASS] Retry / Resume Result Lineage and rollback acceptance completed."
    Write-Host "[PASS] No protected service process appeared during the gate."
    Write-Host "[PASS] Backend Release Gate completed."
}
finally {
    if ($null -eq $previousDatabaseIntegration) {
        Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
    } else {
        $env:RUN_DATABASE_INTEGRATION = $previousDatabaseIntegration
    }
}
