$ErrorActionPreference="Stop"

$backendRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..")).Path

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Operator Governance PostgreSQL Acceptance"
Write-Host "Scope: Operator Action claim -> replay -> tenant isolation -> atomic rollback -> Trigger lifecycle"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops protected services."
Write-Host "Test data policy: all Tenant/User/Workflow/Trigger/Execution/Idempotency records are generated by the tests and cleaned automatically."
Write-Host "============================================================"

Push-Location $backendRoot
try {
    Write-Host "[1/5] Verify PostgreSQL dependency"
    Write-Host "[INFO] Database connection is resolved by the project's existing backend configuration; no manual test data or connection value is requested."

    Write-Host "[2/5] Verify migration head"
    uv run alembic upgrade head
    if($LASTEXITCODE -ne 0){
        Write-Host "[NOT EXECUTED] PostgreSQL migration verification could not complete."
        Write-Host "[INFO] Start PostgreSQL manually using the project's normal local development procedure, then rerun this gate."
        Write-Host "[INFO] No protected service was started or stopped by this gate."
        exit 2
    }

    $env:RUN_DATABASE_INTEGRATION="1"

    Write-Host "[3/5] Execute Operator Action Idempotency PostgreSQL acceptance"
    uv run pytest -q -W error tests/integration/test_operator_action_idempotency.py -s
    if($LASTEXITCODE -ne 0){throw "Operator Action Idempotency PostgreSQL acceptance failed."}

    Write-Host "[4/5] Execute Manual Trigger Invoke PostgreSQL acceptance"
    uv run pytest -q -W error tests/integration/test_operator_trigger_invoke.py -s
    if($LASTEXITCODE -ne 0){throw "Manual Trigger Invoke PostgreSQL acceptance failed."}

    Write-Host "[5/5] Execute Trigger Lifecycle PostgreSQL acceptance"
    uv run pytest -q -W error tests/integration/test_operator_trigger_lifecycle_governance.py -s
    if($LASTEXITCODE -ne 0){throw "Trigger Lifecycle PostgreSQL acceptance failed."}

    Write-Host "============================================================"
    Write-Host "[PASS] Operator Governance PostgreSQL acceptance completed."
    Write-Host "[PASS] Covered: concurrent claim, tenant isolation, conflict, failed-key rejection, retry replay, trigger invoke replay, trigger lifecycle, invalid state rejection, delete atomicity, and finalization rollback."
    Write-Host "============================================================"
} finally {
    Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
    Pop-Location
}