$ErrorActionPreference="Stop"

$backendRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..")).Path

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Operator Idempotency PostgreSQL Acceptance"
Write-Host "Scope: atomic Idempotency-Key claim -> tenant isolation"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops protected services."
Write-Host "Test data policy: all Tenant/User/Idempotency records are generated by the test and cleaned automatically."
Write-Host "============================================================"

Push-Location $backendRoot
try {
    Write-Host "[1/3] Verify PostgreSQL dependency"
    if(-not $env:DATABASE_URL -and -not $env:TEST_DATABASE_URL){
        Write-Host "[NOT EXECUTED] DATABASE_URL / TEST_DATABASE_URL is not configured."
        Write-Host "[INFO] Start PostgreSQL manually using the project's normal local development procedure, then rerun this gate."
        Write-Host "[INFO] No protected service was started or stopped by this gate."
        exit 2
    }

    Write-Host "[2/3] Verify migration head"
    uv run alembic upgrade head
    if($LASTEXITCODE -ne 0){throw "Alembic migration verification failed."}

    Write-Host "[3/3] Execute Operator Action Idempotency PostgreSQL acceptance"
    $env:RUN_DATABASE_INTEGRATION="1"
    uv run pytest -q -W error tests/integration/test_operator_action_idempotency.py -s
    if($LASTEXITCODE -ne 0){throw "Operator Action Idempotency PostgreSQL acceptance failed."}

    Write-Host "============================================================"
    Write-Host "[PASS] Operator Action Idempotency PostgreSQL acceptance completed."
    Write-Host "============================================================"
} finally {
    Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
    Pop-Location
}
