<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElMessage } from "element-plus";
import { workflowApi, type Workflow, type WorkflowExecution, type WorkflowTrigger, type SchedulerStatus, type WorkflowVersion, type ScheduledMisfirePolicy, type OperatorActionAvailability, type OperatorActionName } from "@/api/workflows";
import PageHeader from "@/components/ui/PageHeader.vue";
import SurfaceCard from "@/components/ui/SurfaceCard.vue";
import StatePanel from "@/components/ui/StatePanel.vue";
import ConfirmDialog from "@/components/ui/ConfirmDialog.vue";

type PageState = "loading" | "empty" | "error" | "permission" | "success";
type ExecutionAction = "run" | "cancel" | "retry" | "resume";
type TriggerAction = "invoke" | "enable" | "disable" | "delete";
type DiagnosticFocus = "trace" | "audit";
type TriggerEditor = { trigger: WorkflowTrigger | null; name: string; timezone: string; interval_seconds: number; misfire_policy: ScheduledMisfirePolicy; catch_up_limit: number; event_id_field: string; secret: string };
const route = useRoute();
const router = useRouter();
const workflows = ref<Workflow[]>([]);
const versions = ref<WorkflowVersion[]>([]);
const triggers = ref<WorkflowTrigger[]>([]);
const schedules = ref<Record<string, SchedulerStatus>>({});
const executions = ref<WorkflowExecution[]>([]);
const executionAvailability = ref<Record<string, OperatorActionAvailability[]>>({});
const triggerAvailability = ref<Record<string, OperatorActionAvailability[]>>({});
const selectedId = ref(typeof route.query.workflow_id === "string" ? route.query.workflow_id : "");
const focusedExecutionId = ref(typeof route.query.execution_id === "string" ? route.query.execution_id : "");
const diagnosticTraceId = ref(typeof route.query.trace_id === "string" ? route.query.trace_id : "");
const diagnosticAuditId = ref(typeof route.query.audit_id === "string" ? route.query.audit_id : "");
const loading = ref(false); const detailLoading = ref(false); const error = ref(""); const detailError = ref(""); const permissionDenied = ref(false); const pageState = ref<PageState>("loading");
const invokeDialogVisible = ref(false); const invokeLoading = ref(false); const invokeTarget = ref<WorkflowTrigger | null>(null);
const executionDialogVisible = ref(false); const executionActionLoading = ref(false); const executionAction = ref<ExecutionAction | null>(null); const executionTarget = ref<WorkflowExecution | null>(null);
const triggerEditorVisible = ref(false); const triggerEditorLoading = ref(false); const triggerEditor = ref<TriggerEditor>({ trigger: null, name: "", timezone: "UTC", interval_seconds: 300, misfire_policy: "skip", catch_up_limit: 10, event_id_field: "event_id", secret: "" });
const deleteTriggerDialogVisible = ref(false); const deleteTriggerLoading = ref(false); const deleteTriggerTarget = ref<WorkflowTrigger | null>(null);
const triggerActionDialogVisible = ref(false); const triggerActionLoading = ref(false); const triggerAction = ref<Exclude<TriggerAction, "invoke" | "delete"> | null>(null); const triggerActionTarget = ref<WorkflowTrigger | null>(null);

const selected = computed(() => workflows.value.find((item) => item.id === selectedId.value));
const publishedVersion = computed(() => versions.value.find((item) => item.id === selected.value?.published_version_id));
const focusedExecution = computed(() => executions.value.find((item) => item.id === focusedExecutionId.value));
const diagnosticFocus = computed<DiagnosticFocus | null>(() => diagnosticTraceId.value ? "trace" : diagnosticAuditId.value ? "audit" : null);
const diagnosticFocusId = computed(() => diagnosticTraceId.value || diagnosticAuditId.value);
const diagnosticFocusLabel = computed(() => diagnosticFocus.value === "trace" ? "Trace ID" : diagnosticFocus.value === "audit" ? "Audit ID" : "诊断上下文");
const stateTitle = computed(() => ({ loading: "正在加载工作流", empty: "暂无工作流", permission: "无权查看工作流", error: "工作流加载失败" } as Record<string, string>)[pageState.value] ?? "工作流");
const stateDescription = computed(() => ({ loading: "正在同步工作流生命周期数据。", empty: "当前没有可用工作流，请先创建工作流。", permission: "当前账号没有工作流访问权限，请联系管理员。", error: "无法同步工作流数据，请检查服务状态后重试。" } as Record<string, string>)[pageState.value] ?? "");
const lifecycleSteps = computed(() => [
  { label: "工作流", done: Boolean(selected.value), active: false },
  { label: "版本", done: Boolean(publishedVersion.value), active: Boolean(selected.value) && !publishedVersion.value },
  { label: "发布", done: selected.value?.status === "published", active: Boolean(publishedVersion.value) && selected.value?.status !== "published" },
  { label: "触发器", done: triggers.value.length > 0, active: selected.value?.status === "published" && triggers.value.length === 0 },
  { label: "运行", done: executions.value.length > 0, active: selected.value?.status === "published" && executions.value.length === 0 },
]);
const statusText: Record<string, string> = { draft: "草稿", published: "已发布", archived: "已归档", pending: "等待中", running: "运行中", completed: "已完成", failed: "失败", cancelled: "已取消", retrying: "重试中", skipped: "已跳过", enabled: "已启用", disabled: "已停用" };
const triggerTypeText: Record<string, string> = { manual: "手动", scheduled: "定时", webhook: "Webhook" };
const actionText: Record<ExecutionAction, string> = { run: "运行", cancel: "取消", retry: "重试", resume: "恢复" };
const triggerActionText: Record<TriggerAction, string> = { invoke: "立即运行", enable: "启用", disable: "停用", delete: "删除" };
const displayStatus = (value?: string) => value ? statusText[value] || `未知状态（${value}）` : "-";
const displayTriggerType = (value?: string) => value ? triggerTypeText[value] || `未知类型（${value}）` : "-";
const displayTriggerAction = (action: OperatorActionName) => triggerActionText[action as TriggerAction] || action;
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "-";
function asExecution(row: unknown): WorkflowExecution { return row as WorkflowExecution; }
function asTrigger(row: unknown): WorkflowTrigger { return row as WorkflowTrigger; }
function executionActions(execution: WorkflowExecution) { return (executionAvailability.value[execution.id] || []).filter((item) => ["run", "cancel", "retry", "resume"].includes(item.action) && item.allowed).map((item) => item.action as ExecutionAction); }
function executionActionAvailability(execution: WorkflowExecution, action: ExecutionAction) { return executionAvailability.value[execution.id]?.find((item) => item.action === action); }
function triggerActionAvailability(trigger: WorkflowTrigger, action: TriggerAction) { return triggerAvailability.value[trigger.id]?.find((item) => item.action === action); }
function triggerActionAllowed(trigger: WorkflowTrigger, action: TriggerAction) { return triggerActionAvailability(trigger, action)?.allowed === true; }
function triggerActionReason(trigger: WorkflowTrigger, action: TriggerAction) { return triggerActionAvailability(trigger, action)?.reason_code || "ACTION_NOT_AVAILABLE"; }
function lifecycleQuery(executionId?: string) { return { ...(selected.value ? { workflow_id: selected.value.id } : {}), ...(executionId ? { execution_id: executionId } : {}), source: "workflow-lifecycle" }; }
function focusExecution(execution: WorkflowExecution) { focusedExecutionId.value = execution.id; diagnosticTraceId.value = ""; diagnosticAuditId.value = ""; void router.replace({ path: "/workflows/lifecycle", query: lifecycleQuery(execution.id) }); }
function openRuntimeExecution(execution: WorkflowExecution) { focusedExecutionId.value = execution.id; void router.push({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: execution.id, workflow_id: execution.workflow_id, workflow_version_id: execution.workflow_version_id } }); }
function openRuntimeCorrelations(execution: WorkflowExecution, focus?: DiagnosticFocus, focusId?: string) { focusedExecutionId.value = execution.id; const query: Record<string, string> = { tab: "correlations", source: "workflow-lifecycle", focus_type: focus ?? "execution", focus_id: focusId ?? execution.id, execution_id: execution.id, workflow_id: execution.workflow_id, workflow_version_id: execution.workflow_version_id }; void router.push({ path: "/runtime", query }); }
function continueDiagnostic() { if (!focusedExecution.value || !diagnosticFocus.value || !diagnosticFocusId.value) return; openRuntimeCorrelations(focusedExecution.value, diagnosticFocus.value, diagnosticFocusId.value); }
function clearDiagnosticContext() { diagnosticTraceId.value = ""; diagnosticAuditId.value = ""; void router.replace({ path: "/workflows/lifecycle", query: lifecycleQuery(focusedExecutionId.value || undefined) }); }
function openScheduledExecution(executionId?: string | null) { if (!executionId) return; const execution = executions.value.find((item) => item.id === executionId); if (execution) return openRuntimeExecution(execution); void router.push({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: executionId, ...(selected.value ? { workflow_id: selected.value.id } : {}) } }); }
function operatorErrorMessage(error: any, resource: "Execution" | "触发器", action?: string) { const status = error?.response?.status; const detail = String(error?.response?.data?.detail || error?.message || ""); if (status === 403) return `当前账号没有操作该${resource}的权限。`; if (status === 409) return /Idempotency|幂等|replay|处理中|结果/i.test(detail) ? `${resource}${action ? ` ${action}` : ""}发生幂等冲突或已有结果，请查看后端 Result Resource。` : `${resource}当前状态已变化，请刷新后重试。`; return `${resource}${action ? ` ${action}` : ""}失败，请稍后重试。`; }
async function load() { loading.value = true; pageState.value = "loading"; error.value = ""; permissionDenied.value = false; try { workflows.value = (await workflowApi.list()).data; const requestedId = typeof route.query.workflow_id === "string" ? route.query.workflow_id : ""; if (requestedId && workflows.value.some((item) => item.id === requestedId)) selectedId.value = requestedId; else if (!selectedId.value || !workflows.value.some((item) => item.id === selectedId.value)) selectedId.value = workflows.value[0]?.id || ""; if (!workflows.value.length) { selectedId.value = ""; pageState.value = "empty"; return; } if (selectedId.value) await loadDetails(selectedId.value); pageState.value = "success"; } catch (e: any) { workflows.value = []; permissionDenied.value = e?.response?.status === 403; error.value = permissionDenied.value ? "" : "工作流生命周期数据加载失败，请刷新后重试。"; pageState.value = permissionDenied.value ? "permission" : "error"; } finally { loading.value = false; } }
async function loadDetails(id: string) { detailLoading.value = true; detailError.value = ""; try { const [versionResponse, triggerResponse, executionResponse] = await Promise.all([workflowApi.versions(id), workflowApi.triggers(id), workflowApi.listExecutions(id)]); versions.value = versionResponse.data; triggers.value = triggerResponse.data; executions.value = executionResponse.data; const executionResults = await Promise.all(executions.value.map(async (execution) => [execution.id, (await workflowApi.executionAvailability(execution.id)).data.actions] as const)); const triggerResults = await Promise.all(triggers.value.map(async (trigger) => [trigger.id, (await workflowApi.triggerAvailability(trigger.id)).data.actions] as const)); executionAvailability.value = Object.fromEntries(executionResults); triggerAvailability.value = Object.fromEntries(triggerResults); const scheduled = triggers.value.filter((item) => item.trigger_type === "scheduled"); const results = await Promise.all(scheduled.map(async (trigger) => [trigger.id, (await workflowApi.schedule(id, trigger.id)).data] as const)); schedules.value = Object.fromEntries(results); const requestedExecutionId = typeof route.query.execution_id === "string" ? route.query.execution_id : ""; if (requestedExecutionId && executions.value.some((item) => item.id === requestedExecutionId)) focusedExecutionId.value = requestedExecutionId; else if (!focusedExecutionId.value || !executions.value.some((item) => item.id === focusedExecutionId.value)) focusedExecutionId.value = executions.value[0]?.id || ""; } catch (e: any) { versions.value = []; triggers.value = []; executions.value = []; schedules.value = {}; executionAvailability.value = {}; triggerAvailability.value = {}; if (e?.response?.status === 403) { permissionDenied.value = true; detailError.value = "当前账号没有读取工作流 Operator Action 可用性的权限。"; } else detailError.value = "无法同步当前工作流的版本、触发器、运行数据或 Operator Action 可用性。请重试；若持续失败，请检查服务状态。"; } finally { detailLoading.value = false; } }
async function selectWorkflow(id: string) { selectedId.value = id; focusedExecutionId.value = ""; diagnosticTraceId.value = ""; diagnosticAuditId.value = ""; await loadDetails(id); }
function handleStateAction() { if (pageState.value === "error" || pageState.value === "permission") void load(); }
function retryDetails() { if (selectedId.value) void loadDetails(selectedId.value); }
function requestInvoke(trigger: WorkflowTrigger) { const availability = triggerActionAvailability(trigger, "invoke"); if (!availability || !availability.allowed) { ElMessage.warning(`后端禁止当前 Trigger 执行：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); return; } invokeTarget.value = trigger; invokeDialogVisible.value = true; }
function cancelInvoke() { if (invokeLoading.value) return; invokeDialogVisible.value = false; invokeTarget.value = null; }
async function confirmInvoke() { if (!selectedId.value || !invokeTarget.value || invokeLoading.value) return; const target = invokeTarget.value; const availability = triggerActionAvailability(target, "invoke"); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该操作：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); cancelInvoke(); return; } invokeLoading.value = true; try { const response = await workflowApi.invokeTrigger(selectedId.value, target.id, {}); ElMessage.success(`手动触发已提交，Result Resource ${response.data.id} 已返回；重复幂等请求由后端复用既有结果。`); invokeDialogVisible.value = false; invokeTarget.value = null; await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", "invoke")); } finally { invokeLoading.value = false; } }
function requestExecutionAction(execution: WorkflowExecution, action: ExecutionAction) { if (executionActionLoading.value) return; const availability = executionActionAvailability(execution, action); if (!availability?.allowed) { ElMessage.warning(`后端禁止当前 Execution ${actionText[action]}：${availability?.reason_code || "ACTION_NOT_ALLOWED"}`); return; } executionTarget.value = execution; executionAction.value = action; executionDialogVisible.value = true; }
function cancelExecutionAction() { if (executionActionLoading.value) return; executionDialogVisible.value = false; executionTarget.value = null; executionAction.value = null; }
async function confirmExecutionAction() { if (!executionTarget.value || !executionAction.value || executionActionLoading.value) return; const target = executionTarget.value; const action = executionAction.value; const availability = executionActionAvailability(target, action); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该操作：${availability?.reason_code || "ACTION_NOT_ALLOWED"}`); cancelExecutionAction(); return; } executionActionLoading.value = true; try { let response; if (action === "run") response = await workflowApi.runExecution(target.id); else if (action === "cancel") response = await workflowApi.cancelExecution(target.id); else if (action === "retry") response = await workflowApi.retryExecution(target.id); else response = await workflowApi.resumeExecution(target.id); const result = response.data; const replayHint = action === "retry" ? `Retry Result ${result.id}${result.retry_of_execution_id ? `，来源 ${result.retry_of_execution_id}` : ""}；相同幂等键由后端复用既有结果。` : action === "resume" ? `Resume Result ${result.id}${result.resume_of_execution_id ? `，来源 ${result.resume_of_execution_id}` : ""}。` : `Result Resource ${result.id} 已返回。`; ElMessage.success(`Execution ${actionText[action]}已提交；${replayHint}`); executionDialogVisible.value = false; executionTarget.value = null; executionAction.value = null; await loadDetails(selectedId.value || target.workflow_id); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "Execution", action)); } finally { executionActionLoading.value = false; } }
function openTriggerEditor(trigger: WorkflowTrigger) { if (selected.value?.status === "archived") return; triggerEditor.value = { trigger, name: trigger.name, timezone: (trigger.config as any)?.timezone || "UTC", interval_seconds: (trigger.config as any)?.interval_seconds || 300, misfire_policy: (trigger.config as any)?.misfire_policy || "skip", catch_up_limit: (trigger.config as any)?.catch_up_limit || 10, event_id_field: (trigger.config as any)?.event_id_field || "event_id", secret: "" }; triggerEditorVisible.value = true; }
function cancelTriggerEditor() { if (triggerEditorLoading.value) return; triggerEditorVisible.value = false; triggerEditor.value = { trigger: null, name: "", timezone: "UTC", interval_seconds: 300, misfire_policy: "skip", catch_up_limit: 10, event_id_field: "event_id", secret: "" }; }
async function saveTriggerEditor() { if (!selectedId.value || !triggerEditor.value.trigger || triggerEditorLoading.value) return; const target = triggerEditor.value.trigger; triggerEditorLoading.value = true; try { const payload = target.trigger_type === "scheduled" ? { name: triggerEditor.value.name, config: { timezone: triggerEditor.value.timezone, interval_seconds: triggerEditor.value.interval_seconds, misfire_policy: triggerEditor.value.misfire_policy, catch_up_limit: triggerEditor.value.catch_up_limit } } : { name: triggerEditor.value.name, config: { auth_mode: "secret" as const, event_id_field: triggerEditor.value.event_id_field, ...(triggerEditor.value.secret ? { secret: triggerEditor.value.secret } : {}) } }; await workflowApi.updateTrigger(selectedId.value, target.id, payload); ElMessage.success("触发器配置已保存。已保留后端已存储的 Secret，不会回显敏感信息。"); cancelTriggerEditor(); await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", "保存")); } finally { triggerEditorLoading.value = false; } }
function requestDeleteTrigger(trigger: WorkflowTrigger) { const availability = triggerActionAvailability(trigger, "delete"); if (!availability || !availability.allowed) { ElMessage.warning(`后端禁止删除当前 Trigger：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); return; } deleteTriggerTarget.value = trigger; deleteTriggerDialogVisible.value = true; }
function cancelDeleteTrigger() { if (deleteTriggerLoading.value) return; deleteTriggerDialogVisible.value = false; deleteTriggerTarget.value = null; }
async function confirmDeleteTrigger() { if (!selectedId.value || !deleteTriggerTarget.value || deleteTriggerLoading.value) return; const target = deleteTriggerTarget.value; const availability = triggerActionAvailability(target, "delete"); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该删除操作：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); cancelDeleteTrigger(); return; } deleteTriggerLoading.value = true; try { await workflowApi.deleteTrigger(selectedId.value, target.id); ElMessage.success("触发器已删除。"); cancelDeleteTrigger(); await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", "删除")); } finally { deleteTriggerLoading.value = false; } }
function requestTriggerStatusAction(trigger: WorkflowTrigger, action: "enable" | "disable") { const availability = triggerActionAvailability(trigger, action); if (!availability || !availability.allowed) { ElMessage.warning(`后端禁止当前 Trigger ${action === "enable" ? "启用" : "停用"}：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); return; } triggerActionTarget.value = trigger; triggerAction.value = action; triggerActionDialogVisible.value = true; }
function cancelTriggerStatusAction() { if (triggerActionLoading.value) return; triggerActionDialogVisible.value = false; triggerActionTarget.value = null; triggerAction.value = null; }
async function confirmTriggerStatusAction() { if (!selectedId.value || !triggerActionTarget.value || !triggerAction.value || triggerActionLoading.value) return; const target = triggerActionTarget.value; const action = triggerAction.value; const availability = triggerActionAvailability(target, action); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该操作：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); cancelTriggerStatusAction(); return; } triggerActionLoading.value = true; try { if (action === "enable") await workflowApi.enableTrigger(selectedId.value, target.id); else await workflowApi.disableTrigger(selectedId.value, target.id); ElMessage.success(`触发器已${action === "enable" ? "启用" : "停用"}。`); cancelTriggerStatusAction(); await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", action === "enable" ? "启用" : "停用")); } finally { triggerActionLoading.value = false; } }
onMounted(() => { void load(); });
</script>

<template>
  <div class="workflow-lifecycle-page">
    <PageHeader title="工作流生命周期" description="围绕 Workflow → Version → Trigger → Execution 建立真实后端状态与可观测操作链路。" />
    <StatePanel v-if="pageState !== 'success'" :state="pageState" :title="stateTitle" :description="stateDescription" action-label="重新加载" @action="handleStateAction" />
    <template v-else>
      <SurfaceCard title="工作流" description="选择工作流查看版本、触发器、Execution 与诊断上下文。">
        <el-select v-model="selectedId" placeholder="选择工作流" style="width: 100%; max-width: 520px" @change="selectWorkflow"><el-option v-for="item in workflows" :key="item.id" :label="item.name" :value="item.id" /></el-select>
      </SurfaceCard>
      <SurfaceCard v-if="selected" title="生命周期" :description="selected.description || '工作流生命周期状态由后端真实资源驱动。'"><div class="lifecycle-steps"><div v-for="step in lifecycleSteps" :key="step.label" class="lifecycle-step" :class="{ done: step.done, active: step.active }"><span class="step-dot" /> <span>{{ step.label }}</span></div></div></SurfaceCard>
      <SurfaceCard title="版本" description="仅展示后端 Workflow Version 与发布状态。"><el-table v-if="versions.length" :data="versions" border><el-table-column prop="version" label="版本" width="100" /><el-table-column prop="status" label="状态" width="120"><template #default="{ row }">{{ displayStatus(row.status) }}</template></el-table-column><el-table-column prop="created_at" label="创建时间" min-width="200"><template #default="{ row }">{{ formatTime(row.created_at) }}</template></el-table-column></el-table><StatePanel v-else state="empty" title="暂无版本" description="当前工作流尚未创建版本。" /></SurfaceCard>
      <SurfaceCard class="trigger-card" title="触发与调度" description="Trigger 配置写入与 Operator Action 均使用真实后端 Contract；Scheduler 目前仍保持只读"><el-table v-if="triggers.length" :data="triggers" border><el-table-column prop="name" label="触发器" min-width="180" /><el-table-column label="类型" width="110"><template #default="{ row }">{{ displayTriggerType(row.trigger_type) }}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="row.status === 'enabled' ? 'success' : 'info'">{{ displayStatus(row.status) }}</el-tag></template></el-table-column><el-table-column label="可用性" min-width="220"><template #default="{ row }"><div class="availability-summary"><el-tag v-for="item in triggerAvailability[row.id] || []" :key="item.action" size="small" :type="item.allowed ? 'success' : 'info'" effect="plain">{{ displayTriggerAction(item.action) }}：{{ item.allowed ? '可用' : item.reason_code }}</el-tag></div></template></el-table-column><el-table-column label="下次运行" min-width="180"><template #default="{ row }">{{ row.trigger_type === 'scheduled' ? formatTime(schedules[row.id]?.next_run_at) : '-' }}</template></el-table-column><el-table-column label="最近运行" min-width="180"><template #default="{ row }">{{ row.trigger_type === 'scheduled' ? formatTime(schedules[row.id]?.last_run_at) : '-' }}</template></el-table-column><el-table-column label="最近 Execution" min-width="220"><template #default="{ row }"><el-button v-if="schedules[row.id]?.last_execution_id" link type="primary" @click="openScheduledExecution(schedules[row.id]?.last_execution_id)">{{ schedules[row.id]?.last_execution_id }}</el-button><span v-else>-</span></template></el-table-column><el-table-column label="操作" min-width="380" fixed="right"><template #default="{ row }"><el-button v-if="row.trigger_type === 'manual'" size="small" type="primary" link :disabled="!triggerActionAllowed(asTrigger(row), 'invoke')" @click="requestInvoke(asTrigger(row))">立即运行</el-button><el-button v-if="row.status === 'disabled'" size="small" type="success" link :disabled="!triggerActionAllowed(asTrigger(row), 'enable')" @click="requestTriggerStatusAction(asTrigger(row), 'enable')">启用</el-button><el-button v-if="row.status === 'enabled'" size="small" type="warning" link :disabled="!triggerActionAllowed(asTrigger(row), 'disable')" @click="requestTriggerStatusAction(asTrigger(row), 'disable')">停用</el-button><template v-if="row.trigger_type !== 'manual'"><el-button size="small" type="primary" link :disabled="selected.status === 'archived'" @click="openTriggerEditor(asTrigger(row))">编辑配置</el-button></template><el-button size="small" type="danger" link :disabled="selected.status === 'archived' || !triggerActionAllowed(asTrigger(row), 'delete')" @click="requestDeleteTrigger(asTrigger(row))">删除</el-button></template></el-table-column></el-table><StatePanel v-else state="empty" title="暂无触发器" description="发布工作流后可配置手动、定时或 Webhook 入口。" /></SurfaceCard>
      <SurfaceCard title="Execution" description="运行操作严格消费后端 Operator Action Availability，不在前端复制状态机。"><el-table v-if="executions.length" :data="executions" border><el-table-column prop="id" label="Execution ID" min-width="260" /><el-table-column prop="status" label="状态" width="120"><template #default="{ row }">{{ displayStatus(row.status) }}</template></el-table-column><el-table-column label="操作" min-width="320"><template #default="{ row }"><el-button v-for="action in executionActions(asExecution(row))" :key="action" size="small" link type="primary" @click="requestExecutionAction(asExecution(row), action)">{{ actionText[action] }}</el-button><el-button size="small" link @click="focusExecution(asExecution(row))">查看上下文</el-button><el-button size="small" link @click="openRuntimeExecution(asExecution(row))">Runtime</el-button></template></el-table-column></el-table><StatePanel v-else state="empty" title="暂无 Execution" description="当前工作流尚无运行记录。" /></SurfaceCard>
      <SurfaceCard v-if="focusedExecution" title="诊断上下文" :description="diagnosticFocus ? `${diagnosticFocusLabel}：${diagnosticFocusId}` : '选择 Trace/Audit 深链后可继续进入 Runtime Correlations。'"><div class="diagnostic-actions"><el-button v-if="diagnosticFocus" type="primary" @click="continueDiagnostic">继续诊断</el-button><el-button v-if="diagnosticFocus" @click="clearDiagnosticContext">清除诊断上下文</el-button><el-button @click="openRuntimeCorrelations(focusedExecution)">查看 Execution Correlations</el-button></div></SurfaceCard>
      <StatePanel v-if="detailError" state="error" title="工作流详情同步失败" :description="detailError" action-label="重新加载详情" @action="retryDetails" />
    </template>
    <ConfirmDialog v-model="invokeDialogVisible" title="确认立即运行" :loading="invokeLoading" confirm-text="确认运行" @confirm="confirmInvoke" @cancel="cancelInvoke"><p>将通过真实后端 Operator Action 提交手动触发。</p></ConfirmDialog>
    <ConfirmDialog v-model="executionDialogVisible" :title="`确认${executionAction ? actionText[executionAction] : '操作'} Execution`" :loading="executionActionLoading" :confirm-text="`确认${executionAction ? actionText[executionAction] : '操作'}`" @confirm="confirmExecutionAction" @cancel="cancelExecutionAction"><p>该操作由后端 Operator Action Availability 授权并记录执行结果。</p></ConfirmDialog>
    <ConfirmDialog v-model="deleteTriggerDialogVisible" title="确认删除触发器" :loading="deleteTriggerLoading" confirm-text="确认删除" @confirm="confirmDeleteTrigger" @cancel="cancelDeleteTrigger"><p>删除后该 Trigger 将不再作为当前 Workflow 的入口。请确认后继续。</p></ConfirmDialog>
    <ConfirmDialog v-model="triggerActionDialogVisible" :title="`确认${triggerAction === 'enable' ? '启用' : '停用'}触发器`" :loading="triggerActionLoading" :confirm-text="`确认${triggerAction === 'enable' ? '启用' : '停用'}`" @confirm="confirmTriggerStatusAction" @cancel="cancelTriggerStatusAction"><p>该状态变更由后端 Operator Action 执行。</p></ConfirmDialog>
    <el-dialog v-model="triggerEditorVisible" title="编辑触发器配置" width="560px"><el-form label-width="120px"><el-form-item label="名称"><el-input v-model="triggerEditor.name" /></el-form-item><template v-if="triggerEditor.trigger?.trigger_type === 'scheduled'"><el-form-item label="时区"><el-input v-model="triggerEditor.timezone" /></el-form-item><el-form-item label="间隔秒数"><el-input-number v-model="triggerEditor.interval_seconds" :min="1" /></el-form-item><el-form-item label="错过策略"><el-select v-model="triggerEditor.misfire_policy"><el-option label="跳过" value="skip" /><el-option label="执行一次" value="fire_once" /><el-option label="追赶" value="catch_up" /></el-select></el-form-item><el-form-item label="追赶上限"><el-input-number v-model="triggerEditor.catch_up_limit" :min="1" /></el-form-item></template><template v-else><el-form-item label="事件 ID 字段"><el-input v-model="triggerEditor.event_id_field" /></el-form-item><el-form-item label="Secret"><el-input v-model="triggerEditor.secret" type="password" show-password placeholder="留空表示保留现有 Secret" /></el-form-item></template></el-form><template #footer><el-button @click="cancelTriggerEditor">取消</el-button><el-button type="primary" :loading="triggerEditorLoading" @click="saveTriggerEditor">保存</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.workflow-lifecycle-page { display: grid; gap: 16px; }
.lifecycle-steps { display: flex; gap: 18px; flex-wrap: wrap; }
.lifecycle-step { display: inline-flex; align-items: center; gap: 8px; color: var(--el-text-color-secondary); }
.lifecycle-step.done { color: var(--el-text-color-primary); }
.lifecycle-step.active { font-weight: 600; }
.step-dot { width: 8px; height: 8px; border-radius: 50%; background: var(--el-border-color); }
.lifecycle-step.done .step-dot { background: var(--el-color-success); }
.lifecycle-step.active .step-dot { background: var(--el-color-primary); }
.availability-summary { display: flex; gap: 6px; flex-wrap: wrap; }
.diagnostic-actions { display: flex; gap: 8px; flex-wrap: wrap; }
@media (max-width: 900px) { .workflow-lifecycle-page :deep(.el-table) { font-size: 12px; } }
</style>
