<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElMessage } from "element-plus";
import { workflowApi, type Workflow, type WorkflowExecution, type WorkflowTrigger, type SchedulerStatus, type WorkflowVersion, type ScheduledMisfirePolicy, type OperatorActionAvailability } from "@/api/workflows";
import PageHeader from "@/components/ui/PageHeader.vue";
import SurfaceCard from "@/components/ui/SurfaceCard.vue";
import StatePanel from "@/components/ui/StatePanel.vue";
import ConfirmDialog from "@/components/ui/ConfirmDialog.vue";

type PageState = "loading" | "empty" | "error" | "permission" | "success";
type ExecutionAction = "run" | "cancel" | "retry" | "resume";
type TriggerAction = "invoke" | "enable" | "disable" | "delete";
type DiagnosticFocus = "trace" | "audit";
type TriggerEditor = { trigger: WorkflowTrigger | null; name: string; timezone: string; interval_seconds: number; misfire_policy: ScheduledMisfirePolicy; catch_up_limit: number; event_id_field: string; secret: string };
const route = useRoute();
const router = useRouter();
const workflows = ref<Workflow[]>([]);
const versions = ref<WorkflowVersion[]>([]);
const triggers = ref<WorkflowTrigger[]>([]);
const schedules = ref<Record<string, SchedulerStatus>>({});
const executions = ref<WorkflowExecution[]>([]);
const executionAvailability = ref<Record<string, OperatorActionAvailability[]>>({});
const triggerAvailability = ref<Record<string, OperatorActionAvailability[]>>({});
const selectedId = ref(typeof route.query.workflow_id === "string" ? route.query.workflow_id : "");
const focusedExecutionId = ref(typeof route.query.execution_id === "string" ? route.query.execution_id : "");
const diagnosticTraceId = ref(typeof route.query.trace_id === "string" ? route.query.trace_id : "");
const diagnosticAuditId = ref(typeof route.query.audit_id === "string" ? route.query.audit_id : "");
const loading = ref(false); const detailLoading = ref(false); const error = ref(""); const detailError = ref(""); const permissionDenied = ref(false); const pageState = ref<PageState>("loading");
const invokeDialogVisible = ref(false); const invokeLoading = ref(false); const invokeTarget = ref<WorkflowTrigger | null>(null);
const executionDialogVisible = ref(false); const executionActionLoading = ref(false); const executionAction = ref<ExecutionAction | null>(null); const executionTarget = ref<WorkflowExecution | null>(null);
const triggerEditorVisible = ref(false); const triggerEditorLoading = ref(false); const triggerEditor = ref<TriggerEditor>({ trigger: null, name: "", timezone: "UTC", interval_seconds: 300, misfire_policy: "skip", catch_up_limit: 10, event_id_field: "event_id", secret: "" });
const deleteTriggerDialogVisible = ref(false); const deleteTriggerLoading = ref(false); const deleteTriggerTarget = ref<WorkflowTrigger | null>(null);
const triggerActionDialogVisible = ref(false); const triggerActionLoading = ref(false); const triggerAction = ref<Exclude<TriggerAction, "invoke" | "delete"> | null>(null); const triggerActionTarget = ref<WorkflowTrigger | null>(null);

const selected = computed(() => workflows.value.find((item) => item.id === selectedId.value));
const publishedVersion = computed(() => versions.value.find((item) => item.id === selected.value?.published_version_id));
const focusedExecution = computed(() => executions.value.find((item) => item.id === focusedExecutionId.value));
const diagnosticFocus = computed<DiagnosticFocus | null>(() => diagnosticTraceId.value ? "trace" : diagnosticAuditId.value ? "audit" : null);
const diagnosticFocusId = computed(() => diagnosticTraceId.value || diagnosticAuditId.value);
const diagnosticFocusLabel = computed(() => diagnosticFocus.value === "trace" ? "Trace ID" : diagnosticFocus.value === "audit" ? "Audit ID" : "诊断上下文");
const stateTitle = computed(() => ({ loading: "正在加载工作流", empty: "暂无工作流", permission: "无权查看工作流", error: "工作流加载失败" } as Record<string, string>)[pageState.value] ?? "工作流");
const stateDescription = computed(() => ({ loading: "正在同步工作流生命周期数据。", empty: "当前没有可用工作流，请先创建工作流。", permission: "当前账号没有工作流访问权限，请联系管理员。", error: "无法同步工作流数据，请检查服务状态后重试。" } as Record<string, string>)[pageState.value] ?? "");
const lifecycleSteps = computed(() => [
  { label: "工作流", done: Boolean(selected.value), active: false },
  { label: "版本", done: Boolean(publishedVersion.value), active: Boolean(selected.value) && !publishedVersion.value },
  { label: "发布", done: selected.value?.status === "published", active: Boolean(publishedVersion.value) && selected.value?.status !== "published" },
  { label: "触发器", done: triggers.value.length > 0, active: selected.value?.status === "published" && triggers.value.length === 0 },
  { label: "运行", done: executions.value.length > 0, active: selected.value?.status === "published" && executions.value.length === 0 },
]);
const statusText: Record<string, string> = { draft: "草稿", published: "已发布", archived: "已归档", pending: "等待中", running: "运行中", completed: "已完成", failed: "失败", cancelled: "已取消", retrying: "重试中", skipped: "已跳过", enabled: "已启用", disabled: "已停用" };
const triggerTypeText: Record<string, string> = { manual: "手动", scheduled: "定时", webhook: "Webhook" };
const actionText: Record<ExecutionAction, string> = { run: "运行", cancel: "取消", retry: "重试", resume: "恢复" };
const triggerActionText: Record<TriggerAction, string> = { invoke: "立即运行", enable: "启用", disable: "停用", delete: "删除" };
const displayStatus = (value?: string) => value ? statusText[value] || `未知状态（${value}）` : "-";
const displayTriggerType = (value?: string) => value ? triggerTypeText[value] || `未知类型（${value}）` : "-";
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "-";
function asExecution(row: unknown): WorkflowExecution { return row as WorkflowExecution; }
function asTrigger(row: unknown): WorkflowTrigger { return row as WorkflowTrigger; }
function executionActions(execution: WorkflowExecution) { return (executionAvailability.value[execution.id] || []).filter((item) => ["run", "cancel", "retry", "resume"].includes(item.action) && item.allowed).map((item) => item.action as ExecutionAction); }
function executionActionAvailability(execution: WorkflowExecution, action: ExecutionAction) { return executionAvailability.value[execution.id]?.find((item) => item.action === action); }
function triggerActionAvailability(trigger: WorkflowTrigger, action: TriggerAction) { return triggerAvailability.value[trigger.id]?.find((item) => item.action === action); }
function triggerActionAllowed(trigger: WorkflowTrigger, action: TriggerAction) { return triggerActionAvailability(trigger, action)?.allowed === true; }
function triggerActionReason(trigger: WorkflowTrigger, action: TriggerAction) { return triggerActionAvailability(trigger, action)?.reason_code || "ACTION_NOT_AVAILABLE"; }
function lifecycleQuery(executionId?: string) { return { ...(selected.value ? { workflow_id: selected.value.id } : {}), ...(executionId ? { execution_id: executionId } : {}), source: "workflow-lifecycle" }; }
function focusExecution(execution: WorkflowExecution) { focusedExecutionId.value = execution.id; diagnosticTraceId.value = ""; diagnosticAuditId.value = ""; void router.replace({ path: "/workflows/lifecycle", query: lifecycleQuery(execution.id) }); }
function openRuntimeExecution(execution: WorkflowExecution) { focusedExecutionId.value = execution.id; void router.push({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: execution.id, workflow_id: execution.workflow_id, workflow_version_id: execution.workflow_version_id } }); }
function openRuntimeCorrelations(execution: WorkflowExecution, focus?: DiagnosticFocus, focusId?: string) { focusedExecutionId.value = execution.id; const query: Record<string, string> = { tab: "correlations", source: "workflow-lifecycle", focus_type: focus ?? "execution", focus_id: focusId ?? execution.id, execution_id: execution.id, workflow_id: execution.workflow_id, workflow_version_id: execution.workflow_version_id }; void router.push({ path: "/runtime", query }); }
function continueDiagnostic() { if (!focusedExecution.value || !diagnosticFocus.value || !diagnosticFocusId.value) return; openRuntimeCorrelations(focusedExecution.value, diagnosticFocus.value, diagnosticFocusId.value); }
function clearDiagnosticContext() { diagnosticTraceId.value = ""; diagnosticAuditId.value = ""; void router.replace({ path: "/workflows/lifecycle", query: lifecycleQuery(focusedExecutionId.value || undefined) }); }
function openScheduledExecution(executionId?: string | null) { if (!executionId) return; const execution = executions.value.find((item) => item.id === executionId); if (execution) return openRuntimeExecution(execution); void router.push({ path: "/runtime", query: { tab: "executions", source: "workflow-lifecycle", execution_id: executionId, ...(selected.value ? { workflow_id: selected.value.id } : {}) } }); }
function operatorErrorMessage(error: any, resource: "Execution" | "触发器", action?: string) { const status = error?.response?.status; const detail = String(error?.response?.data?.detail || error?.message || ""); if (status === 403) return `当前账号没有操作该${resource}的权限。`; if (status === 409) return /Idempotency|幂等|replay|处理中|结果/i.test(detail) ? `${resource}${action ? ` ${action}` : ""}发生幂等冲突或已有结果，请查看后端 Result Resource。` : `${resource}当前状态已变化，请刷新后重试。`; return `${resource}${action ? ` ${action}` : ""}失败，请稍后重试。`; }
async function load() { loading.value = true; pageState.value = "loading"; error.value = ""; permissionDenied.value = false; try { workflows.value = (await workflowApi.list()).data; const requestedId = typeof route.query.workflow_id === "string" ? route.query.workflow_id : ""; if (requestedId && workflows.value.some((item) => item.id === requestedId)) selectedId.value = requestedId; else if (!selectedId.value || !workflows.value.some((item) => item.id === selectedId.value)) selectedId.value = workflows.value[0]?.id || ""; if (!workflows.value.length) { selectedId.value = ""; pageState.value = "empty"; return; } if (selectedId.value) await loadDetails(selectedId.value); pageState.value = "success"; } catch (e: any) { workflows.value = []; permissionDenied.value = e?.response?.status === 403; error.value = permissionDenied.value ? "" : "工作流生命周期数据加载失败，请刷新后重试。"; pageState.value = permissionDenied.value ? "permission" : "error"; } finally { loading.value = false; } }
async function loadDetails(id: string) { detailLoading.value = true; detailError.value = ""; try { const [versionResponse, triggerResponse, executionResponse] = await Promise.all([workflowApi.versions(id), workflowApi.triggers(id), workflowApi.listExecutions(id)]); versions.value = versionResponse.data; triggers.value = triggerResponse.data; executions.value = executionResponse.data; const executionResults = await Promise.all(executions.value.map(async (execution) => [execution.id, (await workflowApi.executionAvailability(execution.id)).data.actions] as const)); const triggerResults = await Promise.all(triggers.value.map(async (trigger) => [trigger.id, (await workflowApi.triggerAvailability(trigger.id)).data.actions] as const)); executionAvailability.value = Object.fromEntries(executionResults); triggerAvailability.value = Object.fromEntries(triggerResults); const scheduled = triggers.value.filter((item) => item.trigger_type === "scheduled"); const results = await Promise.all(scheduled.map(async (trigger) => [trigger.id, (await workflowApi.schedule(id, trigger.id)).data] as const)); schedules.value = Object.fromEntries(results); const requestedExecutionId = typeof route.query.execution_id === "string" ? route.query.execution_id : ""; if (requestedExecutionId && executions.value.some((item) => item.id === requestedExecutionId)) focusedExecutionId.value = requestedExecutionId; else if (!focusedExecutionId.value || !executions.value.some((item) => item.id === focusedExecutionId.value)) focusedExecutionId.value = executions.value[0]?.id || ""; } catch (e: any) { versions.value = []; triggers.value = []; executions.value = []; schedules.value = {}; executionAvailability.value = {}; triggerAvailability.value = {}; if (e?.response?.status === 403) { permissionDenied.value = true; detailError.value = "当前账号没有读取工作流 Operator Action 可用性的权限。"; } else detailError.value = "无法同步当前工作流的版本、触发器、运行数据或 Operator Action 可用性。请重试；若持续失败，请检查服务状态。"; } finally { detailLoading.value = false; } }
async function selectWorkflow(id: string) { selectedId.value = id; focusedExecutionId.value = ""; diagnosticTraceId.value = ""; diagnosticAuditId.value = ""; await loadDetails(id); }
function handleStateAction() { if (pageState.value === "error" || pageState.value === "permission") void load(); }
function retryDetails() { if (selectedId.value) void loadDetails(selectedId.value); }
function requestInvoke(trigger: WorkflowTrigger) { const availability = triggerActionAvailability(trigger, "invoke"); if (!availability || !availability.allowed) { ElMessage.warning(`后端禁止当前 Trigger 执行：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); return; } invokeTarget.value = trigger; invokeDialogVisible.value = true; }
function cancelInvoke() { if (invokeLoading.value) return; invokeDialogVisible.value = false; invokeTarget.value = null; }
async function confirmInvoke() { if (!selectedId.value || !invokeTarget.value || invokeLoading.value) return; const target = invokeTarget.value; const availability = triggerActionAvailability(target, "invoke"); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该操作：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); cancelInvoke(); return; } invokeLoading.value = true; try { const response = await workflowApi.invokeTrigger(selectedId.value, target.id, {}); ElMessage.success(`手动触发已提交，Result Resource ${response.data.id} 已返回；重复幂等请求由后端复用既有结果。`); invokeDialogVisible.value = false; invokeTarget.value = null; await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", "invoke")); } finally { invokeLoading.value = false; } }
function requestExecutionAction(execution: WorkflowExecution, action: ExecutionAction) { if (executionActionLoading.value) return; const availability = executionActionAvailability(execution, action); if (!availability?.allowed) { ElMessage.warning(`后端禁止当前 Execution ${actionText[action]}：${availability?.reason_code || "ACTION_NOT_ALLOWED"}`); return; } executionTarget.value = execution; executionAction.value = action; executionDialogVisible.value = true; }
function cancelExecutionAction() { if (executionActionLoading.value) return; executionDialogVisible.value = false; executionTarget.value = null; executionAction.value = null; }
async function confirmExecutionAction() { if (!executionTarget.value || !executionAction.value || executionActionLoading.value) return; const target = executionTarget.value; const action = executionAction.value; const availability = executionActionAvailability(target, action); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该操作：${availability?.reason_code || "ACTION_NOT_ALLOWED"}`); cancelExecutionAction(); return; } executionActionLoading.value = true; try { let response; if (action === "run") response = await workflowApi.runExecution(target.id); else if (action === "cancel") response = await workflowApi.cancelExecution(target.id); else if (action === "retry") response = await workflowApi.retryExecution(target.id); else response = await workflowApi.resumeExecution(target.id); const result = response.data; const replayHint = action === "retry" ? `Retry Result ${result.id}${result.retry_of_execution_id ? `，来源 ${result.retry_of_execution_id}` : ""}；相同幂等键由后端复用既有结果。` : action === "resume" ? `Resume Result ${result.id}${result.resume_checkpoint_sequence != null ? `，Checkpoint ${result.resume_checkpoint_sequence}` : ""}。` : `Result Resource ${result.id} 已返回。`; ElMessage.success(`${actionText[action]}操作成功，${replayHint}正在刷新 Backend Execution。`); executionDialogVisible.value = false; executionTarget.value = null; executionAction.value = null; await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "Execution", actionText[action])); } finally { executionActionLoading.value = false; } }
function openTriggerEditor(trigger: WorkflowTrigger) { if (selected.value?.status === "archived") return; const config = (trigger.config || {}) as Record<string, unknown>; if (trigger.trigger_type === "scheduled") triggerEditor.value = { trigger, name: trigger.name, timezone: String(config.timezone || "UTC"), interval_seconds: Number(config.interval_seconds || 300), misfire_policy: (config.misfire_policy as ScheduledMisfirePolicy) || "skip", catch_up_limit: Number(config.catch_up_limit || 10), event_id_field: "event_id", secret: "" }; else if (trigger.trigger_type === "webhook") triggerEditor.value = { trigger, name: trigger.name, timezone: "UTC", interval_seconds: 300, misfire_policy: "skip", catch_up_limit: 10, event_id_field: String(config.event_id_field || "event_id"), secret: "" }; else return; triggerEditorVisible.value = true; }
function cancelTriggerEditor() { if (triggerEditorLoading.value) return; triggerEditorVisible.value = false; triggerEditor.value.trigger = null; triggerEditor.value.secret = ""; }
async function saveTriggerEditor() { const editor = triggerEditor.value; const trigger = editor.trigger; if (!selectedId.value || !trigger || triggerEditorLoading.value) return; triggerEditorLoading.value = true; try { const config = trigger.trigger_type === "scheduled" ? { timezone: editor.timezone, interval_seconds: editor.interval_seconds, misfire_policy: editor.misfire_policy, catch_up_limit: editor.catch_up_limit } : { auth_mode: "secret" as const, event_id_field: editor.event_id_field, ...(editor.secret.trim() ? { secret: editor.secret.trim() } : {}) }; await workflowApi.updateTrigger(selectedId.value, trigger.id, { name: editor.name, config }); ElMessage.success("Trigger 配置已更新，正在刷新生命周期状态。"); triggerEditorVisible.value = false; editor.trigger = null; editor.secret = ""; await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", "update")); } finally { triggerEditorLoading.value = false; } }
function requestDeleteTrigger(trigger: WorkflowTrigger) { if (selected.value?.status === "archived" || deleteTriggerLoading.value) return; const availability = triggerActionAvailability(trigger, "delete"); if (!availability?.allowed) { ElMessage.warning(`后端禁止删除 Trigger：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); return; } deleteTriggerTarget.value = trigger; deleteTriggerDialogVisible.value = true; }
function cancelDeleteTrigger() { if (deleteTriggerLoading.value) return; deleteTriggerDialogVisible.value = false; deleteTriggerTarget.value = null; }
async function confirmDeleteTrigger() { const trigger = deleteTriggerTarget.value; if (!selectedId.value || !trigger || deleteTriggerLoading.value) return; const availability = triggerActionAvailability(trigger, "delete"); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝删除 Trigger：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); cancelDeleteTrigger(); return; } deleteTriggerLoading.value = true; try { await workflowApi.deleteTrigger(selectedId.value, trigger.id); ElMessage.success(`Trigger “${trigger.name}”已删除，正在刷新生命周期状态。`); deleteTriggerDialogVisible.value = false; deleteTriggerTarget.value = null; await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", "delete")); } finally { deleteTriggerLoading.value = false; } }
function requestTriggerStatusAction(trigger: WorkflowTrigger, action: "enable" | "disable") { if (selected.value?.status === "archived" || triggerActionLoading.value) return; const availability = triggerActionAvailability(trigger, action); if (!availability?.allowed) { ElMessage.warning(`后端禁止${triggerActionText[action]} Trigger：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); return; } triggerActionTarget.value = trigger; triggerAction.value = action; triggerActionDialogVisible.value = true; }
function cancelTriggerStatusAction() { if (triggerActionLoading.value) return; triggerActionDialogVisible.value = false; triggerActionTarget.value = null; triggerAction.value = null; }
async function confirmTriggerStatusAction() { const trigger = triggerActionTarget.value; const action = triggerAction.value; if (!selectedId.value || !trigger || !action || triggerActionLoading.value) return; const availability = triggerActionAvailability(trigger, action); if (!availability?.allowed) { ElMessage.warning(`后端已拒绝该操作：${availability?.reason_code || "ACTION_NOT_AVAILABLE"}`); cancelTriggerStatusAction(); return; } triggerActionLoading.value = true; try { if (action === "enable") await workflowApi.enableTrigger(selectedId.value, trigger.id); else await workflowApi.disableTrigger(selectedId.value, trigger.id); ElMessage.success(`Trigger “${trigger.name}”${action === "enable" ? "已启用" : "已停用"}，正在刷新 Backend Trigger / Availability。`); triggerActionDialogVisible.value = false; triggerActionTarget.value = null; triggerAction.value = null; await loadDetails(selectedId.value); } catch (e: any) { ElMessage.error(operatorErrorMessage(e, "触发器", triggerActionText[action])); } finally { triggerActionLoading.value = false; } }
const executionDialogTitle = computed(() => `确认${executionAction.value ? actionText[executionAction.value] : ""} Execution`);
const executionDialogDescription = computed(() => !executionTarget.value || !executionAction.value ? "请确认当前 Execution 操作。" : `将对 Execution “${executionTarget.value.id}”执行${actionText[executionAction.value]}操作。确认与幂等要求由 Backend Operator Action Availability Contract 决定，最终状态以 Backend refresh 为准，是否继续？`);
const triggerActionDialogTitle = computed(() => triggerAction.value ? `确认${triggerActionText[triggerAction.value]} Trigger` : "确认 Trigger 操作");
const triggerActionDialogDescription = computed(() => !triggerActionTarget.value || !triggerAction.value ? "请确认当前 Trigger 操作。" : `将对 Trigger “${triggerActionTarget.value.name}”执行${triggerActionText[triggerAction.value]}。Backend Availability reason_code：${triggerActionReason(triggerActionTarget.value, triggerAction.value)}。确认后将重新读取 Trigger 与 Availability。`);
const triggerEditorTitle = computed(() => triggerEditor.value.trigger?.trigger_type === "scheduled" ? "编辑定时 Trigger" : "编辑 Webhook Trigger");
const triggerEditorDescription = computed(() => triggerEditor.value.trigger?.trigger_type === "scheduled" ? "保存时调用真实 Trigger PATCH Contract；Scheduler 状态仍由后端只读查询返回。" : "保存时调用真实 Trigger PATCH Contract。Webhook Secret 只提交新 Secret，不读取或回显旧 Secret。");
onMounted(load);
</script>

<template>
  <main class="lifecycle-page" aria-label="工作流生命周期工作台">
    <PageHeader title="Workflow 生命周期工作台" description="把定义、版本、发布、触发器、调度与真实 Execution 串成一条可验证的运行链路。" eyebrow="P1 生命周期治理"><template #actions><el-button :loading="loading" @click="load">刷新</el-button></template></PageHeader>
    <StatePanel v-if="pageState !== 'success'" :state="pageState" :title="stateTitle" :description="stateDescription" :action-label="pageState === 'error' || pageState === 'permission' ? '重试' : undefined" @action="handleStateAction" />
    <template v-else-if="selected">
      <SurfaceCard class="workflow-selector"><div class="workflow-selector__row"><div class="workflow-identity"><strong>{{ selected.name }}</strong><span>工作流 ID：{{ selected.id }}</span></div><el-select :model-value="selectedId" placeholder="选择工作流" filterable @update:model-value="selectWorkflow"><el-option v-for="item in workflows" :key="item.id" :label="item.name" :value="item.id"></el-option></el-select><el-tag effect="plain">{{ displayStatus(selected.status) }}</el-tag></div></SurfaceCard>
      <section class="lifecycle-card" aria-label="生命周期阶段"><div v-for="(step, index) in lifecycleSteps" :key="step.label" class="step" :class="{ done: step.done, active: step.active }"><span class="step-index">{{ step.done ? "✓" : index + 1 }}</span><strong>{{ step.label }}</strong><span>{{ step.done ? "已完成" : step.active ? "当前关注" : "待进入" }}</span><i v-if="index < lifecycleSteps.length - 1">→</i></div></section>
      <StatePanel v-if="detailError" state="error" title="工作流详情加载失败" :description="detailError" action-label="重新加载" @action="retryDetails" />
      <template v-else-if="detailLoading"><StatePanel state="loading" title="正在加载工作流详情" description="正在同步版本、触发器、运行记录和 Operator Action Availability。" /></template>
      <template v-else>
        <div class="detail-grid">
          <SurfaceCard title="版本与发布" description="当前生效版本"><el-descriptions v-if="publishedVersion" :column="2" border><el-descriptions-item label="版本">v{{ publishedVersion.version }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag type="success">{{ displayStatus(publishedVersion.status) }}</el-tag></el-descriptions-item><el-descriptions-item label="版本标识">{{ publishedVersion.id }}</el-descriptions-item><el-descriptions-item label="发布时间">{{ formatTime(publishedVersion.created_at) }}</el-descriptions-item></el-descriptions><StatePanel v-else state="empty" title="尚未发布可生效版本" description="当前工作流暂无可展示的已发布版本。" /></SurfaceCard>
          <SurfaceCard title="运行记录" :description="`${executions.length} 条运行记录，操作权限与状态资格均来自 Backend Operator Action Availability`"><StatePanel v-if="!executions.length" state="empty" title="暂无运行记录" description="当前工作流还没有 Execution 运行记录。" /><el-table v-else :data="executions" row-key="id" border @row-click="(row) => focusExecution(asExecution(row))"><el-table-column label="Execution" min-width="230"><template #default="{ row }"><el-button link type="primary" @click.stop="focusExecution(asExecution(row))">{{ row.id }}</el-button><el-tag v-if="focusedExecutionId === row.id" type="success" effect="plain" class="focus-tag">已定位</el-tag></template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag>{{ displayStatus(row.status) }}</el-tag></template></el-table-column><el-table-column label="创建时间" min-width="180"><template #default="{ row }">{{ formatTime(row.created_at) }}</template></el-table-column><el-table-column label="当前节点" min-width="160"><template #default="{ row }">{{ row.current_node_id || '-' }}</template></el-table-column><el-table-column label="错误" min-width="190"><template #default="{ row }"><span v-if="row.error_code" class="error-code">{{ row.error_code }}</span><span v-else class="muted">-</span></template></el-table-column><el-table-column label="操作" min-width="310" fixed="right"><template #default="{ row }"><el-button v-for="action in executionActions(asExecution(row))" :key="action" size="small" :type="action === 'cancel' ? 'danger' : 'primary'" plain @click.stop="requestExecutionAction(asExecution(row), action)">{{ actionText[action] }}</el-button><el-button size="small" plain @click.stop="focusExecution(asExecution(row))">定位</el-button><el-button size="small" type="primary" plain @click.stop="openRuntimeExecution(asExecution(row))">Runtime</el-button><el-button size="small" plain @click.stop="openRuntimeCorrelations(asExecution(row))">Trace / Audit</el-button></template></el-table-column></el-table></SurfaceCard>
        </div>
        <SurfaceCard v-if="focusedExecution" class="execution-focus-card" title="当前 Execution 定位" description="所有诊断入口均以该 Execution ID 为关联根，不在前端推导 Trace / Audit 关系"><div class="focus-summary"><div><span>Execution ID</span><strong>{{ focusedExecution.id }}</strong></div><div><span>状态</span><el-tag>{{ displayStatus(focusedExecution.status) }}</el-tag></div><div><span>Workflow Version</span><strong>{{ focusedExecution.workflow_version_id }}</strong></div><div v-if="focusedExecution.retry_of_execution_id"><span>Retry 来源</span><strong>{{ focusedExecution.retry_of_execution_id }}</strong></div><div v-if="focusedExecution.resume_of_execution_id"><span>Resume 来源</span><strong>{{ focusedExecution.resume_of_execution_id }}</strong></div></div><div v-if="focusedExecution.error_message" class="error-message">{{ focusedExecution.error_message }}</div><div class="execution-actions"><el-button type="primary" @click="openRuntimeExecution(focusedExecution)">Runtime 诊断</el-button><el-button @click="openRuntimeCorrelations(focusedExecution)">Trace / Audit 关联</el-button></div></SurfaceCard>
        <SurfaceCard v-if="diagnosticFocus && focusedExecution" class="diagnostic-context-card" title="反向诊断上下文" description="该上下文由 Runtime correlation 返回的真实 ID 传入；继续诊断不会重新推导关联关系"><div class="diagnostic-context"><div><span>Execution ID</span><strong>{{ focusedExecution.id }}</strong></div><div><span>{{ diagnosticFocusLabel }}</span><strong>{{ diagnosticFocusId }}</strong></div><div><span>Workflow ID</span><strong>{{ focusedExecution.workflow_id }}</strong></div><div><span>Workflow Version</span><strong>{{ focusedExecution.workflow_version_id }}</strong></div></div><div class="execution-actions"><el-button type="primary" @click="continueDiagnostic">继续 {{ diagnosticFocus === 'trace' ? 'Trace' : 'Audit' }} 诊断</el-button><el-button plain @click="clearDiagnosticContext">清除诊断上下文</el-button></div></SurfaceCard>
        <SurfaceCard class="trigger-card" title="触发与调度" description="Trigger 配置写入与 Operator Action 均使用真实后端 Contract；Scheduler 目前仍保持只读"><el-table v-if="triggers.length" :data="triggers" border><el-table-column prop="name" label="触发器" min-width="180" /><el-table-column label="类型" width="110"><template #default="{ row }">{{ displayTriggerType(row.trigger_type) }}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="row.status === 'enabled' ? 'success' : 'info'">{{ displayStatus(row.status) }}</el-tag></template></el-table-column><el-table-column label="可用性" min-width="220"><template #default="{ row }"><div class="availability-summary"><el-tag v-for="item in triggerAvailability[row.id] || []" :key="item.action" size="small" :type="item.allowed ? 'success' : 'info'" effect="plain">{{ triggerActionText[item.action] || item.action }}：{{ item.allowed ? '可用' : item.reason_code }}</el-tag></div></template></el-table-column><el-table-column label="下次运行" min-width="180"><template #default="{ row }">{{ row.trigger_type === 'scheduled' ? formatTime(schedules[row.id]?.next_run_at) : '-' }}</template></el-table-column><el-table-column label="最近运行" min-width="180"><template #default="{ row }">{{ row.trigger_type === 'scheduled' ? formatTime(schedules[row.id]?.last_run_at) : '-' }}</template></el-table-column><el-table-column label="最近 Execution" min-width="220"><template #default="{ row }"><el-button v-if="schedules[row.id]?.last_execution_id" link type="primary" @click="openScheduledExecution(schedules[row.id]?.last_execution_id)">{{ schedules[row.id]?.last_execution_id }}</el-button><span v-else>-</span></template></el-table-column><el-table-column label="操作" min-width="380" fixed="right"><template #default="{ row }"><el-button v-if="row.trigger_type === 'manual'" size="small" type="primary" link :disabled="!triggerActionAllowed(asTrigger(row), 'invoke')" @click="requestInvoke(asTrigger(row))">立即运行</el-button><el-button v-if="row.status === 'disabled'" size="small" type="success" link :disabled="!triggerActionAllowed(asTrigger(row), 'enable')" @click="requestTriggerStatusAction(asTrigger(row), 'enable')">启用</el-button><el-button v-if="row.status === 'enabled'" size="small" type="warning" link :disabled="!triggerActionAllowed(asTrigger(row), 'disable')" @click="requestTriggerStatusAction(asTrigger(row), 'disable')">停用</el-button><template v-if="row.trigger_type !== 'manual'"><el-button size="small" type="primary" link :disabled="selected.status === 'archived'" @click="openTriggerEditor(asTrigger(row))">编辑配置</el-button></template><el-button size="small" type="danger" link :disabled="selected.status === 'archived' || !triggerActionAllowed(asTrigger(row), 'delete')" @click="requestDeleteTrigger(asTrigger(row))">删除</el-button></template></el-table-column></el-table><StatePanel v-else state="empty" title="暂无触发器" description="发布工作流后可配置手动、定时或 Webhook 入口。" /></SurfaceCard>
        <el-alert v-if="selected.status === 'archived'" title="该工作流已归档，生命周期数据保持可观测但不再允许继续变更。" type="warning" :closable="false" show-icon />
      </template>
    </template>
    <ConfirmDialog v-model="invokeDialogVisible" title="立即运行工作流" :description="`将通过手动触发器“${invokeTarget?.name ?? ''}”提交一次 Execution。本次使用空输入数据，是否继续？`" confirm-text="立即运行" :loading="invokeLoading" @confirm="confirmInvoke" @cancel="cancelInvoke" />
    <ConfirmDialog v-model="executionDialogVisible" :title="executionDialogTitle" :description="executionDialogDescription" :confirm-text="executionAction ? actionText[executionAction] : '确认'" :danger="executionAction === 'cancel'" :loading="executionActionLoading" @confirm="confirmExecutionAction" @cancel="cancelExecutionAction" />
    <ConfirmDialog v-model="triggerActionDialogVisible" :title="triggerActionDialogTitle" :description="triggerActionDialogDescription" :confirm-text="triggerAction ? triggerActionText[triggerAction] : '确认'" :danger="false" :loading="triggerActionLoading" @confirm="confirmTriggerStatusAction" @cancel="cancelTriggerStatusAction" />
    <ConfirmDialog v-model="deleteTriggerDialogVisible" title="删除 Trigger" :description="`将永久删除 Trigger “${deleteTriggerTarget?.name ?? ''}” 。该操作不会删除既有 Execution / Trace / Audit 事实，但会移除后续 Trigger 入口，是否继续？`" confirm-text="删除" :danger="true" :loading="deleteTriggerLoading" @confirm="confirmDeleteTrigger" @cancel="cancelDeleteTrigger" />
    <el-dialog v-model="triggerEditorVisible" :title="triggerEditorTitle" width="560px" :close-on-click-modal="!triggerEditorLoading" :close-on-press-escape="!triggerEditorLoading"><p class="dialog-description">{{ triggerEditorDescription }}</p><el-form label-position="top"><el-form-item label="名称"><el-input v-model="triggerEditor.name" maxlength="100" /></el-form-item><template v-if="triggerEditor.trigger?.trigger_type === 'scheduled'"><el-form-item label="Timezone"><el-input v-model="triggerEditor.timezone" /></el-form-item><el-form-item label="间隔（秒）"><el-input-number v-model="triggerEditor.interval_seconds" :min="60" :max="86400" /></el-form-item><el-form-item label="Misfire 策略"><el-select v-model="triggerEditor.misfire_policy"><el-option label="skip" value="skip" /><el-option label="fire_once" value="fire_once" /><el-option label="catch_up" value="catch_up" /></el-select></el-form-item><el-form-item label="Catch-up 上限"><el-input-number v-model="triggerEditor.catch_up_limit" :min="1" :max="100" :disabled="triggerEditor.misfire_policy !== 'catch_up'" /></el-form-item></template><template v-else><el-form-item label="Event ID 字段"><el-input v-model="triggerEditor.event_id_field" /></el-form-item><el-form-item label="新 Secret"><el-input v-model="triggerEditor.secret" type="password" show-password /></el-form-item></template></el-form><template #footer><el-button :disabled="triggerEditorLoading" @click="cancelTriggerEditor">取消</el-button><el-button type="primary" :loading="triggerEditorLoading" @click="saveTriggerEditor">保存</el-button></template></el-dialog>
  </main>
</template>

<style scoped>
.lifecycle-page{padding:24px 32px;min-height:100%}.workflow-selector{margin-bottom:16px}.workflow-selector__row{display:flex;align-items:center;gap:16px}.workflow-identity{display:flex;flex-direction:column;gap:3px;min-width:220px;flex:1}.workflow-identity strong{font-size:14px;color:var(--ui-text-primary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.workflow-identity span,.muted{font-size:12px;color:var(--ui-text-tertiary)}.workflow-selector .el-select{width:320px}.lifecycle-card{display:flex;align-items:center;gap:4px;padding:18px;margin-bottom:16px;background:var(--ui-bg-surface);border:1px solid var(--ui-border-default);border-radius:var(--ui-radius-lg)}.step{display:flex;align-items:center;gap:7px;flex:1;color:var(--ui-text-tertiary);font-size:12px}.step strong{color:var(--ui-text-secondary)}.step.done strong,.step.active strong{color:var(--ui-text-primary)}.step-index{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;border:1px solid var(--ui-border-default);font-size:11px}.step.done .step-index{color:var(--ui-color-success-500)}.step.active .step-index{color:var(--ui-color-primary-500)}.step i{margin-left:auto;font-style:normal}.detail-grid{display:grid;grid-template-columns:minmax(0,1fr);gap:16px}.execution-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap;margin-top:12px}.availability-summary{display:flex;gap:4px;flex-wrap:wrap}.error-code{font-size:12px;color:var(--ui-color-danger-500)}.error-message{margin-top:8px;font-size:12px;color:var(--ui-text-secondary);line-height:1.5}.focus-tag{margin-left:8px}.execution-focus-card,.diagnostic-context-card,.trigger-card{margin-top:16px}.focus-summary,.diagnostic-context{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.focus-summary>div,.diagnostic-context>div{display:flex;flex-direction:column;gap:5px;padding:10px 12px;border:1px solid var(--ui-border-default);border-radius:8px;background:var(--ui-bg-subtle)}.focus-summary span,.diagnostic-context span{font-size:10px;color:var(--ui-text-tertiary)}.focus-summary strong,.diagnostic-context strong{font-size:12px;word-break:break-all;color:var(--ui-text-primary)}.dialog-description{margin:0 0 16px;color:var(--ui-text-secondary);font-size:13px;line-height:1.5}.lifecycle-page>.el-alert{margin-top:16px}@media(max-width:900px){.lifecycle-page{padding:16px}.workflow-selector__row{flex-wrap:wrap}.workflow-identity{width:100%;min-width:0}.workflow-selector .el-select{width:100%}.lifecycle-card{display:grid;grid-template-columns:1fr 1fr}.step i{display:none}.focus-summary,.diagnostic-context{grid-template-columns:1fr 1fr}.execution-actions{justify-content:flex-start}}@media(max-width:600px){.focus-summary,.diagnostic-context{grid-template-columns:1fr}}
</style>
