$ErrorActionPreference = "Stop"
$backendRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backendRoot

function Invoke-CommandChecked {
    param(
        [string]$Description,
        [scriptblock]$Command
    )
    Write-Host $Description
    & $Command
    if ($LASTEXITCODE -ne 0) {
        throw "Test gate failed: $Description"
    }
}

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Scheduler Lease Concurrency Gate"
Write-Host "============================================================"
Write-Host "[0/3] Local precondition checks"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
Write-Host "Test data policy: all tenants, users, workflows, triggers, schedules and IDs are generated by the test."
Write-Host "Warning policy: warnings are treated as test errors."

Write-Host "[1/3] PostgreSQL readiness"
$postgresCheck = @"
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))

asyncio.run(main())
"@
$postgresCheck | uv run python -
if ($LASTEXITCODE -ne 0) {
    Write-Host "[NOT EXECUTED] PostgreSQL is not reachable through the configured backend database URL."
    Write-Host "This gate intentionally does not start PostgreSQL or any other protected service."
    exit 2
}

Write-Host "[2/3] Scheduler Repository concurrency integration"
$env:RUN_DATABASE_INTEGRATION = "1"
try {
    uv run pytest -q -W error tests/integration/test_workflow_scheduler_repository.py -m integration --tb=long
    if ($LASTEXITCODE -ne 0) {
        throw "Scheduler Repository concurrency integration failed."
    }
}
finally {
    Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
}

Write-Host "[3/3] Gate result"
Write-Host "[PASS] PostgreSQL readiness verified without service lifecycle changes."
Write-Host "[PASS] Concurrent Scheduler lease claim has exactly one winner."
Write-Host "[PASS] Persisted lease owner is verified after concurrent contention."
Write-Host "[PASS] Test fixtures and identifiers are generated and isolated by the test."
Write-Host "[PASS] Scheduler Lease Concurrency Gate completed."
