$ErrorActionPreference = 'Stop'

Write-Host '============================================================'
Write-Host 'Enterprise AI Agent Platform - Scheduler Misfire / Lease Gate'
Write-Host '============================================================'
Write-Host '[0/4] Local precondition checks'
Write-Host 'Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis.'
Write-Host 'Test data policy: all tenants, users, workflows, triggers, schedules and IDs are generated by the test.'
Write-Host 'Warning policy: warnings are treated as test errors.'

$backend = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
Set-Location $backend

Write-Host '[1/4] PostgreSQL readiness'
$readiness = @'
import asyncio
from sqlalchemy import text
from app.infrastructure.db.session import engine

async def main():
    try:
        async with engine.connect() as connection:
            await connection.execute(text("SELECT 1"))
    finally:
        await engine.dispose()

asyncio.run(main())
'@

$previousIntegration = $env:RUN_DATABASE_INTEGRATION
try {
    Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
    uv run python -c $readiness
    if ($LASTEXITCODE -ne 0) {
        Write-Host '[NOT EXECUTED] PostgreSQL is not ready; no service lifecycle action was attempted.'
        exit 2
    }

    Write-Host '[2/4] Scheduler misfire unit regression'
    uv run pytest -q -W error tests/unit/services/workflow_scheduler/test_misfire.py --tb=long
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host '[3/4] Scheduler lease expiry PostgreSQL acceptance'
    $env:RUN_DATABASE_INTEGRATION = '1'
    uv run pytest -q -W error tests/integration/test_workflow_scheduler_lease_expiry.py -m integration --tb=long
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host '[4/4] Gate result'
    Write-Host '[PASS] PostgreSQL readiness verified without service lifecycle changes.'
    Write-Host '[PASS] skip / fire_once / catch_up misfire semantics are covered by deterministic unit tests.'
    Write-Host '[PASS] Expired Scheduler lease can be reclaimed by a new owner.'
    Write-Host '[PASS] Stale owner cannot release the reclaimed lease.'
    Write-Host '[PASS] Test fixtures and identifiers are generated and isolated by the tests.'
    Write-Host '[PASS] Scheduler Misfire / Lease Gate completed.'
}
finally {
    if ($null -eq $previousIntegration) {
        Remove-Item Env:RUN_DATABASE_INTEGRATION -ErrorAction SilentlyContinue
    } else {
        $env:RUN_DATABASE_INTEGRATION = $previousIntegration
    }
}
