"""Scheduler Runtime PostgreSQL 闭环 Gate。

职责：检查 PostgreSQL 已就绪后执行 Scheduler Runtime 真实验收与 Due Candidate 边界验收。
边界：只做 readiness 与测试编排，不创建、启动、重启或停止 API、Scheduler、Worker、PostgreSQL、Redis。
"""

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

Write-Host "============================================================"
Write-Host "Enterprise AI Agent Platform - Scheduler Runtime Gate"
Write-Host "============================================================"
Write-Host "[0/5] Local precondition checks"
Write-Host "Service policy: this gate never creates, starts, restarts, or stops API, Scheduler, Worker, PostgreSQL, or Redis."
Write-Host "Test data policy: all tenants, users, workflows, triggers, schedules and IDs are generated by the test."
Write-Host "Warning policy: warnings are treated as test errors."

Write-Host "[1/5] PostgreSQL readiness"
$readiness = @'
import asyncio
from app.infrastructure.db.session import engine

async def main():
    async with engine.connect() as connection:
        await connection.exec_driver_sql("SELECT 1")

asyncio.run(main())
'@
$readiness | uv run python -
if ($LASTEXITCODE -ne 0) {
    Write-Host "[NOT EXECUTED] PostgreSQL is not ready."
    Write-Host "Standard startup command: start the project's existing PostgreSQL dependency using your normal local environment."
    exit 0
}

Write-Host "[2/5] Scheduler Runtime PostgreSQL acceptance"
$env:RUN_DATABASE_INTEGRATION = "1"
uv run pytest -q -W error tests/integration/test_workflow_scheduler_runtime.py -m integration --tb=long
if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] Scheduler Runtime PostgreSQL acceptance failed."
    exit $LASTEXITCODE
}

Write-Host "[3/5] Scheduler Due Candidate dirty-data boundary"
uv run pytest -q -W error tests/integration/test_workflow_scheduler_runtime_boundaries.py -m integration --tb=long
if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] Scheduler Due Candidate dirty-data boundary failed."
    exit $LASTEXITCODE
}

Write-Host "[4/5] Scheduler Runtime targeted regression"
uv run pytest -q -W error tests/unit/services/workflow_scheduler/test_misfire.py tests/integration/test_workflow_scheduler_repository.py tests/integration/test_workflow_scheduler_lease_expiry.py -m "unit or integration" --tb=long
if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] Scheduler Runtime targeted regression failed."
    exit $LASTEXITCODE
}

Write-Host "[5/5] Gate result"
Write-Host "[PASS] PostgreSQL readiness verified without service lifecycle changes."
Write-Host "[PASS] Scheduler Runtime persists misfire slots, ScheduleSlot, WorkflowExecution and Durable Frontier."
Write-Host "[PASS] Scheduled Execution writes tenant/workflow/execution-linked Audit and Trace facts."
Write-Host "[PASS] Due Candidate discovery excludes disabled, future and missing-schedule dirty workflows."
Write-Host "[PASS] Runtime advances next_run_at and releases the Scheduler lease atomically."
Write-Host "[PASS] Scheduler Runtime targeted regression completed."